package tenant.classes;
// Generated 10 Jun, 2016 10:18:54 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "accessory_type", schema = "arete_tms"
)
public class AccessoryType implements java.io.Serializable {

    private Integer SNo;
    private String userId;
    private String orgId;
    private String accessoryCode;
    private String accessoryName;
    private String accessoryDesc;
    private String status;
    private Date lastmodifiedDate;

    public AccessoryType() {
    }

    public AccessoryType(String userId, String orgId, String accessoryCode, String accessoryName, String accessoryDesc, String status, Date lastmodifiedDate) {
        this.userId = userId;
        this.orgId = orgId;
        this.accessoryCode = accessoryCode;
        this.accessoryName = accessoryName;
        this.accessoryDesc = accessoryDesc;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    public AccessoryType(Integer SNo, String userId, String orgId, String accessoryCode, String accessoryName, String accessoryDesc, String status, Date lastmodifiedDate) {
        this.SNo = SNo;
        this.userId = userId;
        this.orgId = orgId;
        this.accessoryCode = accessoryCode;
        this.accessoryName = accessoryName;
        this.accessoryDesc = accessoryDesc;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "s_no", unique = true, nullable = false)
    public Integer getSNo() {
        return this.SNo;
    }

    public void setSNo(Integer SNo) {
        this.SNo = SNo;
    }

    @Column(name = "user_id", length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "org_id", length = 11)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "status", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lastmodified_date", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Column(name = "accessory_code", length = 60)
    public String getAccessoryCode() {
        return accessoryCode;
    }

    public void setAccessoryCode(String accessoryCode) {
        this.accessoryCode = accessoryCode;
    }

    @Column(name = "accessory_name", length = 60)
    public String getAccessoryName() {
        return accessoryName;
    }

    public void setAccessoryName(String accessoryName) {
        this.accessoryName = accessoryName;
    }

    @Column(name = "accessory_desc", length = 250)
    public String getAccessoryDesc() {
        return accessoryDesc;
    }

    public void setAccessoryDesc(String accessoryDesc) {
        this.accessoryDesc = accessoryDesc;
    }

}
