package tenant.classes;
// Generated 21 Sep, 2016 3:04:58 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccessoriesTagging generated by hbm2java
 */
@Entity
@Table(name = "accessories_tagging", schema = "arete_tms"
)
public class AccessoriesTagging implements java.io.Serializable {

    private Integer SNo;
    private String assetCode;
    private String assetName;
    private String subAssetCode;
    private String subAssetName;
    private String accessoryCode;
    private String accessoryName;
    private String accessoryCat;
    private String quantity;
    private Date creationDate;
    private String status;
    private Date lastmodifiedDate;
    private String orgId;
    private String userId;
    private String remarks;

    public AccessoriesTagging() {
    }

    public AccessoriesTagging(String assetCode, String assetName, String subAssetCode, String subAssetName, String accessoryCode, String accessoryName, String accessoryCat, Date creationDate, String status, Date lastmodifiedDate, String orgId, String userId, String remarks, String quantity) {
        this.assetCode = assetCode;
        this.assetName = assetName;
        this.subAssetCode = subAssetCode;
        this.subAssetName = subAssetName;
        this.accessoryCode = accessoryCode;
        this.accessoryName = accessoryName;
        this.accessoryCat = accessoryCat;
        this.creationDate = creationDate;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.orgId = orgId;
        this.userId = userId;
        this.remarks = remarks;
        this.quantity = quantity;
    }

    public AccessoriesTagging(Integer SNo, String assetCode, String assetName, String subAssetCode, String subAssetName, String accessoryCode, String accessoryName, String accessoryCat, Date creationDate, String status, Date lastmodifiedDate, String orgId, String userId, String remarks, String quantity) {
        this.SNo = SNo;
        this.assetCode = assetCode;
        this.assetName = assetName;
        this.subAssetCode = subAssetCode;
        this.subAssetName = subAssetName;
        this.accessoryCode = accessoryCode;
        this.accessoryName = accessoryName;
        this.accessoryCat = accessoryCat;
        this.creationDate = creationDate;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.orgId = orgId;
        this.userId = userId;
        this.remarks = remarks;
        this.quantity = quantity;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "s_no", unique = true, nullable = false)
    public Integer getSNo() {
        return this.SNo;
    }

    public void setSNo(Integer SNo) {
        this.SNo = SNo;
    }

    @Column(name = "asset_code", length = 60)
    public String getAssetCode() {
        return this.assetCode;
    }

    public void setAssetCode(String assetCode) {
        this.assetCode = assetCode;
    }

    @Column(name = "asset_name", length = 60)
    public String getAssetName() {
        return this.assetName;
    }

    public void setAssetName(String assetName) {
        this.assetName = assetName;
    }

    @Column(name = "sub_asset_code", length = 60)
    public String getSubAssetCode() {
        return this.subAssetCode;
    }

    public void setSubAssetCode(String subAssetCode) {
        this.subAssetCode = subAssetCode;
    }

    @Column(name = "sub_asset_name", length = 60)
    public String getSubAssetName() {
        return this.subAssetName;
    }

    public void setSubAssetName(String subAssetName) {
        this.subAssetName = subAssetName;
    }

    @Column(name = "accessory_code", length = 60)
    public String getAccessoryCode() {
        return this.accessoryCode;
    }

    public void setAccessoryCode(String accessoryCode) {
        this.accessoryCode = accessoryCode;
    }

    @Column(name = "accessory_name", length = 60)
    public String getAccessoryName() {
        return this.accessoryName;
    }

    public void setAccessoryName(String accessoryName) {
        this.accessoryName = accessoryName;
    }

    @Column(name = "accessory_cat", length = 60)
    public String getAccessoryCat() {
        return this.accessoryCat;
    }

    public void setAccessoryCat(String accessoryCat) {
        this.accessoryCat = accessoryCat;
    }

    @Column(name = "quantity", length = 60)
    public String getQuantity() {
        return this.quantity;
    }

    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "creation_date", length = 19)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Column(name = "status", length = 60)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lastmodified_date", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Column(name = "org_id", length = 60)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "user_id", length = 60)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "remarks", length = 500)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

}
