package tenant.classes;
// Generated 9 Jun, 2016 9:41:56 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApprovalLevel generated by hbm2java
 */
@Entity
@Table(name = "approval_level", schema = "arete_tms"
)
public class ApprovalLevel implements java.io.Serializable {

    private Integer sno;
    private String orgName;
    private String orgId;
    private String moduleName;
    private String submoduleName;
    private String tabName;
    private String approvalLevel;
    private String userName;
    private String userId;
    private String approvalRole;
    private String approverEmailId;
    private Integer levelNo;
    private String status;
    private Date lastmodifiedDate;

    public ApprovalLevel() {
    }

    public ApprovalLevel(String orgName, String moduleName, String submoduleName, String tabName, String approvalLevel, String userName, String userId, String approvalRole, Integer levelNo, String status, Date lastmodifiedDate) {
        this.orgName = orgName;
        this.moduleName = moduleName;
        this.submoduleName = submoduleName;
        this.tabName = tabName;
        this.approvalLevel = approvalLevel;
        this.userName = userName;
        this.userId = userId;
        this.approvalRole = approvalRole;
        this.levelNo = levelNo;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "SNO", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "ORG_NAME", length = 50)
    public String getOrgName() {
        return this.orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    @Column(name = "MODULE_NAME", length = 100)
    public String getModuleName() {
        return this.moduleName;
    }

    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    @Column(name = "SUBMODULE_NAME", length = 80)
    public String getSubmoduleName() {
        return this.submoduleName;
    }

    public void setSubmoduleName(String submoduleName) {
        this.submoduleName = submoduleName;
    }

    @Column(name = "TAB_NAME", length = 80)
    public String getTabName() {
        return this.tabName;
    }

    public void setTabName(String tabName) {
        this.tabName = tabName;
    }

    @Column(name = "Approval_level", length = 50)
    public String getApprovalLevel() {
        return this.approvalLevel;
    }

    public void setApprovalLevel(String approvalLevel) {
        this.approvalLevel = approvalLevel;
    }

    @Column(name = "USER_NAME", length = 50)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Column(name = "USER_ID", length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "Approval_Role", length = 50)
    public String getApprovalRole() {
        return this.approvalRole;
    }

    public void setApprovalRole(String approvalRole) {
        this.approvalRole = approvalRole;
    }

    @Column(name = "level_no")
    public Integer getLevelNo() {
        return this.levelNo;
    }

    public void setLevelNo(Integer levelNo) {
        this.levelNo = levelNo;
    }

    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTMODIFIED_DATE", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }
    @Column(name = "APPROVER_EMAIL_ID", length = 200)
    public String getApproverEmailId() {
        return this.approverEmailId;
    }

    public void setApproverEmailId(String approverEmailId) {
        this.approverEmailId = approverEmailId;
    }
    @Column(name = "ORG_ID", length = 100)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

}
