package tenant.classes;
// Generated 13 Oct, 2016 5:14:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AssetClass generated by hbm2java
 */
@Entity
@Table(name = "ASSET_CLASS", schema = "arete_tms"
)
public class AssetClass implements java.io.Serializable {

    private Integer SNo;
    private String userId;
    private String orgId;
    private String assetClassId;
    private String assetClassName;
    private String assetClassDescription;
    private String status;
    private Date createdDate;
    private Date lastModifiedDate;

    public AssetClass() {
    }

    public AssetClass(String userId, String orgId, String assetClassCodeId, String assetClassName, String assetClassDescription, String status, Date today_date_and_time_created_user, Date today_date_and_time_updated_user) {
        this.userId = userId;
        this.orgId = orgId;
        this.assetClassId = assetClassCodeId;
        this.assetClassName = assetClassName;
        this.assetClassDescription = assetClassDescription;
        this.status = status;
        this.createdDate = today_date_and_time_created_user;
        this.lastModifiedDate = today_date_and_time_updated_user;
    }

    public AssetClass(Integer Sno, String userId, String orgId, String assetClassCodeId, String assetClassName, String assetClassDescription, String status, Date today_date_and_time_created_user, Date today_date_and_time_updated_user) {
        this.SNo = Sno;
        this.userId = userId;
        this.orgId = orgId;
        this.assetClassId = assetClassCodeId;
        this.assetClassName = assetClassName;
        this.assetClassDescription = assetClassDescription;
        this.status = status;
        this.createdDate = today_date_and_time_created_user;
        this.lastModifiedDate = today_date_and_time_updated_user;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "s_no", unique = true, nullable = false)
    public Integer getSNo() {
        return this.SNo;
    }

    public void setSNo(Integer SNo) {
        this.SNo = SNo;
    }

    @Column(name = "user_id", length = 60)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "org_Id", length = 60)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "asset_class_id", length = 60)
    public String getAssetClassId() {
        return this.assetClassId;
    }

    public void setAssetClassId(String assetClassId) {
        this.assetClassId = assetClassId;
    }

    @Column(name = "asset_class_name", length = 60)
    public String getAssetClassName() {
        return this.assetClassName;
    }

    public void setAssetClassName(String assetClassName) {
        this.assetClassName = assetClassName;
    }

    @Column(name = "asset_class_description", length = 600)
    public String getAssetClassDescription() {
        return this.assetClassDescription;
    }

    public void setAssetClassDescription(String assetClassDescription) {
        this.assetClassDescription = assetClassDescription;
    }

    @Column(name = "status", length = 60)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "createdDate", length = 10)
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "lastModifiedDate", length = 10)
    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

}
