package tenant.classes;
// Generated 21 Sep, 2016 3:04:58 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AssetDetails generated by hbm2java
 */
@Entity
@Table(name = "asset_details", schema = "arete_tms")      
public class AssetDetails implements java.io.Serializable {

    private int SNo;
    private String assetArea;
    private String assetBuilding;
    private String assetCategoryId;
    private String assetClassId;
    private String assetCode;
    private String assetName;
    private String assetOwnerType;
    private String assetPlotNo;
    private String assetType;
    private String amcassetName;
    private Date startDate;
    private Date endDate;
    private String percentage;
    private String amcamount;
    private String basement;
    private String blockNo;
    private String buildedArea;
    private String classificationArea;
    private Date lastmodifiedDate;
    private String length;
    private String mezzanineFloor;
    private String minimumRentGen;
    private String noOfFloors;
    private String orgId;
    private String parking;
    private String pentHouse;
    private String pinCode;
    private String poBox;
    private String roi;
    private String status;
    private String streetNo;
    private String swimmingPool;
    private String totalAssetValue;
    private String userId;
    private String way;
    private String width;
    private String ccname;
    private String sname;
    private String scontact;
    private String semail;
    private String saddress;

    private Date bcDate;
    
    private String wilayat;
    private String city;

    //newly added by lakshmi
    private String lifeSpanOfBld;
    private Date nextRevDate;
    private String storeName;
    private String storeID;
    private String areaCode;
    private String areaStatus;

    //////////
    public AssetDetails() {
    }

    public AssetDetails(String assetArea, String assetBuilding, String assetCategoryId, String assetClassId, String assetCode, String assetName,
            String assetOwnerType, String assetPlotNo, String assetType, String amcassetName, Date startDate, Date endDate, String percentage,
            String amcamount, String basement, String blockNo, String buildedArea, String classificationArea, Date lastmodifiedDate, 
            String mezzanineFloor, String minimumRentGen, String noOfFloors, String orgId, String parking, String pentHouse, String pinCode, 
            String poBox, String roi, String status, String streetNo, String swimmingPool, String totalAssetValue, String userId,
            String way, String storeName, String storeID,String wilayat,String city) {
        this.assetArea = assetArea;
        this.assetBuilding = assetBuilding;
        this.assetCategoryId = assetCategoryId;
        this.assetClassId = assetClassId;
        this.assetCode = assetCode;
        this.assetName = assetName;
        this.assetOwnerType = assetOwnerType;
        this.assetPlotNo = assetPlotNo;
        this.assetType = assetType;
        this.amcassetName = amcassetName;
        this.startDate = startDate;
        this.endDate = endDate;
        this.percentage = percentage;
        this.amcamount = amcamount;
        this.basement = basement;
        this.blockNo = blockNo;
        this.buildedArea = buildedArea;
        this.classificationArea = classificationArea;
        this.lastmodifiedDate = lastmodifiedDate;
        this.length = length;
        this.mezzanineFloor = mezzanineFloor;
        this.minimumRentGen = minimumRentGen;
        this.noOfFloors = noOfFloors;
        this.orgId = orgId;
        this.parking = parking;
        this.pentHouse = pentHouse;
        this.pinCode = pinCode;
        this.poBox = poBox;
        this.roi = roi;
        this.status = status;
        this.streetNo = streetNo;
        this.swimmingPool = swimmingPool;
        this.totalAssetValue = totalAssetValue;
        this.userId = userId;
        this.way = way;
        this.width = width;
        this.storeName = storeName;
        this.storeID = storeID;
        this.wilayat = wilayat;
        this.city = city;
    }

    public AssetDetails(String ccname, Date bcDate, String lifeSpanOfBld, Date nextRevDate, String sname, String scontact, String semail, 
            String saddress, String assetArea, String assetBuilding, String assetCategoryId, String assetClassId, String assetCode,
            String assetName, String assetOwnerType, String assetPlotNo, String assetType, String amcassetName, Date startDate,
            Date endDate, String percentage, String amcamount, String basement, String blockNo, String buildedArea,
            String classificationArea, Date lastmodifiedDate, String mezzanineFloor, String minimumRentGen,
            String noOfFloors, String orgId, String parking, String pentHouse, String pinCode, String poBox,
            String roi, String status, String streetNo, String swimmingPool, String totalAssetValue, String userId, 
            String way, String storeName, String storeID,String areaCode,String areaStatus,String wilayat,String city) {
        this.assetArea = assetArea;
        this.assetBuilding = assetBuilding;
        this.assetCategoryId = assetCategoryId;
        this.assetClassId = assetClassId;
        this.assetCode = assetCode;
        this.assetName = assetName;
        this.assetOwnerType = assetOwnerType;
        this.assetPlotNo = assetPlotNo;
        this.assetType = assetType;
        this.amcassetName = amcassetName;
        this.startDate = startDate;
        this.endDate = endDate;
        this.percentage = percentage;
        this.amcamount = amcamount;
        this.basement = basement;
        this.blockNo = blockNo;
        this.buildedArea = buildedArea;
        this.classificationArea = classificationArea;
        this.lastmodifiedDate = lastmodifiedDate;
        this.length = length;
        this.mezzanineFloor = mezzanineFloor;
        this.minimumRentGen = minimumRentGen;
        this.noOfFloors = noOfFloors;
        this.orgId = orgId;
        this.parking = parking;
        this.pentHouse = pentHouse;
        this.pinCode = pinCode;
        this.poBox = poBox;
        this.roi = roi;
        this.status = status;
        this.streetNo = streetNo;
        this.swimmingPool = swimmingPool;
        this.totalAssetValue = totalAssetValue;
        this.userId = userId;
        this.way = way;
        this.width = width;
        this.ccname = ccname;
        this.bcDate = bcDate;
        ///////
        this.lifeSpanOfBld = lifeSpanOfBld;
        this.nextRevDate = nextRevDate;
        ////////
        this.sname = sname;
        this.scontact = scontact;
        this.semail = semail;
        this.saddress = saddress;
        this.storeName = storeName;
        this.storeID = storeID;
        this.areaCode = areaCode;
        this.areaStatus= areaStatus;
        this.wilayat = wilayat;
        this.city = city;

    }
    
    public AssetDetails(int SNo, String ccname, Date bcDate, String lifeSpanOfBld, Date nextRevDate, String sname, String scontact, String semail, 
            String saddress, String assetArea, String assetBuilding, String assetCategoryId, String assetClassId, String assetCode,
            String assetName, String assetOwnerType, String assetPlotNo, String assetType, String amcassetName, Date startDate,
            Date endDate, String percentage, String amcamount, String basement, String blockNo, String buildedArea,
            String classificationArea, Date lastmodifiedDate, String mezzanineFloor, String minimumRentGen,
            String noOfFloors, String orgId, String parking, String pentHouse, String pinCode, String poBox,
            String roi, String status, String streetNo, String swimmingPool, String totalAssetValue, String userId, 
            String way, String storeName, String storeID,String areaCode,String areaStatus,String wilayat,String city) {
        this.SNo = SNo;
        this.assetArea = assetArea;
        this.assetBuilding = assetBuilding;
        this.assetCategoryId = assetCategoryId;
        this.assetClassId = assetClassId;
        this.assetCode = assetCode;
        this.assetName = assetName;
        this.assetOwnerType = assetOwnerType;
        this.assetPlotNo = assetPlotNo;
        this.assetType = assetType;
        this.amcassetName = amcassetName;
        this.startDate = startDate;
        this.endDate = endDate;
        this.percentage = percentage;
        this.amcamount = amcamount;
        this.basement = basement;
        this.blockNo = blockNo;
        this.buildedArea = buildedArea;
        this.classificationArea = classificationArea;
        this.lastmodifiedDate = lastmodifiedDate;
        this.length = length;
        this.mezzanineFloor = mezzanineFloor;
        this.minimumRentGen = minimumRentGen;
        this.noOfFloors = noOfFloors;
        this.orgId = orgId;
        this.parking = parking;
        this.pentHouse = pentHouse;
        this.pinCode = pinCode;
        this.poBox = poBox;
        this.roi = roi;
        this.status = status;
        this.streetNo = streetNo;
        this.swimmingPool = swimmingPool;
        this.totalAssetValue = totalAssetValue;
        this.userId = userId;
        this.way = way;
        this.width = width;
        this.ccname = ccname;
        this.bcDate = bcDate;
        ///////
        this.lifeSpanOfBld = lifeSpanOfBld;
        this.nextRevDate = nextRevDate;
        ////////
        this.sname = sname;
        this.scontact = scontact;
        this.semail = semail;
        this.saddress = saddress;
        this.storeName = storeName;
        this.storeID = storeID;
        this.areaCode = areaCode;
        this.areaStatus = areaStatus;
        this.wilayat = wilayat;
        this.city = city;

    }

    public AssetDetails(int SNo, String ccname, Date bcDate, String lifeSpanOfBld, Date nextRevDate, String sname, String scontact, String semail, 
            String saddress, String assetArea, String assetBuilding, String assetCategoryId, String assetClassId, String assetCode,
            String assetName, String assetOwnerType, String assetPlotNo, String assetType, String amcassetName, Date startDate, 
            Date endDate, String percentage, String amcamount, String basement, String blockNo, String buildedArea, String classificationArea,
            Date lastmodifiedDate, String mezzanineFloor, String minimumRentGen, String noOfFloors, String orgId, String parking, String pentHouse, 
            String pinCode, String poBox, String roi, String status, String streetNo, String swimmingPool, String totalAssetValue, String userId,
            String way,String storeName, String storeID,String wilayat,String city) {
        this.SNo = SNo;
        this.assetArea = assetArea;
        this.assetBuilding = assetBuilding;
        this.assetCategoryId = assetCategoryId;
        this.assetClassId = assetClassId;
        this.assetCode = assetCode;
        this.assetName = assetName;
        this.assetOwnerType = assetOwnerType;
        this.assetPlotNo = assetPlotNo;
        this.assetType = assetType;
        this.amcassetName = amcassetName;
        this.startDate = startDate;
        this.endDate = endDate;
        this.percentage = percentage;
        this.amcamount = amcamount;
        this.basement = basement;
        this.blockNo = blockNo;
        this.buildedArea = buildedArea;
        this.classificationArea = classificationArea;
        this.lastmodifiedDate = lastmodifiedDate;
        this.length = length;
        this.mezzanineFloor = mezzanineFloor;
        this.minimumRentGen = minimumRentGen;
        this.noOfFloors = noOfFloors;
        this.orgId = orgId;
        this.parking = parking;
        this.pentHouse = pentHouse;
        this.pinCode = pinCode;
        this.poBox = poBox;
        this.roi = roi;
        this.status = status;
        this.streetNo = streetNo;
        this.swimmingPool = swimmingPool;
        this.totalAssetValue = totalAssetValue;
        this.userId = userId;
        this.way = way;
        this.width = width;
        this.ccname = ccname;
        this.bcDate = bcDate;
        ///////
        this.lifeSpanOfBld = lifeSpanOfBld;
        this.nextRevDate = nextRevDate;
        ///////
        this.sname = sname;
        this.scontact = scontact;
        this.semail = semail;
        this.saddress = saddress;
        this.storeName = storeName;
        this.storeID = storeID;
        this.wilayat = wilayat;
        this.city = city;

    }

    public AssetDetails(int SNo, String assetArea, String assetBuilding, String assetCategoryId, String assetClassId, String assetCode, String assetName,
            String assetOwnerType, String assetPlotNo, String assetType, String amcassetName, Date startDate, Date endDate, String percentage, 
            String amcamount, String basement, String blockNo, String buildedArea, String classificationArea, Date lastmodifiedDate,
            String mezzanineFloor, String minimumRentGen, String noOfFloors, String orgId, String parking, String pentHouse, String pinCode,
            String poBox, String roi, String status, String streetNo, String swimmingPool, String totalAssetValue, 
            String userId, String way,String wilayat,String city) {
        this.SNo = SNo;
        this.assetArea = assetArea;
        this.assetBuilding = assetBuilding;
        this.assetCategoryId = assetCategoryId;
        this.assetClassId = assetClassId;
        this.assetCode = assetCode;
        this.assetName = assetName;
        this.assetOwnerType = assetOwnerType;
        this.assetPlotNo = assetPlotNo;
        this.assetType = assetType;
        this.amcassetName = amcassetName;
        this.startDate = startDate;
        this.endDate = endDate;
        this.percentage = percentage;
        this.amcamount = amcamount;
        this.basement = basement;
        this.blockNo = blockNo;
        this.buildedArea = buildedArea;
        this.classificationArea = classificationArea;
        this.lastmodifiedDate = lastmodifiedDate;
        this.length = length;
        this.mezzanineFloor = mezzanineFloor;
        this.minimumRentGen = minimumRentGen;
        this.noOfFloors = noOfFloors;
        this.orgId = orgId;
        this.parking = parking;
        this.pentHouse = pentHouse;
        this.pinCode = pinCode;
        this.poBox = poBox;
        this.roi = roi;
        this.status = status;
        this.streetNo = streetNo;
        this.swimmingPool = swimmingPool;
        this.totalAssetValue = totalAssetValue;
        this.userId = userId;
        this.way = way;
        this.wilayat = wilayat;
        this.city = city;
       
    }

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "s_no", unique = true, nullable = false)
    public int getSNo() {
        return this.SNo;
    }

    public void setSNo(int SNo) {
        this.SNo = SNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Building_Constrction_Date", length = 19)
    public Date getBcDate() {
        return this.bcDate;
    }

    public void setBcDate(Date bcDate) {
        this.bcDate = bcDate;
    }
////Newly added by lakshmi///////

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Next_Revaluation_Date", length = 19)
    public Date getNextRevDate() {
        return nextRevDate;
    }

    public void setNextRevDate(Date nextRevDate) {
        this.nextRevDate = nextRevDate;
    }
//////////////////////////

    @Column(name = "asset_area", length = 60)
    public String getAssetArea() {
        return this.assetArea;
    }

    public void setAssetArea(String assetArea) {
        this.assetArea = assetArea;
    }

    @Column(name = "asset_building", length = 60)
    public String getAssetBuilding() {
        return this.assetBuilding;
    }

    public void setAssetBuilding(String assetBuilding) {
        this.assetBuilding = assetBuilding;
    }

    @Column(name = "asset_category_id", length = 60)
    public String getAssetCategoryId() {
        return assetCategoryId;
    }

    public void setAssetCategoryId(String assetCategoryId) {
        this.assetCategoryId = assetCategoryId;
    }

    @Column(name = "asset_class_id", length = 60)
    public String getAssetClassId() {
        return assetClassId;
    }

    public void setAssetClassId(String assetClassId) {
        this.assetClassId = assetClassId;
    }

    @Column(name = "asset_code", length = 60)
    public String getAssetCode() {
        return this.assetCode;
    }

    public void setAssetCode(String assetCode) {
        this.assetCode = assetCode;
    }

    @Column(name = "asset_name", length = 60)
    public String getAssetName() {
        return this.assetName;
    }

    public void setAssetName(String assetName) {
        this.assetName = assetName;
    }

    @Column(name = "asset_owner_type", length = 60)
    public String getAssetOwnerType() {
        return assetOwnerType;
    }

    public void setAssetOwnerType(String assetOwnerType) {
        this.assetOwnerType = assetOwnerType;
    }

    @Column(name = "asset_plot_no", length = 60)
    public String getAssetPlotNo() {
        return this.assetPlotNo;
    }

    public void setAssetPlotNo(String assetPlotNo) {
        this.assetPlotNo = assetPlotNo;
    }

    @Column(name = "asset_type", length = 60)
    public String getAssetType() {
        return this.assetType;
    }

    public void setAssetType(String assetType) {
        this.assetType = assetType;
    }

    @Column(name = "amc_assetName", length = 60)
    public String getAmcassetName() {
        return amcassetName;
    }

    public void setAmcassetName(String amcassetName) {
        this.amcassetName = amcassetName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_date", length = 19)
    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end_date", length = 19)
    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @Column(name = "percentage", length = 60)
    public String getPercentage() {
        return percentage;
    }

    public void setPercentage(String percentage) {
        this.percentage = percentage;
    }

    @Column(name = "amc_amount", length = 60)
    public String getAmcamount() {
        return amcamount;
    }

    public void setAmcamount(String amcamount) {
        this.amcamount = amcamount;
    }

    @Column(name = "basement", length = 60)
    public String getBasement() {
        return this.basement;
    }

    public void setBasement(String basement) {
        this.basement = basement;
    }

    @Column(name = "block_no", length = 60)
    public String getBlockNo() {
        return this.blockNo;
    }

    public void setBlockNo(String blockNo) {
        this.blockNo = blockNo;
    }

    @Column(name = "builded_area", length = 60)
    public String getBuildedArea() {
        return this.buildedArea;
    }

    public void setBuildedArea(String buildedArea) {
        this.buildedArea = buildedArea;
    }

    @Column(name = "classification_area", length = 60)
    public String getClassificationArea() {
        return this.classificationArea;
    }

    public void setClassificationArea(String classificationArea) {
        this.classificationArea = classificationArea;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lastmodified_date", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Column(name = "length", length = 60)
    public String getLength() {
        return this.length;
    }

    public void setLength(String length) {
        this.length = length;
    }

    @Column(name = "mezzanine_floor", length = 60)
    public String getMezzanineFloor() {
        return this.mezzanineFloor;
    }

    public void setMezzanineFloor(String mezzanineFloor) {
        this.mezzanineFloor = mezzanineFloor;
    }

    @Column(name = "minimum_rent_gen", length = 60)
    public String getMinimumRentGen() {
        return this.minimumRentGen;
    }

    public void setMinimumRentGen(String minimumRentGen) {
        this.minimumRentGen = minimumRentGen;
    }

    @Column(name = "no_of_floors", length = 60)
    public String getNoOfFloors() {
        return this.noOfFloors;
    }

    public void setNoOfFloors(String noOfFloors) {
        this.noOfFloors = noOfFloors;
    }

    @Column(name = "org_id", length = 50)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "parking", length = 60)
    public String getParking() {
        return this.parking;
    }

    public void setParking(String parking) {
        this.parking = parking;
    }

    @Column(name = "pent_house", length = 60)
    public String getPentHouse() {
        return this.pentHouse;
    }

    public void setPentHouse(String pentHouse) {
        this.pentHouse = pentHouse;
    }

    @Column(name = "pin_code")
    public String getPinCode() {
        return this.pinCode;
    }

    public void setPinCode(String pinCode) {
        this.pinCode = pinCode;
    }

    @Column(name = "po_box", length = 60)
    public String getPoBox() {
        return this.poBox;
    }

    public void setPoBox(String poBox) {
        this.poBox = poBox;
    }

    @Column(name = "roi", length = 60)
    public String getRoi() {
        return this.roi;
    }

    public void setRoi(String roi) {
        this.roi = roi;
    }

    @Column(name = "status", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "street_no", length = 60)
    public String getStreetNo() {
        return this.streetNo;
    }

    public void setStreetNo(String streetNo) {
        this.streetNo = streetNo;
    }

    @Column(name = "swimming_pool", length = 60)
    public String getSwimmingPool() {
        return this.swimmingPool;
    }

    public void setSwimmingPool(String swimmingPool) {
        this.swimmingPool = swimmingPool;
    }

    @Column(name = "total_asset_value", length = 60)
    public String getTotalAssetValue() {
        return this.totalAssetValue;
    }

    public void setTotalAssetValue(String totalAssetValue) {
        this.totalAssetValue = totalAssetValue;
    }

    @Column(name = "user_id", length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "way", length = 60)
    public String getWay() {
        return this.way;
    }

    public void setWay(String way) {
        this.way = way;
    }

    @Column(name = "width", length = 60)
    public String getWidth() {
        return this.width;
    }

    public void setWidth(String width) {
        this.width = width;
    }

    @Column(name = "Construction_Company_Name", length = 60)
    public String getCcname() {
        return this.ccname;
    }

    public void setCcname(String ccname) {
        this.ccname = ccname;
    }
////Newly added by lakshmi//////

    @Column(name = "Life_Span_Of_Building", length = 60)
    public String getLifeSpanOfBld() {
        return lifeSpanOfBld;
    }

    public void setLifeSpanOfBld(String lifeSpanOfBld) {
        this.lifeSpanOfBld = lifeSpanOfBld;
    }
////////////////////////////

    @Column(name = "Second_Owner_Address", length = 60)
    public String getSaddress() {
        return this.saddress;
    }

    public void setSaddress(String saddress) {
        this.saddress = saddress;
    }

    @Column(name = "Second_Owner_name", length = 60)
    public String getSname() {
        return this.sname;
    }

    public void setSname(String sname) {
        this.sname = sname;
    }

    @Column(name = "Second_Owner_ContactNo", length = 60)
    public String getScontact() {
        return this.scontact;
    }

    public void setScontact(String scontact) {
        this.scontact = scontact;
    }

    @Column(name = "Second_Owner_Email", length = 60)
    public String getSemail() {
        return this.semail;
    }

    public void setSemail(String semail) {
        this.semail = semail;
    }
    @Column(name = "Store_Name", length = 60)
    public String getStoreName() {
        return storeName;
    }

    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    @Column(name = "Store_ID", length = 60)
    public String getStoreID() {
        return storeID;
    }

    public void setStoreID(String storeID) {
        this.storeID = storeID;
    }

    @Column(name = "area_code")
    public String getAreaCode() {
        return areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    @Column(name = "wila_yat")
    public String getWilayat() {
        return wilayat;
    }

    public void setWilayat(String wilayat) {
        this.wilayat = wilayat;
    }

    @Column(name = "city")
    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "area_status")
    public String getAreaStatus() {
        return areaStatus;
    }

    public void setAreaStatus(String areaStatus) {
        this.areaStatus = areaStatus;
    }



    }
