package tenant.classes;
// Generated 13 Oct, 2016 5:14:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AssetCategory generated by hbm2java
 */
@Entity
@Table(name = "ASSET_CATEGORY", schema = "arete_tms"
)
public class AssetCategory implements java.io.Serializable {

    private Integer SNo;
    private String userId;
    private String orgId;
    private String assetCategoryId;
    private String assetCategoryName;
    private String assetCategoryDescription;
    private String status;
    private Date createdDate;
    private Date lastModifiedDate;

    public AssetCategory() {
    }

    public AssetCategory(String userId, String orgId, String assetCategoryId, String assetCategoryName, String assetCategoryDescription, String status, Date createdDate, Date lastModifiedDate) {
        this.userId = userId;
        this.orgId = orgId;
        this.assetCategoryId = assetCategoryId;
        this.assetCategoryName = assetCategoryName;
        this.assetCategoryDescription = assetCategoryDescription;
        this.status = status;
        this.createdDate = createdDate;
        this.lastModifiedDate = lastModifiedDate;
    }

    public AssetCategory(Integer Sno, String userId, String orgId, String assetCategoryId, String assetCategoryName, String assetCategoryDescription, String status, Date createdDate, Date lastModifiedDate) {
        this.SNo = Sno;
        this.userId = userId;
        this.orgId = orgId;
        this.assetCategoryId = assetCategoryId;
        this.assetCategoryName = assetCategoryName;
        this.assetCategoryDescription = assetCategoryDescription;
        this.status = status;
        this.createdDate = createdDate;
        this.lastModifiedDate = lastModifiedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "s_no", unique = true, nullable = false)
    public Integer getSNo() {
        return this.SNo;
    }

    public void setSNo(Integer SNo) {
        this.SNo = SNo;
    }

    @Column(name = "user_id", length = 60)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "org_Id", length = 60)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "asset_category_id", length = 60)
    public String getAssetCategoryId() {
        return this.assetCategoryId;
    }

    public void setAssetCategoryId(String assetCategoryId) {
        this.assetCategoryId = assetCategoryId;
    }

    @Column(name = "asset_category_name", length = 60)
    public String getAssetCategoryName() {
        return this.assetCategoryName;
    }

    public void setAssetCategoryName(String assetCategoryName) {
        this.assetCategoryName = assetCategoryName;
    }

    @Column(name = "asset_category_description", length = 600)
    public String getAssetCategoryDescription() {
        return this.assetCategoryDescription;
    }

    public void setAssetCategoryDescription(String assetCategoryDescription) {
        this.assetCategoryDescription = assetCategoryDescription;
    }

    @Column(name = "status", length = 60)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "createdDate", length = 10)
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "lastModifiedDate", length = 10)
    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

}
