package tenant.classes;
// Generated Sep 15, 2016 11:02:38 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BillPayment generated by hbm2java
 */
@Entity
@Table(name = "bill_payment", schema = "arete_tms"
)
public class BillPayment implements java.io.Serializable {

    private Integer SNo;
    private String orgId;
    private String userId;
    private String receiptNo;
    private Date receiptDate;
    private String receiptType;
    private String tenantCode;
    private String tenantName;
    private String assetName;
    private String buildingNo;
    private String blockNo;
    private String streetNo;
    private String plotNo;
    private Date period;
    private Date period1;
    private String srNo;
    private String rentAmount;
    private String totalAmount;
    private String dues;
    private String serviceDues;
    private String modeOfPayment;
    private String chequeNo;
    private String bankName;
    private String accountNo;
    private Date dated;
    private String amount;
    private String flotNo;
    private String subassetCode;
    private String otherAmount;
    private String prepaidAmount;
    private String extra1;
    private String extra2;
    private String extra3;
    private String extra4;
    private String extra5;
    private String chequeStatus;
    private String status;
    private Date creationDate;
    private Date lastmodifiedDate;
    private String serviceRequestedCost;
    private String penaltyType;
    private String penaltyamount;
    private String invoiceNumber;
    private String contractCode;

    public BillPayment(String orgId, String userId, String receiptNo, Date receiptDate, String receiptType, String tenantCode, String tenantName, String assetName, String buildingNo, String blockNo, String streetNo, String plotNo, Date period, Date period1, String srNo, String rentAmount, String totalAmount, String dues, String serviceDues, String modeOfPayment, String chequeNo, String bankName, String accountNo, Date dated, String amount, String flotNo, String subassetCode, String otherAmount, String prepaidAmount, String extra1, String extra2, String extra3, String extra4, String extra5, String status, Date creationDate, Date lastmodifiedDate, String serviceRequestedCost, String penaltyType, String penaltyamount,String invoiceNumber, String contractCode) {
        this.orgId = orgId;
        this.userId = userId;
        this.receiptNo = receiptNo;
        this.receiptDate = receiptDate;
        this.receiptType = receiptType;
        this.tenantCode = tenantCode;
        this.tenantName = tenantName;
        this.assetName = assetName;
        this.buildingNo = buildingNo;
        this.blockNo = blockNo;
        this.streetNo = streetNo;
        this.plotNo = plotNo;
        this.period = period;
        this.period1 = period1;
        this.srNo = srNo;
        this.rentAmount = rentAmount;
        this.totalAmount = totalAmount;
        this.dues = dues;
        this.serviceDues = serviceDues;
        this.modeOfPayment = modeOfPayment;
        this.chequeNo = chequeNo;
        this.bankName = bankName;
        this.accountNo = accountNo;
        this.dated = dated;
        this.amount = amount;
        this.flotNo = flotNo;
        this.subassetCode = subassetCode;
        this.otherAmount = otherAmount;
        this.prepaidAmount = prepaidAmount;
        this.extra1 = extra1;
        this.extra2 = extra2;
        this.extra3 = extra3;
        this.extra4 = extra4;
        this.extra5 = extra5;
        this.status = status;
        this.creationDate = creationDate;
        this.lastmodifiedDate = lastmodifiedDate;
        this.serviceRequestedCost = serviceRequestedCost;
        this.penaltyType = penaltyType;
        this.penaltyamount = penaltyamount;
        this.invoiceNumber = invoiceNumber;
        this.contractCode = contractCode;

    }

    public BillPayment(Integer SNo, String orgId, String userId, String receiptNo, Date receiptDate, String receiptType, String tenantCode, String tenantName, String assetName, String buildingNo, String blockNo, String streetNo, String plotNo, Date period, Date period1, String srNo, String rentAmount, String totalAmount, String dues, String serviceDues, String modeOfPayment, String chequeNo, String bankName, String accountNo, Date dated, String amount, String flotNo, String subassetCode, String otherAmount, String prepaidAmount, String extra1, String extra2, String extra3, String extra4, String extra5, String status, Date creationDate, Date lastmodifiedDate, String serviceRequestedCost, String penaltyType, String penaltyamount, String invoiceNumber, String contractCode) {

        this.SNo = SNo;
        this.orgId = orgId;
        this.userId = userId;
        this.receiptNo = receiptNo;
        this.receiptDate = receiptDate;
        this.receiptType = receiptType;
        this.tenantCode = tenantCode;
        this.tenantName = tenantName;
        this.assetName = assetName;
        this.buildingNo = buildingNo;
        this.blockNo = blockNo;
        this.streetNo = streetNo;
        this.plotNo = plotNo;
        this.period = period;
        this.period1 = period1;
        this.srNo = srNo;
        this.rentAmount = rentAmount;
        this.totalAmount = totalAmount;
        this.dues = dues;
        this.serviceDues = serviceDues;
        this.modeOfPayment = modeOfPayment;
        this.chequeNo = chequeNo;
        this.bankName = bankName;
        this.accountNo = accountNo;
        this.dated = dated;
        this.amount = amount;
        this.flotNo = flotNo;
        this.subassetCode = subassetCode;
        this.otherAmount = otherAmount;
        this.prepaidAmount = prepaidAmount;
        this.extra1 = extra1;
        this.extra2 = extra2;
        this.extra3 = extra3;
        this.extra4 = extra4;
        this.extra5 = extra5;
        this.status = status;
        this.creationDate = creationDate;
        this.lastmodifiedDate = lastmodifiedDate;
        this.serviceRequestedCost = serviceRequestedCost;
        this.penaltyType = penaltyType;
        this.penaltyamount = penaltyamount;
        this.invoiceNumber = invoiceNumber;
        this.contractCode = contractCode;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "s_no", unique = true, nullable = false)
    public Integer getSNo() {
        return this.SNo;
    }

    public void setSNo(Integer SNo) {
        this.SNo = SNo;
    }

    @Column(name = "org_id", length = 50)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "user_id", length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "receipt_no", length = 60)
    public String getReceiptNo() {
        return this.receiptNo;
    }

    public void setReceiptNo(String receiptNo) {
        this.receiptNo = receiptNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "receipt_date", length = 19)
    public Date getReceiptDate() {
        return this.receiptDate;
    }

    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }

    @Column(name = "receipt_type", length = 60)
    public String getReceiptType() {
        return this.receiptType;
    }

    public void setReceiptType(String receiptType) {
        this.receiptType = receiptType;
    }

    @Column(name = "tenant_code", length = 60)
    public String getTenantCode() {
        return this.tenantCode;
    }

    public void setTenantCode(String tenantCode) {
        this.tenantCode = tenantCode;
    }

    @Column(name = "tenant_name", length = 60)
    public String getTenantName() {
        return this.tenantName;
    }

    public void setTenantName(String tenantName) {
        this.tenantName = tenantName;
    }

    @Column(name = "asset_name", length = 60)
    public String getAssetName() {
        return this.assetName;
    }

    public void setAssetName(String assetName) {
        this.assetName = assetName;
    }
    
    @Column(name = "contractCode", length = 60)
    public String getContractCode() {
        return this.contractCode;
    }

    public void setContractCode(String contractCode) {
        this.contractCode = contractCode;
    }

    @Column(name = "building_no", length = 60)
    public String getBuildingNo() {
        return this.buildingNo;
    }

    public void setBuildingNo(String buildingNo) {
        this.buildingNo = buildingNo;
    }

    @Column(name = "block_no", length = 60)
    public String getBlockNo() {
        return this.blockNo;
    }

    public void setBlockNo(String blockNo) {
        this.blockNo = blockNo;
    }

    @Column(name = "street_no", length = 60)
    public String getStreetNo() {
        return this.streetNo;
    }

    public void setStreetNo(String streetNo) {
        this.streetNo = streetNo;
    }

    @Column(name = "plot_no", length = 60)
    public String getPlotNo() {
        return this.plotNo;
    }

    public void setPlotNo(String plotNo) {
        this.plotNo = plotNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "period", length = 20)
    public Date getPeriod() {
        return this.period;
    }

    public void setPeriod(Date period) {
        this.period = period;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "period1", length = 20)
    public Date getPeriod1() {
        return this.period1;
    }

    public void setPeriod1(Date period1) {
        this.period1 = period1;
    }

    @Column(name = "sr_no", length = 60)
    public String getSrNo() {
        return this.srNo;
    }

    public void setSrNo(String srNo) {
        this.srNo = srNo;
    }

    @Column(name = "rent_amount", length = 60)
    public String getRentAmount() {
        return this.rentAmount;
    }

    public void setRentAmount(String rentAmount) {
        this.rentAmount = rentAmount;
    }

    @Column(name = "total_amount", length = 60)
    public String getTotalAmount() {
        return this.totalAmount;
    }

    public void setTotalAmount(String totalAmount) {
        this.totalAmount = totalAmount;
    }

    @Column(name = "dues", length = 60)
    public String getDues() {
        return this.dues;
    }

    public void setDues(String dues) {
        this.dues = dues;
    }

    @Column(name = "service_dues", length = 60)
    public String getServiceDues() {
        return this.serviceDues;
    }

    public void setServiceDues(String serviceDues) {
        this.serviceDues = serviceDues;
    }

    @Column(name = "mode_of_payment", length = 60)
    public String getModeOfPayment() {
        return this.modeOfPayment;
    }

    public void setModeOfPayment(String modeOfPayment) {
        this.modeOfPayment = modeOfPayment;
    }

    @Column(name = "cheque_no", length = 60)
    public String getChequeNo() {
        return this.chequeNo;
    }

    public void setChequeNo(String chequeNo) {
        this.chequeNo = chequeNo;
    }

    @Column(name = "bank_name", length = 60)
    public String getBankName() {
        return this.bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    @Column(name = "account_no", length = 60)
    public String getAccountNo() {
        return this.accountNo;
    }

    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dated", length = 19)
    public Date getDated() {
        return this.dated;
    }

    public void setDated(Date dated) {
        this.dated = dated;
    }

    @Column(name = "amount", length = 60)
    public String getAmount() {
        return this.amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    @Column(name = "prepaid_amount", length = 60)
    public String getPrepaidAmount() {
        return prepaidAmount;
    }

    public void setPrepaidAmount(String prepaidAmount) {
        this.prepaidAmount = prepaidAmount;
    }

    @Column(name = "attribute1", length = 60)
    public String getExtra1() {
        return this.extra1;
    }

    public void setExtra1(String extra1) {
        this.extra1 = extra1;
    }

    @Column(name = "attribute2", length = 500)
    public String getExtra2() {
        return this.extra2;
    }

    public void setExtra2(String extra2) {
        this.extra2 = extra2;
    }

    @Column(name = "attribute3", length = 60)
    public String getExtra3() {
        return this.extra3;
    }

    public void setExtra3(String extra3) {
        this.extra3 = extra3;
    }

    @Column(name = "attribute4", length = 60)
    public String getExtra4() {
        return this.extra4;
    }

    public void setExtra4(String extra4) {
        this.extra4 = extra4;
    }

    @Column(name = "attribute5", length = 60)
    public String getExtra5() {
        return this.extra5;
    }

    public void setExtra5(String extra5) {
        this.extra5 = extra5;
    }

    @Column(name = "cheque_status", length = 60)
    public String getChequeStatus() {
        return chequeStatus;
    }

    public void setChequeStatus(String chequeStatus) {
        this.chequeStatus = chequeStatus;
    }

    @Column(name = "status", length = 60)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "creation_date", length = 60)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lastmodified_date", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Column(name = "flat_no", length = 60)
    public String getFlotNo() {
        return flotNo;
    }

    public void setFlotNo(String flotNo) {
        this.flotNo = flotNo;
    }

    @Column(name = "subass_code", length = 60)
    public String getSubassetCode() {
        return subassetCode;
    }

    public void setSubassetCode(String subassetCode) {
        this.subassetCode = subassetCode;
    }

    @Column(name = "other_amt", length = 60)
    public String getOtherAmount() {
        return otherAmount;
    }

    public void setOtherAmount(String otherAmount) {
        this.otherAmount = otherAmount;
    }

    @Column(name = "service_requested_cost", length = 60)
    public String getServiceRequestedCost() {
        return serviceRequestedCost;
    }

    public void setServiceRequestedCost(String serviceRequestedCost) {
        this.serviceRequestedCost = serviceRequestedCost;
    }

    @Column(name = "penalty_type", length = 60)
    public String getPenaltyType() {
        return penaltyType;
    }

    public void setPenaltyType(String penaltyType) {
        this.penaltyType = penaltyType;
    }

    @Column(name = "penalty_amount", length = 60)
    public String getPenaltyamount() {
        return penaltyamount;
    }

    public void setPenaltyamount(String penaltyamount) {
        this.penaltyamount = penaltyamount;
    }

    @Column(name = "invoice_number", length = 60)
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }

    public BillPayment() {
    }

}
