package tenant.classes;
// Generated 28 Sep, 2016 11:04:18 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Campaign generated by hbm2java
 */
@Entity
@Table(name = "campaign", schema = "arete_tms"
)
public class Campaign implements java.io.Serializable {

    private Integer sno;
    private String userId;
    private String orgId;
    private String campaignCode;
    private String campaignName;
    private String campaignMedia;
    private String campaignStatus;
    private String campaignRemarks;
    private Date startDate;
    private Date endDate;
    private String response;
    private String eventOrganiser;
    private String companyName;
    private String companyType;
    private String companyDetails;
    private String emailId;
    private String phoneNo;
    private String remarks;
    private String expectedRevenue;
    private String actualRevenue;
    private String budgetedCost;
    private String actualCost;
    private String roi;
    private String budgeteRemaining;
    private String recordStatus;
    private String attribute1;
    private String attribute2;
    private String attribute3;
    private String attribute4;
    private String attribute5;
    private Date creationDate;
    private String status;
    private Date lastmodefiedDate;

    public Campaign() {
    }

    public Campaign(String userId) {
        this.userId = userId;
    }

    public Campaign(String userId, String orgId, String campaignCode, String campaignName, String campaignMedia, String campaignStatus, String campaignRemarks, Date startDate, Date endDate, String response, String eventOrganiser, String companyName, String companyType, String companyDetails, String emailId, String phoneNo, String remarks, String expectedRevenue, String actualRevenue, String budgetedCost, String actualCost, String roi, String budgeteRemaining, String recordStatus, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, Date creationDate, String status, Date lastmodefiedDate) {
        this.userId = userId;
        this.orgId = orgId;
        this.campaignCode = campaignCode;
        this.campaignName = campaignName;
        this.campaignMedia = campaignMedia;
        this.campaignStatus = campaignStatus;
        this.campaignRemarks = campaignRemarks;
        this.startDate = startDate;
        this.endDate = endDate;
        this.response = response;
        this.eventOrganiser = eventOrganiser;
        this.companyName = companyName;
        this.companyType = companyType;
        this.companyDetails = companyDetails;
        this.emailId = emailId;
        this.phoneNo = phoneNo;
        this.remarks = remarks;
        this.expectedRevenue = expectedRevenue;
        this.actualRevenue = actualRevenue;
        this.budgetedCost = budgetedCost;
        this.actualCost = actualCost;
        this.roi = roi;
        this.budgeteRemaining = budgeteRemaining;
        this.recordStatus = recordStatus;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.creationDate = creationDate;
        this.status = status;
        this.lastmodefiedDate = lastmodefiedDate;
    }

    public Campaign(int sno, String userId, String orgId, String campaignCode, String campaignName, String campaignMedia, String campaignStatus, String campaignRemarks, Date startDate, Date endDate, String response, String eventOrganiser, String companyName, String companyType, String companyDetails, String emailId, String phoneNo, String remarks, String expectedRevenue, String actualRevenue, String budgetedCost, String actualCost, String roi, String budgeteRemaining, String recordStatus, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, Date creationDate, String status, Date lastmodefiedDate) {
        this.sno = sno;
        this.userId = userId;
        this.orgId = orgId;
        this.campaignCode = campaignCode;
        this.campaignName = campaignName;
        this.campaignMedia = campaignMedia;
        this.campaignStatus = campaignStatus;
        this.campaignRemarks = campaignRemarks;
        this.startDate = startDate;
        this.endDate = endDate;
        this.response = response;
        this.eventOrganiser = eventOrganiser;
        this.companyName = companyName;
        this.companyType = companyType;
        this.companyDetails = companyDetails;
        this.emailId = emailId;
        this.phoneNo = phoneNo;
        this.remarks = remarks;
        this.expectedRevenue = expectedRevenue;
        this.actualRevenue = actualRevenue;
        this.budgetedCost = budgetedCost;
        this.actualCost = actualCost;
        this.roi = roi;
        this.budgeteRemaining = budgeteRemaining;
        this.recordStatus = recordStatus;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.creationDate = creationDate;
        this.status = status;
        this.lastmodefiedDate = lastmodefiedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "sno", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "user_Id", nullable = false, length = 20)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "org_Id", length = 20)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "campaign_Code", length = 50)
    public String getCampaignCode() {
        return this.campaignCode;
    }

    public void setCampaignCode(String campaignCode) {
        this.campaignCode = campaignCode;
    }

    @Column(name = "campaign_Name", length = 50)
    public String getCampaignName() {
        return this.campaignName;
    }

    public void setCampaignName(String campaignName) {
        this.campaignName = campaignName;
    }

    @Column(name = "campaign_Media", length = 50)
    public String getCampaignMedia() {
        return this.campaignMedia;
    }

    public void setCampaignMedia(String campaignMedia) {
        this.campaignMedia = campaignMedia;
    }

    @Column(name = "campaign_Status", length = 50)
    public String getCampaignStatus() {
        return this.campaignStatus;
    }

    public void setCampaignStatus(String campaignStatus) {
        this.campaignStatus = campaignStatus;
    }

    @Column(name = "Campaign_Remarks", length = 500)
    public String getCampaignRemarks() {
        return this.campaignRemarks;
    }

    public void setCampaignRemarks(String campaignRemarks) {
        this.campaignRemarks = campaignRemarks;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Start_Date", length = 19)
    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "End_Date", length = 19)
    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @Column(name = "Response", length = 50)
    public String getResponse() {
        return this.response;
    }

    public void setResponse(String response) {
        this.response = response;
    }

    @Column(name = "Event_Organiser", length = 50)
    public String getEventOrganiser() {
        return this.eventOrganiser;
    }

    public void setEventOrganiser(String eventOrganiser) {
        this.eventOrganiser = eventOrganiser;
    }

    @Column(name = "Company_Name", length = 50)
    public String getCompanyName() {
        return this.companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    @Column(name = "Company_Type", length = 50)
    public String getCompanyType() {
        return this.companyType;
    }

    public void setCompanyType(String companyType) {
        this.companyType = companyType;
    }

    @Column(name = "Company_Details", length = 50)
    public String getCompanyDetails() {
        return this.companyDetails;
    }

    public void setCompanyDetails(String companyDetails) {
        this.companyDetails = companyDetails;
    }

    @Column(name = "EmailId", length = 50)
    public String getEmailId() {
        return this.emailId;
    }

    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    @Column(name = "Phone_No", length = 50)
    public String getPhoneNo() {
        return this.phoneNo;
    }

    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    @Column(name = "Remarks", length = 500)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "Expected_Revenue", length = 50)
    public String getExpectedRevenue() {
        return this.expectedRevenue;
    }

    public void setExpectedRevenue(String expectedRevenue) {
        this.expectedRevenue = expectedRevenue;
    }

    @Column(name = "Actual_Revenue", length = 50)
    public String getActualRevenue() {
        return this.actualRevenue;
    }

    public void setActualRevenue(String actualRevenue) {
        this.actualRevenue = actualRevenue;
    }

    @Column(name = "Budgeted_Cost", length = 50)
    public String getBudgetedCost() {
        return this.budgetedCost;
    }

    public void setBudgetedCost(String budgetedCost) {
        this.budgetedCost = budgetedCost;
    }

    @Column(name = "Actual_Cost", length = 50)
    public String getActualCost() {
        return this.actualCost;
    }

    public void setActualCost(String actualCost) {
        this.actualCost = actualCost;
    }

    @Column(name = "ROI", length = 50)
    public String getRoi() {
        return this.roi;
    }

    public void setRoi(String roi) {
        this.roi = roi;
    }

    @Column(name = "Budgete_Remaining", length = 50)
    public String getBudgeteRemaining() {
        return this.budgeteRemaining;
    }

    public void setBudgeteRemaining(String budgeteRemaining) {
        this.budgeteRemaining = budgeteRemaining;
    }

    @Column(name = "Record_Status", length = 50)
    public String getRecordStatus() {
        return this.recordStatus;
    }

    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    @Column(name = "Attribute1", length = 50)
    public String getAttribute1() {
        return this.attribute1;
    }

    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    @Column(name = "Attribute2", length = 50)
    public String getAttribute2() {
        return this.attribute2;
    }

    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    @Column(name = "Attribute3", length = 50)
    public String getAttribute3() {
        return this.attribute3;
    }

    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    @Column(name = "Attribute4", length = 500)
    public String getAttribute4() {
        return this.attribute4;
    }

    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    @Column(name = "Attribute5", length = 500)
    public String getAttribute5() {
        return this.attribute5;
    }

    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Creation_date", length = 19)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Column(name = "Status", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Lastmodefied_Date", length = 19)
    public Date getLastmodefiedDate() {
        return this.lastmodefiedDate;
    }

    public void setLastmodefiedDate(Date lastmodefiedDate) {
        this.lastmodefiedDate = lastmodefiedDate;
    }

}
