package tenant.classes;
// Generated 28 Sep, 2016 11:57:28 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Complaints generated by hbm2java
 */
@Entity
@Table(name = "complaints", schema = "arete_tms"
)
public class Complaints implements java.io.Serializable {

    private Integer sno;
    private String userId;
    private String orgId;
    private String complaintCode;
    private String tenantName;
    private String assetName;
    private String assetNo;
    private Date date;
    private String remarks;
    private String compensationExpected;
    private String recordStatus;
    private String attribute1;
    private String attribute2;
    private String attribute3;
    private String attribute4;
    private String attribute5;
    private Date creationDate;
    private String status;
    private Date lastmodefiedDate;
    private String complaintType;

    public Complaints() {
    }

    public Complaints(String userId) {
        this.userId = userId;
    }

    public Complaints(String userId, String orgId, String complaintCode, String tenantName, String assetName, String assetNo, Date date, String remarks, String compensationExpected, String recordStatus, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, Date creationDate, String status, Date lastmodefiedDate, String complaintType) {
        this.userId = userId;
        this.orgId = orgId;
        this.complaintCode = complaintCode;
        this.tenantName = tenantName;
        this.assetName = assetName;
        this.assetNo = assetNo;
        this.date = date;
        this.remarks = remarks;
        this.compensationExpected = compensationExpected;
        this.recordStatus = recordStatus;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.creationDate = creationDate;
        this.status = status;
        this.lastmodefiedDate = lastmodefiedDate;
        this.complaintType = complaintType;
    }

    public Complaints(Integer sno, String userId, String orgId, String complaintCode, String tenantName, String assetName, String assetNo, Date date, String remarks, String compensationExpected, String recordStatus, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, Date creationDate, String status, Date lastmodefiedDate, String complaintType) {
        this.sno = sno;
        this.userId = userId;
        this.orgId = orgId;
        this.complaintCode = complaintCode;
        this.tenantName = tenantName;
        this.assetName = assetName;
        this.assetNo = assetNo;
        this.date = date;
        this.remarks = remarks;
        this.compensationExpected = compensationExpected;
        this.recordStatus = recordStatus;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.creationDate = creationDate;
        this.status = status;
        this.lastmodefiedDate = lastmodefiedDate;
        this.complaintType = complaintType;
    }

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "sno", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "user_Id", nullable = false, length = 20)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "org_Id", length = 20)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "Complaint_Code", length = 50)
    public String getComplaintCode() {
        return this.complaintCode;
    }

    public void setComplaintCode(String complaintCode) {
        this.complaintCode = complaintCode;
    }

    @Column(name = "Tenant_Name", length = 50)
    public String getTenantName() {
        return this.tenantName;
    }

    public void setTenantName(String tenantName) {
        this.tenantName = tenantName;
    }

    @Column(name = "Asset_Name", length = 50)
    public String getAssetName() {
        return this.assetName;
    }

    public void setAssetName(String assetName) {
        this.assetName = assetName;
    }

    @Column(name = "Asset_No", length = 50)
    public String getAssetNo() {
        return this.assetNo;
    }

    public void setAssetNo(String assetNo) {
        this.assetNo = assetNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Date", length = 19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "Remarks", length = 500)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "Compensation_Expected", length = 500)
    public String getCompensationExpected() {
        return this.compensationExpected;
    }

    public void setCompensationExpected(String compensationExpected) {
        this.compensationExpected = compensationExpected;
    }

    @Column(name = "Record_Status", length = 50)
    public String getRecordStatus() {
        return this.recordStatus;
    }

    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    @Column(name = "Attribute1", length = 500)
    public String getAttribute1() {
        return this.attribute1;
    }

    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    @Column(name = "Attribute2", length = 50)
    public String getAttribute2() {
        return this.attribute2;
    }

    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    @Column(name = "Attribute3", length = 500)
    public String getAttribute3() {
        return this.attribute3;
    }

    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    @Column(name = "Attribute4", length = 500)
    public String getAttribute4() {
        return this.attribute4;
    }

    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    @Column(name = "Attribute5", length = 500)
    public String getAttribute5() {
        return this.attribute5;
    }

    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Creation_date", length = 19)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Column(name = "Status", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Lastmodefied_Date", length = 19)
    public Date getLastmodefiedDate() {
        return this.lastmodefiedDate;
    }

    public void setLastmodefiedDate(Date lastmodefiedDate) {
        this.lastmodefiedDate = lastmodefiedDate;
    }

    @Column(name = "complaint_type", length = 50)
    public String getComplaintType() {
        return complaintType;
    }

    public void setComplaintType(String complaintType) {
        this.complaintType = complaintType;
    }
    
    

}
