package tenant.classes;
// Generated 22 Sep, 2016 10:06:28 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ContractCreation generated by hbm2java
 */
@Entity
@Table(name = "contract_creation", schema = "arete_tms", uniqueConstraints = @UniqueConstraint(columnNames = "SNO")
) 
public class ContractCreation implements java.io.Serializable {

    private String contractCode;
    private int sno;
    private String orgId;
    private String userId;
    private String contractTitle;
    private String contractCategoryId;
    private Date contStartDate;
    private Date contEndDate;
    private Date contReviewDate;
    private String contStatus;
    private String classificationId;
    private String remarks;
    private String contractTerm;
    private String recordStatus;
    private String approvar2Remark;
    private String approvar3Remark;
    private String rejectorRemark;
    private String onHoldRemark;
    private String propertyCod;
    private String flatCod;
    private String attribute4;
    private String attribute5;
    private String status;
    private Date creationDate;
    private Date lastmodifiedDate;
    private String insuranceTaggedId;

    public ContractCreation() {
    }

    public ContractCreation(int sno, String contractCategoryId, String classificationId) {
        this.sno = sno;
        this.contractCategoryId = contractCategoryId;
        this.classificationId = classificationId;
    }

    public ContractCreation(int sno, String orgId, String userId, String contractTitle, String contractCategoryId, Date contStartDate, Date contEndDate, Date contReviewDate, String contStatus, String classificationId, String contractCode, String remarks, String contractTerm, String propertyCod, String flatCod, String attribute4, String attribute5, String status, String recordStatus, Date lastmodifiedDate) {
        this.sno = sno;
        this.orgId = orgId;
        this.userId = userId;
        this.contractTitle = contractTitle;
        this.contractCategoryId = contractCategoryId;
        this.contStartDate = contStartDate;
        this.contEndDate = contEndDate;
        this.contReviewDate = contReviewDate;
        this.contStatus = contStatus;
        this.classificationId = classificationId;
        this.contractCode = contractCode;
        this.remarks = remarks;
        this.contractTerm = contractTerm;
        this.propertyCod = propertyCod;
        this.flatCod = flatCod;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.status = status;
        this.recordStatus = recordStatus;

        this.lastmodifiedDate = lastmodifiedDate;

    }

    public ContractCreation(String contractCode, int sno, String orgId, String userId, String contractTitle, String contractCategoryId, Date contStartDate, Date contEndDate, Date contReviewDate, String contStatus, String classificationId, String remarks, String contractTerm, String propertyCod, String flatCod, String attribute4, String attribute5, String status, Date lastmodifiedDate, String insuranceTaggedId) {
        this.contractCode = contractCode;
        this.sno = sno;
        this.orgId = orgId;
        this.userId = userId;
        this.contractTitle = contractTitle;
        this.contractCategoryId = contractCategoryId;
        this.contStartDate = contStartDate;
        this.contEndDate = contEndDate;
        this.contReviewDate = contReviewDate;
        this.contStatus = contStatus;
        this.classificationId = classificationId;

        this.remarks = remarks;
        this.contractTerm = contractTerm;
        this.propertyCod = propertyCod;
        this.flatCod = flatCod;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;

    }

    public ContractCreation(String contractCode, String orgId, String userId, String contractTitle, String contractCategoryId, Date contStartDate, Date contEndDate, Date contReviewDate, String contStatus, String classificationId, String remarks, String contractTerm, String propertyCod, String flatCod, String attribute4, String attribute5, String status, String recordStatus, Date creationDate, Date lastmodifiedDate) {
        this.contractCode = contractCode;
        this.orgId = orgId;
        this.userId = userId;
        this.contractTitle = contractTitle;
        this.contractCategoryId = contractCategoryId;
        this.contStartDate = contStartDate;
        this.contEndDate = contEndDate;
        this.contReviewDate = contReviewDate;
        this.contStatus = contStatus;
        this.classificationId = classificationId;
        this.remarks = remarks;
        this.contractTerm = contractTerm;
        this.propertyCod = propertyCod;
        this.flatCod = flatCod;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.status = status;
        this.recordStatus = recordStatus;
        this.creationDate = creationDate;
        this.lastmodifiedDate = lastmodifiedDate;

    }

    @Column(name = "CONTRACT_CODE", length = 20)
    public String getContractCode() {
        return this.contractCode;
    }

    public void setContractCode(String contractCode) {
        this.contractCode = contractCode;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "SNO", unique = true, nullable = false)
    public int getSno() {
        return this.sno;
    }

    public void setSno(int sno) {
        this.sno = sno;
    }

    @Column(name = "ORG_ID", length = 50)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "USER_ID", length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "CONTRACT_TITLE", length = 100)
    public String getContractTitle() {
        return this.contractTitle;
    }

    public void setContractTitle(String contractTitle) {
        this.contractTitle = contractTitle;
    }

    @Column(name = "CONTRACT_CATEGORY_ID", nullable = false, length = 20)
    public String getContractCategoryId() {
        return this.contractCategoryId;
    }

    public void setContractCategoryId(String contractCategoryId) {
        this.contractCategoryId = contractCategoryId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CONT_START_DATE", length = 10)
    public Date getContStartDate() {
        return this.contStartDate;
    }

    public void setContStartDate(Date contStartDate) {
        this.contStartDate = contStartDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CONT_END_DATE", length = 10)
    public Date getContEndDate() {
        return this.contEndDate;
    }

    public void setContEndDate(Date contEndDate) {
        this.contEndDate = contEndDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CONT_REVIEW_DATE", length = 10)
    public Date getContReviewDate() {
        return this.contReviewDate;
    }

    public void setContReviewDate(Date contReviewDate) {
        this.contReviewDate = contReviewDate;
    }

    @Column(name = "CONT_STATUS", length = 50)
    public String getContStatus() {
        return this.contStatus;
    }

    public void setContStatus(String contStatus) {
        this.contStatus = contStatus;
    }

    @Column(name = "CLASSIFICATION_ID", nullable = false, length = 20)
    public String getClassificationId() {
        return this.classificationId;
    }

    public void setClassificationId(String classificationId) {
        this.classificationId = classificationId;
    }

    @Column(name = "REMARKS", length = 500)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "CONTRACT_TERM")
    public String getContractTerm() {
        return this.contractTerm;
    }

    public void setContractTerm(String contractTerm) {
        this.contractTerm = contractTerm;
    }

    @Column(name = "RECORD_STATUS", length = 50)
    public String getRecordStatus() {
        return this.recordStatus;
    }

    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    @Column(name = "APPROVER2_REMARK")
    public String getApprovar2Remark() {
        return approvar2Remark;
    }

    public void setApprovar2Remark(String approvar2Remark) {
        this.approvar2Remark = approvar2Remark;
    }

    @Column(name = "APPROVER3_REMARK")
    public String getApprovar3Remark() {
        return approvar3Remark;
    }

    public void setApprovar3Remark(String approvar3Remark) {
        this.approvar3Remark = approvar3Remark;
    }

    @Column(name = "REJECTOR_REMARK", length = 300)
    public String getRejectorRemark() {
        return this.rejectorRemark;
    }

    public void setRejectorRemark(String rejectorRemark) {
        this.rejectorRemark = rejectorRemark;
    }

    @Column(name = "ONHOLD_REMARK", length = 300)
    public String getOnHoldRemark() {
        return onHoldRemark;
    }

    public void setOnHoldRemark(String onHoldRemark) {
        this.onHoldRemark = onHoldRemark;
    }

    @Column(name = "PROPERTY_CODE", length = 60)
    public String getPropertyCod() {
        return this.propertyCod;
    }

    public void setPropertyCod(String propertyCod) {
        this.propertyCod = propertyCod;
    }

    @Column(name = "FLAT_CODE", length = 60)
    public String getFlatCod() {
        return this.flatCod;
    }

    public void setFlatCod(String flatCod) {
        this.flatCod = flatCod;
    }

    @Column(name = "ATTRIBUTE4", length = 500)
    public String getAttribute4() {
        return this.attribute4;
    }

    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    @Column(name = "ATTRIBUTE5", length = 500)
    public String getAttribute5() {
        return this.attribute5;
    }

    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATION_DATE", length = 19)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTMODIFIED_DATE", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Column(name = "INSURANCE_TAGGED_ID", length = 70)
    public String getInsuranceTaggedId() {
        return this.insuranceTaggedId;
    }

    public void setInsuranceTaggedId(String insuranceTaggedId) {
        this.insuranceTaggedId = insuranceTaggedId;
    }

}
