/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tenant.classes;

// Generated Oct 18, 2016 3:50:25 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CostCenterMst generated by hbm2java
 */
@Entity
@Table(name = "cost_center_mst", schema = "arete_tms"
)
public class CostCenterMst implements java.io.Serializable {

    private long SNo;
    private String costcenterCode;
    private String costcenterDesc;
    private String status;
    private String createdBy;
    private Date createdDate;
    private java.sql.Timestamp lastModifiedDate;

    public CostCenterMst() {
    }

    public CostCenterMst(long SNo) {
        this.SNo = SNo;
    }

    public CostCenterMst(long SNo, String costcenterCode, String costcenterDesc, String status, String createdBy, Date createdDate, java.sql.Timestamp lastModifiedDate) {
        this.SNo = SNo;
        this.costcenterCode = costcenterCode;
        this.costcenterDesc = costcenterDesc;
        this.status = status;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastModifiedDate = lastModifiedDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "costcenter_id_seq")
    @SequenceGenerator(name = "costcenter_id_seq", sequenceName = "costcenter_seq", allocationSize = 1)

    @Column(name = "s_no", unique = true, nullable = false, precision = 10, scale = 0)
    public long getSNo() {
        return this.SNo;
    }

    public void setSNo(long SNo) {
        this.SNo = SNo;
    }

    @Column(name = "costcenter_code", length = 20)
    public String getCostcenterCode() {
        return this.costcenterCode;
    }

    public void setCostcenterCode(String costcenterCode) {
        this.costcenterCode = costcenterCode;
    }

    @Column(name = "costcenter_desc", length = 250)
    public String getCostcenterDesc() {
        return this.costcenterDesc;
    }

    public void setCostcenterDesc(String costcenterDesc) {
        this.costcenterDesc = costcenterDesc;
    }

    @Column(name = "status", length = 20)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "created_by", length = 50)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "created_date", length = 7)
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "last_modified_date")
    public java.sql.Timestamp getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    public void setLastModifiedDate(java.sql.Timestamp lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

}

