/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tenant.classes;
// Generated Apr 2, 2016 11:48:04 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DeliveryLocation generated by hbm2java
 */
@Entity
@Table(name="delivery_location"
    ,schema = "arete_tms"
)
public class DeliveryLocation  implements java.io.Serializable {


     private Integer sno;
     private String userId;
     private String orgId;
     private String divisionName;
     private String address;
     private BigDecimal contactNo;
     private String emailId;
     private String status;
     private Timestamp lastmodifiedDate;

    public DeliveryLocation() {
    }

	
    public DeliveryLocation(String userId, String orgId, String divisionName, String address, BigDecimal contactNo, String emailId, String status, Timestamp lastmodifiedDate) {
       this.userId = userId;
       this.orgId = orgId;
       this.divisionName = divisionName;
       this.address = address;
       this.contactNo = contactNo;
       this.emailId = emailId;
       this.status = status;
       this.lastmodifiedDate = lastmodifiedDate;
    }
    public DeliveryLocation(Integer sno, String userId, String orgId, String divisionName, String address, BigDecimal contactNo, String emailId, String status, Timestamp lastmodifiedDate) {
       this.sno = sno;
       this.userId = userId;
       this.orgId = orgId;
       this.divisionName = divisionName;
       this.address = address;
       this.contactNo = contactNo;
       this.emailId = emailId;
       this.status = status;
       this.lastmodifiedDate = lastmodifiedDate;
    }
   
     @Id 
     @SequenceGenerator(name = "table_seq", sequenceName = "deliverylocation_sequence",allocationSize=1)
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "table_seq")
    
    @Column(name="s_no", unique=true, nullable=false, precision=22, scale=0)
    public Integer getSno() {
        return this.sno;
    }
    
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    
    @Column(name="user_id", nullable=false, length=50)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="org_id", nullable=false, length=50)
    public String getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    
    @Column(name="division_name", nullable=false, length=100)
    public String getDivisionName() {
        return this.divisionName;
    }
    
    public void setDivisionName(String divisionName) {
        this.divisionName = divisionName;
    }

    
    @Column(name="address", nullable=false, length=200)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="contact_no", precision=22, scale=0)
    public BigDecimal getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(BigDecimal contactNo) {
        this.contactNo = contactNo;
    }

    
    @Column(name="email_id", length=100)
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    
    @Column(name="status", nullable=false, length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="lastmodified_date", nullable=false)
    public Timestamp getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }
    
    public void setLastmodifiedDate(Timestamp lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }




}



