package tenant.classes;
// Generated 30 May, 2016 12:22:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DepartmentModule generated by hbm2java
 */
@Entity
@Table(name = "department_module", schema = "arete_tms"
)
public class DepartmentModule implements java.io.Serializable {

    private Integer sno;
    private String departmentCode;
    private String tabName;
    private String listLink;
    private String formLink;
    private String status;
    private Date lastmodifiedDate;
    private String moduleName;
    private String submoduleName;
    private String orgCode;

    public DepartmentModule() {
    }

    public DepartmentModule(String departmentCode, String orgCode, String moduleName, String submoduleName, String tabName,
            String listLink, String formLink, String status, java.sql.Timestamp lastmodifiedDate) {
        this.departmentCode = departmentCode;
        this.orgCode = orgCode;
        this.moduleName = moduleName;
        this.submoduleName = submoduleName;
        this.tabName = tabName;
        this.listLink = listLink;
        this.formLink = formLink;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    public DepartmentModule(Integer sno, String departmentCode, String tabName, String listLink, String formLink, String status, java.sql.Timestamp lastmodifiedDate) {
        this.sno = sno;
        this.departmentCode = departmentCode;
        this.tabName = tabName;
        this.listLink = listLink;
        this.formLink = formLink;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "SNO", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "DEPARTMENT_CODE", length = 50)
    public String getDepartmentCode() {
        return this.departmentCode;
    }

    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode;
    }

    @Column(name = "TAB_NAME", length = 50)
    public String getTabName() {
        return this.tabName;
    }

    public void setTabName(String tabName) {
        this.tabName = tabName;
    }

    @Column(name = "LIST_LINK", length = 100)
    public String getListLink() {
        return this.listLink;
    }

    public void setListLink(String listLink) {
        this.listLink = listLink;
    }

    @Column(name = "FORM_LINK", length = 100)
    public String getFormLink() {
        return this.formLink;
    }

    public void setFormLink(String formLink) {
        this.formLink = formLink;
    }

    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTMODIFIED_DATE", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Column(name = "MODULE_NAME", length = 50)
    public String getModuleName() {
        return this.moduleName;
    }

    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    @Column(name = "SUBMODULE_NAME", length = 50)
    public String getSubmoduleName() {
        return this.submoduleName;
    }

    public void setSubmoduleName(String submoduleName) {
        this.submoduleName = submoduleName;
    }

    @Column(name = "ORG_CODE", length = 50)
    public String getOrgCode() {
        return this.orgCode;
    }

    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

}
