package tenant.classes;
// Generated 30 May, 2016 12:22:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DepartmentRole generated by hbm2java
 */
@Entity
@Table(name = "department_role", schema = "arete_tms"
)
public class DepartmentRole implements java.io.Serializable {

    private Integer sno;
    private String roleCode;
    private String roleName;
    private String roleDesc;
    private String departmentCode;
    private String status;
    private Date lastmodifiedDate;

    public DepartmentRole() {
    }

    public DepartmentRole(String roleCode, String roleName, String roleDesc, String departmentCode, String status, java.sql.Timestamp lastmodifiedDate) {
        this.roleCode = roleCode;
        this.roleName = roleName;
        this.roleDesc = roleDesc;
        this.departmentCode = departmentCode;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    public DepartmentRole(Integer sno, String roleCode, String roleName, String roleDesc, String departmentCode, String status, java.sql.Timestamp lastmodifiedDate) {
        this.sno = sno;
        this.roleCode = roleCode;
        this.roleName = roleName;
        this.roleDesc = roleDesc;
        this.departmentCode = departmentCode;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "SNO", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "ROLE_CODE", length = 50)
    public String getRoleCode() {
        return this.roleCode;
    }

    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    @Column(name = "ROLE_NAME", length = 50)
    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @Column(name = "ROLE_DESC", length = 100)
    public String getRoleDesc() {
        return this.roleDesc;
    }

    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }

    @Column(name = "DEPARTMENT_CODE", length = 50)
    public String getDepartmentCode() {
        return this.departmentCode;
    }

    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode;
    }

    @Column(name = "STATUS", length = 20)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTMODIFIED_DATE", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

}
