package tenant.classes;
// Generated 13 Oct, 2016 5:14:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DepreciationRecords generated by hbm2java
 */
@Entity
@Table(name = "depreciation_records", schema = "arete_tms"
)
public class DepreciationRecords implements java.io.Serializable {

    private Integer SNo;
    private String depreCode;
    private String assetType;
    private String assetName;
    private String assetValue;
    private Date depreciationStartDate;
    private String status;
    private Date createdDate;
    private Date lastModifiedDate;
    private String subAssetCode;
    private String subAssetName;
    private String accessoriesCode;
    private String accessoriesName;
    private String assetCode;
    private String period;
    private String NBV;
    private String cumulativeAmount;
    private String depreciationAmount;
    private String purchaseVoucherNo;
    private Date purchaseDate;
    private Date depreciationEndDate;
    private Date dipreciationFirstDate;
    private String depreciationPercent;
    private String poNo;
    private String noOfDays;

    public DepreciationRecords() {
    }

    public DepreciationRecords(Integer SNo, String depreCode, String assetType, String assetName, String assetValue, Date depreciationStartDate, String status, Date createdDate, Date lastModifiedDate, String subAssetCode, String subAssetName, String accessoriesCode, String accessoriesName, String assetCode, String period, String NBV, String cumulativeAmount, String depreciationAmount, String purchaseVoucherNo, Date purchaseDate, Date depreciationEndDate, Date dipreciationFirstDate, String depreciationPercent, String poNo, String noOfDays) {
        this.SNo = SNo;
        this.depreCode = depreCode;
        this.assetType = assetType;
        this.assetName = assetName;
        this.assetValue = assetValue;
        this.depreciationStartDate = depreciationStartDate;
        this.status = status;
        this.createdDate = createdDate;
        this.lastModifiedDate = lastModifiedDate;
        this.subAssetCode = subAssetCode;
        this.subAssetName = subAssetName;
        this.accessoriesCode = accessoriesCode;
        this.accessoriesName = accessoriesName;
        this.assetCode = assetCode;
        this.period = period;
        this.NBV = NBV;
        this.cumulativeAmount = cumulativeAmount;
        this.depreciationAmount = depreciationAmount;
        this.purchaseVoucherNo = purchaseVoucherNo;
        this.purchaseDate = purchaseDate;
        this.depreciationEndDate = depreciationEndDate;
        this.dipreciationFirstDate = dipreciationFirstDate;
        this.depreciationPercent = depreciationPercent;
        this.poNo = poNo;
        this.noOfDays = noOfDays;
    }

    public DepreciationRecords(String depreCode, String assetType, String assetName, String assetValue, Date depreciationStartDate, String status, Date createdDate, Date lastModifiedDate, String subAssetCode, String subAssetName, String accessoriesCode, String accessoriesName, String assetCode, String period, String NBV, String cumulativeAmount, String depreciationAmount, String purchaseVoucherNo, Date purchaseDate, Date depreciationEndDate, Date dipreciationFirstDate, String depreciationPercent, String poNo, String noOfDays) {
        this.depreCode = depreCode;
        this.assetType = assetType;
        this.assetName = assetName;
        this.assetValue = assetValue;
        this.depreciationStartDate = depreciationStartDate;
        this.status = status;
        this.createdDate = createdDate;
        this.lastModifiedDate = lastModifiedDate;
        this.subAssetCode = subAssetCode;
        this.subAssetName = subAssetName;
        this.accessoriesCode = accessoriesCode;
        this.accessoriesName = accessoriesName;
        this.assetCode = assetCode;
        this.period = period;
        this.NBV = NBV;
        this.cumulativeAmount = cumulativeAmount;
        this.depreciationAmount = depreciationAmount;
        this.purchaseVoucherNo = purchaseVoucherNo;
        this.purchaseDate = purchaseDate;
        this.depreciationEndDate = depreciationEndDate;
        this.dipreciationFirstDate = dipreciationFirstDate;
        this.depreciationPercent = depreciationPercent;
        this.poNo = poNo;
        this.noOfDays = noOfDays;

    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "s_no", unique = true, nullable = false)
    public Integer getSNo() {
        return this.SNo;
    }

    public Date getDepreciationStartDate() {
        return depreciationStartDate;
    }

    public void setDepreciationStartDate(Date depreciationStartDate) {
        this.depreciationStartDate = depreciationStartDate;
    }

    public String getPoNo() {
        return poNo;
    }

    public void setPoNo(String poNo) {
        this.poNo = poNo;
    }

    public String getNoOfDays() {
        return noOfDays;
    }

    public void setNoOfDays(String noOfDays) {
        this.noOfDays = noOfDays;
    }

    public String getPeriod() {
        return period;
    }

    public void setPeriod(String period) {
        this.period = period;
    }

    public String getDepreciationPercent() {
        return depreciationPercent;
    }

    public Date getDipreciationFirstDate() {
        return dipreciationFirstDate;
    }

    public void setDipreciationFirstDate(Date dipreciationFirstDate) {
        this.dipreciationFirstDate = dipreciationFirstDate;
    }

    public void setDepreciationPercent(String depreciationPercent) {
        this.depreciationPercent = depreciationPercent;
    }

    public String getNBV() {
        return NBV;
    }

    public void setNBV(String NBV) {
        this.NBV = NBV;
    }

    public String getCumulativeAmount() {
        return cumulativeAmount;
    }

    public void setCumulativeAmount(String cumulativeAmount) {
        this.cumulativeAmount = cumulativeAmount;
    }

    public String getDepreciationAmount() {
        return depreciationAmount;
    }

    public void setDepreciationAmount(String depreciationAmount) {
        this.depreciationAmount = depreciationAmount;
    }

    public String getPurchaseVoucherNo() {
        return purchaseVoucherNo;
    }

    public void setPurchaseVoucherNo(String purchaseVoucherNo) {
        this.purchaseVoucherNo = purchaseVoucherNo;
    }

    public Date getPurchaseDate() {
        return purchaseDate;
    }

    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    public Date getDepreciationEndDate() {
        return depreciationEndDate;
    }

    public void setDepreciationEndDate(Date depreciationEndDate) {
        this.depreciationEndDate = depreciationEndDate;
    }

    public void setSNo(Integer SNo) {
        this.SNo = SNo;
    }

    @Column(name = "asset_type", length = 45)
    public String getAssetType() {
        return assetType;
    }

    public void setAssetType(String assetType) {
        this.assetType = assetType;
    }

    @Column(name = "depreciation_code", length = 60)
    public String getDepreCode() {
        return this.depreCode;
    }

    public void setDepreCode(String depreCode) {
        this.depreCode = depreCode;
    }

    @Column(name = "asset_code", length = 60)
    public String getAssetCode() {
        return assetCode;
    }

    public void setAssetCode(String assetCode) {
        this.assetCode = assetCode;
    }

    @Column(name = "asset_name", length = 60)
    public String getAssetName() {
        return this.assetName;
    }

    public void setAssetName(String assetName) {
        this.assetName = assetName;
    }

    @Column(name = "asset_value", length = 60)
    public String getAssetValue() {
        return this.assetValue;
    }

    public void setAssetValue(String assetValue) {
        this.assetValue = assetValue;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "createdDate", length = 10)
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "lastModifiedDate", length = 10)
    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    @Column(name = "status", length = 45)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "sub_asset_code", length = 60)
    public String getSubAssetCode() {
        return subAssetCode;
    }

    public void setSubAssetCode(String subAssetCode) {
        this.subAssetCode = subAssetCode;
    }

    @Column(name = "accessories_code", length = 60)
    public String getAccessoriesCode() {
        return accessoriesCode;
    }

    public void setAccessoriesCode(String accessoriesCode) {
        this.accessoriesCode = accessoriesCode;
    }

    @Column(name = "sub_asset_name", length = 60)
    public String getSubAssetName() {
        return subAssetName;
    }

    public void setSubAssetName(String subAssetName) {
        this.subAssetName = subAssetName;
    }

    @Column(name = "accessories_name", length = 60)
    public String getAccessoriesName() {
        return accessoriesName;
    }

    public void setAccessoriesName(String accessoriesName) {
        this.accessoriesName = accessoriesName;
    }

}
