package tenant.classes;
// Generated 21 Oct, 2016 11:09:42 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FinalQuotation generated by hbm2java
 */
@Entity
@Table(name = "final_quotation", schema = "arete_tms"
)
public class FinalQuotation implements java.io.Serializable {

    private Integer sno;
    private String orgId;
    private String userId;
    private String quotationNo;
    private Date quotationDate;
    private String vendorCode;
    private Date quotCreatDate;
    private String itemCategory;
    private String itemCode;
    private String itemUOM;
    private Double qty;
    private Double price;
    private String discount;
    private Double total;
    private String priority;
    private Date creationDate;
    private String attribute1;
    private String attribute2;
    private String attribute3;
    private String attribute4;
    private String attribute5;
    private String status;
    private Date lastmodifiedDate;

    public FinalQuotation() {
    }

    public FinalQuotation(String quotationNo) {
        this.quotationNo = quotationNo;
    }

    public FinalQuotation(String orgId, String userId, String quotationNo, Date quotationDate, String vendorCode, Date quotCreatDate, String itemCode, Double qty, Double price, String discount, Double total, String priority, Date creationDate, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, String status, Date lastmodifiedDate) {
        this.orgId = orgId;
        this.userId = userId;
        this.quotationNo = quotationNo;
        this.quotationDate = quotationDate;
        this.vendorCode = vendorCode;
        this.quotCreatDate = quotCreatDate;
        this.itemCode = itemCode;
        this.qty = qty;
        this.price = price;
        this.discount = discount;
        this.total = total;
        this.priority = priority;
        this.creationDate = creationDate;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    public FinalQuotation(Integer sno, String orgId, String userId, String quotationNo, Date quotationDate, String vendorCode, String itemCategory, String itemCode, String itemUOM, Double qty, Double price, String discount, Double total, String priority, String status, Date lastmodifiedDate) {
        this.sno = sno;
        this.orgId = orgId;
        this.userId = userId;
        this.quotationNo = quotationNo;
        this.quotationDate = quotationDate;
        this.vendorCode = vendorCode;
        this.itemCategory = itemCategory;
        this.itemCode = itemCode;
        this.itemUOM = itemUOM;
        this.qty = qty;
        this.price = price;
        this.discount = discount;
        this.total = total;
        this.priority = priority;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    public FinalQuotation(String orgId, String userId, String quotationNo, Date quotationDate, String vendorCode, String itemCategory, String itemCode, String itemUOM, Double qty, Double price, String discount, Double total, String priority, Date creationDate, String status, Date lastmodifiedDate) {
        this.orgId = orgId;
        this.userId = userId;
        this.quotationNo = quotationNo;
        this.quotationDate = quotationDate;
        this.vendorCode = vendorCode;
        this.itemCategory = itemCategory;
        this.itemCode = itemCode;
        this.itemUOM = itemUOM;
        this.qty = qty;
        this.price = price;
        this.discount = discount;
        this.total = total;
        this.priority = priority;
        this.creationDate = creationDate;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "SNO", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "ORG_ID", length = 50)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "USER_ID", length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "QUOTATION_NO", nullable = false, length = 60)
    public String getQuotationNo() {
        return this.quotationNo;
    }

    public void setQuotationNo(String quotationNo) {
        this.quotationNo = quotationNo;
    }

    @Column(name = "QUOTATION_DATE", length = 50)
    public Date getQuotationDate() {
        return quotationDate;
    }

    public void setQuotationDate(Date quotationDate) {
        this.quotationDate = quotationDate;
    }

    @Column(name = "VENDOR_CODE", length = 60)
    public String getVendorCode() {
        return this.vendorCode;
    }

    public void setVendorCode(String vendorCode) {
        this.vendorCode = vendorCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "QUOT_CREAT_DATE", length = 19)
    public Date getQuotCreatDate() {
        return this.quotCreatDate;
    }

    public void setQuotCreatDate(Date quotCreatDate) {
        this.quotCreatDate = quotCreatDate;
    }

    @Column(name = "ITEM_CODE", length = 60)
    public String getItemCode() {
        return this.itemCode;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    @Column(name = "QTY", precision = 22, scale = 0)
    public Double getQty() {
        return this.qty;
    }

    public void setQty(Double qty) {
        this.qty = qty;
    }

    @Column(name = "PRICE", precision = 22, scale = 0)
    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    @Column(name = "DISCOUNT", length = 60)
    public String getDiscount() {
        return this.discount;
    }

    public void setDiscount(String discount) {
        this.discount = discount;
    }

    @Column(name = "TOTAL", precision = 22, scale = 0)
    public Double getTotal() {
        return this.total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    @Column(name = "PRIORITY", length = 60)
    public String getPriority() {
        return this.priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CREATION_DATE", length = 10)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Column(name = "ATTRIBUTE1")
    public String getAttribute1() {
        return this.attribute1;
    }

    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    @Column(name = "ATTRIBUTE2")
    public String getAttribute2() {
        return this.attribute2;
    }

    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    @Column(name = "ATTRIBUTE3", length = 50)
    public String getAttribute3() {
        return this.attribute3;
    }

    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    @Column(name = "ATTRIBUTE4")
    public String getAttribute4() {
        return this.attribute4;
    }

    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    @Column(name = "ATTRIBUTE5")
    public String getAttribute5() {
        return this.attribute5;
    }

    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTMODIFIED_DATE", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    public String getItemCategory() {
        return itemCategory;
    }

    public void setItemCategory(String itemCategory) {
        this.itemCategory = itemCategory;
    }

    public String getItemUOM() {
        return itemUOM;
    }

    public void setItemUOM(String itemUOM) {
        this.itemUOM = itemUOM;
    }

}
