package tenant.classes;
// Generated 29 Sep, 2016 3:48:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FollowUp generated by hbm2java
 */
@Entity
@Table(name = "follow_up", schema = "arete_tms"
)
public class FollowUp implements java.io.Serializable {

    private Integer sno;
    private String orgId;
    private String userId;
    private String leadCode;
    private String leadName;
    private String assetCode;
    private String assetName;
    private String contactName;
    private String salesPersonName;
    private Date folloeUpDate;
    private String followUpRemarks;
    private String recordStatus;
    private String status;
    private Date creationDate;
    private Date lastmodifiedDate;

    public FollowUp() {
    }

    public FollowUp(String userId) {
        this.userId = userId;
    }

    public FollowUp(String orgId, String userId, String leadCode, String leadName, String assetCode, String assetName, String contactName, String salesPersonName, Date folloeUpDate, String followUpRemarks, String recordStatus, String status, Date creationDate, Date lastmodifiedDate) {
        this.orgId = orgId;
        this.userId = userId;
        this.leadCode = leadCode;
        this.leadName = leadName;
        this.assetCode = assetCode;
        this.assetName = assetName;
        this.contactName = contactName;
        this.salesPersonName = salesPersonName;
        this.folloeUpDate = folloeUpDate;
        this.followUpRemarks = followUpRemarks;
        this.recordStatus = recordStatus;
        this.status = status;
        this.creationDate = creationDate;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "sno", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "org_Id", length = 20)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "user_Id", nullable = false, length = 20)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "Lead_Code", length = 20)
    public String getLeadCode() {
        return this.leadCode;
    }

    public void setLeadCode(String leadCode) {
        this.leadCode = leadCode;
    }

    @Column(name = "Lead_Name", length = 100)
    public String getLeadName() {
        return this.leadName;
    }

    public void setLeadName(String leadName) {
        this.leadName = leadName;
    }

    @Column(name = "Asset_Code", length = 20)
    public String getAssetCode() {
        return this.assetCode;
    }

    public void setAssetCode(String assetCode) {
        this.assetCode = assetCode;
    }

    @Column(name = "Asset_Name", length = 50)
    public String getAssetName() {
        return this.assetName;
    }

    public void setAssetName(String assetName) {
        this.assetName = assetName;
    }

    @Column(name = "Contact_Name", length = 50)
    public String getContactName() {
        return this.contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    @Column(name = "Sales_Person_Name", length = 50)
    public String getSalesPersonName() {
        return salesPersonName;
    }

    public void setSalesPersonName(String salesPersonName) {
        this.salesPersonName = salesPersonName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FolloeUpDate", length = 19)
    public Date getFolloeUpDate() {
        return this.folloeUpDate;
    }

    public void setFolloeUpDate(Date folloeUpDate) {
        this.folloeUpDate = folloeUpDate;
    }

    @Column(name = "FollowUpRemarks", length = 200)
    public String getFollowUpRemarks() {
        return this.followUpRemarks;
    }

    public void setFollowUpRemarks(String followUpRemarks) {
        this.followUpRemarks = followUpRemarks;
    }

    @Column(name = "Record_Status", length = 50)
    public String getRecordStatus() {
        return this.recordStatus;
    }

    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    @Column(name = "Status", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATION_DATE", length = 19)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Lastmodified_Date", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

}
