package tenant.classes;
// Generated 21 Sep, 2016 3:04:58 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AssetDetails generated by hbm2java
 */
@Entity
@Table(name = "grn_details", schema = "arete_tms"
)
public class Grn implements java.io.Serializable {

    private int SNo;
    private String grnNo;
    private String orgId;
    private String userId;
    private String poNo;
    private Date grnDate;
    private String receivedBy;
    private String customerInvoiceNo;
    private Date customerInvoiceDate;
    private String supplierName;
    private String supplierAddress;
    private String supplierCntNo;
    private String supplierMailId;
    private String inventoryLocation;
    private String deliveryLocation;
    private String subAssetCode;
    private String category;
    private String type;
    private String orderedQty;
    private String receivedQty;
    private String foc;
    private String uom;
    private String manufacturer;
    private String model;
    private Date expiryDate;
    private String warrantyPeriod;
    private String grnStatus;
    private String remarks;
    private String itemCode;
    private String itemName;
//    private Date creationDate;
    private String status;
    private Date lastmodifiedDate;
    private String discount;
    private String qtyAcc;
    private String qtyRej;
    private String grandTotal;
    private String unitPrice;
    private String totalValue;

    public Grn() {
    }

    public Grn(int SNo, String grnNo, String orgId, String userId, String poNo, Date grnDate, String receivedBy, String customerInvoiceNo, Date customerInvoiceDate, String supplierName, String supplierAddress, String supplierCntNo, String supplierMailId, String inventoryLocation, String deliveryLocation, String orderedQty, String receivedQty, String foc, String uom, String manufacturer, String model, Date expiryDate, String warrantyPeriod, String grnStatus, String remarks, String itemCode, String itemName, String status, Date lastmodifiedDate, String qtyAccepted, String qtyRejected, String unitPrice, String totalPrice, String discount, String grandTotal) {
        this.SNo = SNo;
        this.grnNo = grnNo;
        this.orgId = orgId;
        this.userId = userId;
        this.poNo = poNo;
        this.grnDate = grnDate;
        this.receivedBy = receivedBy;
        this.customerInvoiceNo = customerInvoiceNo;
        this.customerInvoiceDate = customerInvoiceDate;
        this.supplierName = supplierName;
        this.supplierAddress = supplierAddress;
        this.supplierCntNo = supplierCntNo;
        this.supplierMailId = supplierMailId;
        this.inventoryLocation = inventoryLocation;
        this.deliveryLocation = deliveryLocation;
//        this.subAssetCode = subAssetCode;
//        this.category = category;
//        this.type = type;
        this.orderedQty = orderedQty;
        this.receivedQty = receivedQty;
        this.foc = foc;
        this.uom = uom;
        this.manufacturer = manufacturer;
        this.model = model;
        this.expiryDate = expiryDate;
        this.warrantyPeriod = warrantyPeriod;
        this.grnStatus = grnStatus;
        this.remarks = remarks;
        this.itemCode = itemCode;
        this.itemName = itemName;
//        this.creationDate = creationDate;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        //added by garun 
        this.discount = discount;
        this.grandTotal = grandTotal;
        this.qtyAcc = qtyAccepted;
        this.qtyRej = qtyRejected;
        this.unitPrice = unitPrice;
        this.totalValue = totalPrice;

    }

    public Grn(String grnNo, String orgId, String userId, String poNo, Date grnDate, String receivedBy, String customerInvoiceNo, Date customerInvoiceDate, String supplierName, String supplierAddress, String supplierCntNo, String supplierMailId, String inventoryLocation, String deliveryLocation, String orderedQty, String receivedQty, String foc, String uom, String manufacturer, String model, Date expiryDate, String warrantyPeriod, String grnStatus, String remarks, String itemCode, String itemName, String status, Date lastmodifiedDate, String qtyAccepted, String qtyRejected, String unitPrice, String totalPrice, String discount, String grandTotal) {
        this.grnNo = grnNo;
        this.orgId = orgId;
        this.userId = userId;
        this.poNo = poNo;
        this.grnDate = grnDate;
        this.receivedBy = receivedBy;
        this.customerInvoiceNo = customerInvoiceNo;
        this.customerInvoiceDate = customerInvoiceDate;
        this.supplierName = supplierName;
        this.supplierAddress = supplierAddress;
        this.supplierCntNo = supplierCntNo;
        this.supplierMailId = supplierMailId;
        this.inventoryLocation = inventoryLocation;
        this.deliveryLocation = deliveryLocation;
//        this.subAssetCode = subAssetCode;
//        this.category = category;
//        this.type = type;
        this.orderedQty = orderedQty;
        this.receivedQty = receivedQty;
        this.foc = foc;
        this.uom = uom;
        this.manufacturer = manufacturer;
        this.model = model;
        this.expiryDate = expiryDate;
        this.warrantyPeriod = warrantyPeriod;
        this.grnStatus = grnStatus;
        this.remarks = remarks;
        this.itemCode = itemCode;
        this.itemName = itemName;
//        this.creationDate = creationDate;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        //added by garun 
        this.discount = discount;
        this.grandTotal = grandTotal;
        this.qtyAcc = qtyAccepted;
        this.qtyRej = qtyRejected;
        this.unitPrice = unitPrice;
        this.totalValue = totalPrice;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "s_no", unique = true, nullable = false)
    public int getSNo() {
        return SNo;
    }

    public void setSNo(int SNo) {
        this.SNo = SNo;
    }

    @Column(name = "grn_no", length = 60)
    public String getGrnNo() {
        return grnNo;
    }

    public void setGrnNo(String grnNo) {
        this.grnNo = grnNo;
    }

    @Column(name = "po_no", length = 60)
    public String getPoNo() {
        return poNo;
    }

    public void setPoNo(String poNo) {
        this.poNo = poNo;
    }

    @Column(name = "org_id", length = 50)
    public String getOrgId() {
        return orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "user_id", length = 50)
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "customer_invoice_no", length = 60)
    public String getCustomerInvoiceNo() {
        return customerInvoiceNo;
    }

    public void setCustomerInvoiceNo(String customerInvoiceNo) {
        this.customerInvoiceNo = customerInvoiceNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "customer_invoice_date", length = 60)
    public Date getCustomerInvoiceDate() {
        return customerInvoiceDate;
    }

    public void setCustomerInvoiceDate(Date customerInvoiceDate) {
        this.customerInvoiceDate = customerInvoiceDate;
    }

    @Column(name = "SUPPLIER_CODE", length = 60)
    public String getSupplierName() {
        return supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    @Column(name = "supplier_address", length = 500)
    public String getSupplierAddress() {
        return supplierAddress;
    }

    public void setSupplierAddress(String supplierAddress) {
        this.supplierAddress = supplierAddress;
    }

    @Column(name = "supplier_cnt_no", length = 20)
    public String getSupplierCntNo() {
        return supplierCntNo;
    }

    public void setSupplierCntNo(String supplierCntNo) {
        this.supplierCntNo = supplierCntNo;
    }

    @Column(name = "supplier_mailId", length = 60)
    public String getSupplierMailId() {
        return supplierMailId;
    }

    public void setSupplierMailId(String supplierMailId) {
        this.supplierMailId = supplierMailId;
    }

    @Column(name = "inventory_location", length = 100)
    public String getInventoryLocation() {
        return inventoryLocation;
    }

    public void setInventoryLocation(String inventoryLocation) {
        this.inventoryLocation = inventoryLocation;
    }

    @Column(name = "sub_asset_code", length = 60)
    public String getSubAssetCode() {
        return subAssetCode;
    }

    public void setSubAssetCode(String subAssetCode) {
        this.subAssetCode = subAssetCode;
    }

    @Column(name = "category", length = 60)
    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    @Column(name = "type", length = 60)
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "ordered_qty", length = 60)
    public String getOrderedQty() {
        return orderedQty;
    }

    public void setOrderedQty(String orderedQty) {
        this.orderedQty = orderedQty;
    }

    @Column(name = "received_qty", length = 60)
    public String getReceivedQty() {
        return receivedQty;
    }

    public void setReceivedQty(String receivedQty) {
        this.receivedQty = receivedQty;
    }

    @Column(name = "foc", length = 60)
    public String getFoc() {
        return foc;
    }

    public void setFoc(String foc) {
        this.foc = foc;
    }

    @Column(name = "uom", length = 60)
    public String getUom() {
        return uom;
    }

    public void setUom(String uom) {
        this.uom = uom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "expiry_date", length = 60)
    public Date getExpiryDate() {
        return expiryDate;
    }

    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    @Column(name = "warranty_period", length = 60)
    public String getWarrantyPeriod() {
        return warrantyPeriod;
    }

    public void setWarrantyPeriod(String warrantyPeriod) {
        this.warrantyPeriod = warrantyPeriod;
    }

    @Column(name = "remarks", length = 500)
    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "item_code", length = 60)
    public String getItemCode() {
        return itemCode;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    @Column(name = "item_name", length = 60)
    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

//    @Temporal(TemporalType.DATE)
//    @Column(name="creation_date", length=60)
//    public Date getCreationDate() {
//        return creationDate;
//    }
//
//    public void setCreationDate(Date creationDate) {
//        this.creationDate = creationDate;
//    }
    @Column(name = "status", length = 60)
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "last_modified_date", length = 60)
    public Date getLastmodifiedDate() {
        return lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "grn_date", length = 60)
    public Date getGrnDate() {
        return grnDate;
    }

    public void setGrnDate(Date grnDate) {
        this.grnDate = grnDate;
    }

    @Column(name = "received_by", length = 60)
    public String getReceivedBy() {
        return receivedBy;
    }

    public void setReceivedBy(String receivedBy) {
        this.receivedBy = receivedBy;
    }

    @Column(name = "delivery_location", length = 60)
    public String getDeliveryLocation() {
        return deliveryLocation;
    }

    public void setDeliveryLocation(String deliveryLocation) {
        this.deliveryLocation = deliveryLocation;
    }

    @Column(name = "manufacturer", length = 60)
    public String getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    @Column(name = "model", length = 60)
    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    @Column(name = "grn_status", length = 60)
    public String getGrnStatus() {
        return grnStatus;
    }

    public void setGrnStatus(String grnStatus) {
        this.grnStatus = grnStatus;
    }

    @Column(name = "discount", length = 60)
    public String getDiscount() {
        return discount;
    }

    public void setDiscount(String discount) {
        this.discount = discount;
    }

    @Column(name = "qty_accepted", length = 60)
    public String getQtyAcc() {
        return qtyAcc;
    }

    public void setQtyAcc(String qtyAcc) {
        this.qtyAcc = qtyAcc;
    }

    @Column(name = "qty_rejected", length = 60)
    public String getQtyRej() {
        return qtyRej;
    }

    public void setQtyRej(String qtyRej) {
        this.qtyRej = qtyRej;
    }

    @Column(name = "grand_total", length = 60)
    public String getGrandTotal() {
        return grandTotal;
    }

    public void setGrandTotal(String grandTotal) {
        this.grandTotal = grandTotal;
    }

    @Column(name = "unit_price", length = 60)
    public String getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(String unitPrice) {
        this.unitPrice = unitPrice;
    }

    @Column(name = "total_value", length = 60)
    public String getTotalValue() {
        return totalValue;
    }

    public void setTotalValue(String totalValue) {
        this.totalValue = totalValue;
    }

}
