/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tenant.classes;
// Generated 11 Dec, 2016 5:12:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HostEmailConfig generated by hbm2java
 */
@Entity
@Table(name="host_email_config"
    ,schema = "arete_tms"
)
public class HostEmailConfig  implements java.io.Serializable {


     private Integer sno;
     private String orgId;
     private String userId;
     private String moduleName;
     private String deptName;
     private String emailFrom;
     private String passwordFrom;
     private String emailTo;
     private String emailCc;
     private String hostName;
     private String status;

    public HostEmailConfig() {
    }

	
    public HostEmailConfig(Integer sno, String orgId) {
        this.sno = sno;
        this.orgId = orgId;
    }
    public HostEmailConfig(Integer sno, String orgId, String userId, String moduleName, String deptName, String emailFrom, String passwordFrom, String emailTo, String emailCc, String hostName, String status) {
       this.sno = sno;
       this.orgId = orgId;
       this.userId = userId;
       this.moduleName = moduleName;
       this.deptName = deptName;
       this.emailFrom = emailFrom;
       this.passwordFrom = passwordFrom;
       this.emailTo = emailTo;
       this.emailCc = emailCc;
       this.hostName = hostName;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="s_no", unique=true, nullable=false, precision=22, scale=0)
    public Integer getSno() {
        return this.sno;
    }
    
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    
    @Column(name="org_no", nullable=false, length=20)
    public String getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    
    @Column(name="user_id", length=60)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="module_name", length=120)
    public String getModuleName() {
        return this.moduleName;
    }
    
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    
    @Column(name="dept_name", length=120)
    public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    
    @Column(name="email_from", length=120)
    public String getEmailFrom() {
        return this.emailFrom;
    }
    
    public void setEmailFrom(String emailFrom) {
        this.emailFrom = emailFrom;
    }

    
    @Column(name="password_from", length=100)
    public String getPasswordFrom() {
        return this.passwordFrom;
    }
    
    public void setPasswordFrom(String passwordFrom) {
        this.passwordFrom = passwordFrom;
    }

    
    @Column(name="email_to", length=600)
    public String getEmailTo() {
        return this.emailTo;
    }
    
    public void setEmailTo(String emailTo) {
        this.emailTo = emailTo;
    }

    
    @Column(name="email_cc", length=600)
    public String getEmailCc() {
        return this.emailCc;
    }
    
    public void setEmailCc(String emailCc) {
        this.emailCc = emailCc;
    }

    
    @Column(name="host_name", length=120)
    public String getHostName() {
        return this.hostName;
    }
    
    public void setHostName(String hostName) {
        this.hostName = hostName;
    }

    
    @Column(name="status", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}



