package tenant.classes;
// Generated Sep 7, 2016 12:08:23 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TenantDetails generated by hbm2java
 */
@Entity
@Table(name = "individual_utility", schema = "arete_tms"
) 
public class IndividualUitlity implements java.io.Serializable {

    private Integer SNo;
    private Date lastmodifiedDate;
    private String utility;
    private String utilityBill;   
    private String status;   
    private String utilityCode;   
    private String utilityBillType;   
    private String utilityBillYear;   
    private String remarks;
    

    public IndividualUitlity() {
    }    
    public IndividualUitlity(Integer SNo, String utility,String remarks, String utilityBill,String status,String utilityCode,String utilityBillType,
            String utilityBillYear,Date lastmodifiedDate) {
        this.SNo = SNo;
        this.utility = utility;
        this.remarks= remarks;
        this.utilityBill = utilityBill;             
        this.status = status;
        this.utilityCode = utilityCode;
        this.utilityBillType = utilityBillType;
        this.utilityBillYear = utilityBillYear;
        this.lastmodifiedDate = lastmodifiedDate;
        
    }
    public IndividualUitlity(String utility,String remarks, String utilityBill,String status,String utilityCode,String utilityBillType, String utilityBillYear,Date lastmodifiedDate) {
       
        this.utility = utility;
        this.remarks = remarks;
        this.utilityBill = utilityBill;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.utilityCode = utilityCode;
        this.utilityBillType = utilityBillType;
        this.utilityBillYear = utilityBillYear;
    }   

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "s_no", unique = true, nullable = false)
    public Integer getSNo() {
        return this.SNo;
    }

    public void setSNo(Integer SNo) {
        this.SNo = SNo;
    }    

    @Column(name = "utility", length = 60)
    public String getUtility() {
        return this.utility;
    }

    public void setUtility(String utility) {
        this.utility = utility;
    }
    @Column(name = "utility_bill", length = 60)
    public String getUtilityBill() {
        return this.utilityBill;
    }

    public void setUtilityBill(String utilityBill) {
        this.utilityBill = utilityBill;
    }  
@Column(name = "utility_Code", length = 60)
    public String getUtilityCode() {
        return this.utilityCode;
    }

    public void setUtilityCode(String utilityCode) {
        this.utilityCode = utilityCode;
    }
    @Column(name = "utility_bill_type", length = 60)
    public String getUtilityBillType() {
        return this.utilityBillType;
    }

    public void setUtilityBillType(String utilityBillType) {
        this.utilityBillType = utilityBillType;
    }
    @Column(name = "utility_Year_bill", length = 60)
    public String getUtilityBillYear() {
        return this.utilityBillYear;
    }

    public void setUtilityBillYear(String utilityBillYear) {
        this.utilityBillYear = utilityBillYear;
    }
    @Column(name = "status", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "remarks")
    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    
    

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lastmodified_date", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

}
