package tenant.classes;
// Generated 22 Sep, 2016 10:06:28 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * InsuranceMaster generated by hbm2java
 */
@Entity
@Table(name = "insurance_master", schema = "arete_tms", uniqueConstraints = @UniqueConstraint(columnNames = "SNO")
)
public class InsuranceMaster implements java.io.Serializable {

    private String insuranceCompanyId;
    private int sno;
    private String orgId;
    private String userId;
    private String insuranceCompanyName;
    private String insuranceDesc;
    private String attribute1;
    private String attribute2;
    private String attribute3;
    private String attribute4;
    private String attribute5;
    private String status;
    private Date creationDate;
    private Date lastmodifiedDate;
    private String insuranceCompId;

    public InsuranceMaster() {
    }

    public InsuranceMaster(int sno) {
        this.sno = sno;
    }

    public InsuranceMaster(int sno, String orgId, String userId, String insuranceCompanyName, String insuranceDesc, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, String status, Date creationDate, Date lastmodifiedDate, String insuranceCompId) {
        this.sno = sno;
        this.orgId = orgId;
        this.userId = userId;
        this.insuranceCompanyName = insuranceCompanyName;
        this.insuranceDesc = insuranceDesc;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.status = status;
        this.creationDate = creationDate;
        this.lastmodifiedDate = lastmodifiedDate;
        this.insuranceCompId = insuranceCompId;
    }

    public InsuranceMaster(String insuranceCompanyId, int sno, String orgId, String userId, String insuranceCompanyName, String insuranceDesc, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, String status, Date lastmodifiedDate) {
        this.insuranceCompanyId = insuranceCompanyId;
        this.sno = sno;
        this.orgId = orgId;
        this.userId = userId;
        this.insuranceCompanyName = insuranceCompanyName;
        this.insuranceDesc = insuranceDesc;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    public InsuranceMaster(String insuranceCompanyId, String orgId, String userId, String insuranceCompanyName, String insuranceDesc, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, String status, Date creationDate, Date lastmodifiedDate) {
        this.insuranceCompanyId = insuranceCompanyId;
        this.orgId = orgId;
        this.userId = userId;
        this.insuranceCompanyName = insuranceCompanyName;
        this.insuranceDesc = insuranceDesc;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.status = status;
        this.creationDate = creationDate;
        this.lastmodifiedDate = lastmodifiedDate;

    }

    @Column(name = "INSURANCE_COMPANY_ID", nullable = false, length = 20)
    public String getInsuranceCompanyId() {
        return this.insuranceCompanyId;
    }

    public void setInsuranceCompanyId(String insuranceCompanyId) {
        this.insuranceCompanyId = insuranceCompanyId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "SNO", unique = true, nullable = false)
    public int getSno() {
        return this.sno;
    }

    public void setSno(int sno) {
        this.sno = sno;
    }

    @Column(name = "ORG_ID", length = 50)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "USER_ID", length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "INSURANCE_COMPANY_NAME", length = 100)
    public String getInsuranceCompanyName() {
        return this.insuranceCompanyName;
    }

    public void setInsuranceCompanyName(String insuranceCompanyName) {
        this.insuranceCompanyName = insuranceCompanyName;
    }

    @Column(name = "INSURANCE_DESC", length = 160)
    public String getInsuranceDesc() {
        return this.insuranceDesc;
    }

    public void setInsuranceDesc(String insuranceDesc) {
        this.insuranceDesc = insuranceDesc;
    }

    @Column(name = "ATTRIBUTE1")
    public String getAttribute1() {
        return this.attribute1;
    }

    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    @Column(name = "ATTRIBUTE2")
    public String getAttribute2() {
        return this.attribute2;
    }

    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    @Column(name = "ATTRIBUTE3", length = 50)
    public String getAttribute3() {
        return this.attribute3;
    }

    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    @Column(name = "ATTRIBUTE4", length = 500)
    public String getAttribute4() {
        return this.attribute4;
    }

    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    @Column(name = "ATTRIBUTE5", length = 500)
    public String getAttribute5() {
        return this.attribute5;
    }

    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATION_DATE", length = 19)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTMODIFIED_DATE", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Column(name = "INSURANCE_COMP_ID", length = 60)
    public String getInsuranceCompId() {
        return this.insuranceCompId;
    }

    public void setInsuranceCompId(String insuranceCompId) {
        this.insuranceCompId = insuranceCompId;
    }

}
