package tenant.classes;
// Generated 22 Sep, 2016 10:06:28 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * InsuranceDetails generated by hbm2java
 */
@Entity
@Table(name = "insurance_details", schema = "arete_tms", uniqueConstraints = @UniqueConstraint(columnNames = "SNO")
)
public class InsuranceDetails implements java.io.Serializable {

    private String insuranceId;
    private int sno;
    private String orgId;
    private String userId;
    private String insuranceNo;
    private String insuranceFor;
    private String insuranceCompanyId;
    private Date insValidFrom;
    private Date insValidTo;
    private String insurTerm;
    private String remarks;
    private String insuranceType;
    private String attribute2;
    private String attribute3;
    private String attribute4;
    private String attribute5;
    private String status;
    private Date creationDate;
    private Date lastmodifiedDate;
    private String insuranceCategory;
    private String insuredAmount;
    private String premiumAmount;
    private String frequency;

    
      

    public InsuranceDetails() {
    }

    public InsuranceDetails(int sno) {
        this.sno = sno;
    }

    public InsuranceDetails(int sno, String orgId, String userId, String insuranceNo, String insuranceFor, String insuranceCompanyId, Date insValidFrom, Date insValidTo, String remarks, String insuranceType, String attribute2, String attribute3, String attribute4, String attribute5, String status, Date creationDate, Date lastmodifiedDate,String insuranceCategory,String insuredAmount,String premiumAmount,String frequency) {
        this.sno = sno;
        this.orgId = orgId;
        this.userId = userId;
        this.insuranceNo = insuranceNo;
        this.insuranceFor = insuranceFor;
        this.insuranceCompanyId = insuranceCompanyId;
        this.insValidFrom = insValidFrom;
        this.insValidTo = insValidTo;
        this.remarks = remarks;
        this.insuranceType = insuranceType;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.status = status;
        this.creationDate = creationDate;
        this.lastmodifiedDate = lastmodifiedDate;
        this.insuranceCategory=insuranceCategory;
        this.insuredAmount = insuredAmount;
        this.premiumAmount = premiumAmount;
        this.frequency=frequency;
    }

    public InsuranceDetails(String insuranceId, int sno, String orgId, String userId, String insuranceNo, String insuranceFor, String insuranceCompanyId, Date insValidFrom, Date insValidTo, String insurTerm, String remarks, String insuranceType, String attribute2, String attribute3, String attribute4, String attribute5, String status, Date lastmodifiedDate,String insuranceCategory,String insuredAmount,String premiumAmount,String frequency) {
        this.insuranceId = insuranceId;
        this.sno = sno;
        this.orgId = orgId;
        this.userId = userId;
        this.insuranceNo = insuranceNo;
        this.insuranceFor = insuranceFor;
        this.insuranceCompanyId = insuranceCompanyId;
        this.insValidFrom = insValidFrom;
        this.insValidTo = insValidTo;
        this.insurTerm = insurTerm;
        this.remarks = remarks;
        this.insuranceType = insuranceType;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.insuranceCategory=insuranceCategory;
        this.insuredAmount = insuredAmount;
        this.premiumAmount = premiumAmount;
        this.frequency=frequency;
    }

    public InsuranceDetails(String insuranceId, String orgId, String userId, String insuranceNo, String insuranceFor, String insuranceCompanyId, Date insValidFrom, Date insValidTo, String insurTerm, String remarks, String insuranceType, String attribute2, String attribute3, String attribute4, String attribute5, String status, Date creationDate, Date lastmodifiedDate,String insuranceCategory,String insuredAmount,String premiumAmount,String frequency) {
        this.insuranceId = insuranceId;
        this.orgId = orgId;
        this.userId = userId;
        this.insuranceNo = insuranceNo;
        this.insuranceFor = insuranceFor;
        this.insuranceCompanyId = insuranceCompanyId;
        this.insValidFrom = insValidFrom;
        this.insValidTo = insValidTo;
        this.insurTerm = insurTerm;
        this.remarks = remarks;
        this.insuranceType = insuranceType;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.status = status;
        this.creationDate = creationDate;
        this.lastmodifiedDate = lastmodifiedDate;
        this.insuranceCategory=insuranceCategory;
        this.insuredAmount = insuredAmount;
        this.premiumAmount = premiumAmount;
        this.frequency=frequency;
    }

    @Column(name = "INSURANCE_ID", unique = true, nullable = false, length = 20)
    public String getInsuranceId() {
        return this.insuranceId;
    }

    public void setInsuranceId(String insuranceId) {
        this.insuranceId = insuranceId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "SNO", unique = true, nullable = false)
    public int getSno() {
        return this.sno;
    }

    public void setSno(int sno) {
        this.sno = sno;
    }

    @Column(name = "ORG_ID", length = 50)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "USER_ID", length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "INSURANCE_NO", length = 60)
    public String getInsuranceNo() {
        return this.insuranceNo;
    }

    public void setInsuranceNo(String insuranceNo) {
        this.insuranceNo = insuranceNo;
    }

    @Column(name = "INSURANCE_FOR", length = 50)
    public String getInsuranceFor() {
        return this.insuranceFor;
    }

    public void setInsuranceFor(String insuranceFor) {
        this.insuranceFor = insuranceFor;
    }

    @Column(name = "INSURANCE_COMPANY_ID", length = 20)
    public String getInsuranceCompanyId() {
        return this.insuranceCompanyId;
    }

    public void setInsuranceCompanyId(String insuranceCompanyId) {
        this.insuranceCompanyId = insuranceCompanyId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "INS_VALID_FROM", length = 10)
    public Date getInsValidFrom() {
        return this.insValidFrom;
    }

    public void setInsValidFrom(Date insValidFrom) {
        this.insValidFrom = insValidFrom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "INS_VALID_TO", length = 10)
    public Date getInsValidTo() {
        return this.insValidTo;
    }

    public void setInsValidTo(Date insValidTo) {
        this.insValidTo = insValidTo;
    }

    @Column(name = "INSURANCE_TERM", length = 50)
    public String getInsurTerm() {
        return insurTerm;
    }

    public void setInsurTerm(String insurTerm) {
        this.insurTerm = insurTerm;
    }

    @Column(name = "REMARKS", length = 500)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "INSURANCE_TYPE")
    public String getInsuranceType() {
        return this.insuranceType;
    }

    public void setInsuranceType(String insuranceType) {
        this.insuranceType = insuranceType;
    }

    @Column(name = "ATTRIBUTE2")
    public String getAttribute2() {
        return this.attribute2;
    }

    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    @Column(name = "ATTRIBUTE3", length = 50)
    public String getAttribute3() {
        return this.attribute3;
    }

    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    @Column(name = "ATTRIBUTE4", length = 500)
    public String getAttribute4() {
        return this.attribute4;
    }

    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    @Column(name = "ATTRIBUTE5", length = 500)
    public String getAttribute5() {
        return this.attribute5;
    }

    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATION_DATE", length = 19)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    
    ///Newly Added By Lakshmi
    @Column(name = "INSURANCE_CATEGORY", length = 50)
    public String getInsuranceCategory() {
        return insuranceCategory;
    }

    public void setInsuranceCategory(String insuranceCategory) {
        this.insuranceCategory = insuranceCategory;
    }
    ////////
    
    @Column(name = "INSURANCE_AMOUNT", length = 50)
    public String getInsuredAmount() {
        return insuredAmount;
    }

    public void setInsuredAmount(String insuredAmount) {
        this.insuredAmount = insuredAmount;
    }

    @Column(name = "PREMIUM_AMOUNT", length = 50)
    public String getPremiumAmount() {
        return premiumAmount;
    }

    public void setPremiumAmount(String premiumAmount) {
        this.premiumAmount = premiumAmount;
    }

    @Column(name = "FREQUENCY", length = 50)
    public String getFrequency() {
        return frequency;
    }

    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }
    

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTMODIFIED_DATE", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

}
