package tenant.classes;
// Generated 26 Feb, 2016 4:46:53 PM by Hibernate Tools 4.3.1

import java.io.Serializable;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InventoryCount generated by hbm2java
 */
@Entity
@Table(name = "inventory_count", schema = "arete_tms"
)
public class InventoryCount implements Serializable {

    private Integer SNo;
    private String userId;
    private String orgId;
    private String storeLocationName;
    private String itemCode;
    private String itemName;
    private String batchNo;
    private Date expiryDate;
    private String uom;
    private Double availableStock;
    private Double physicalCountQty;
    private Date physicalCountDate;
    private String preparedBy;
    private String status;
    private Date lastmodifiedDate;
    private Double varianceQty;
    private String storeManagerRemarks;
    private String financeManagerRemarks;
    private String storeManagerName;
    private String financeManagerName;
    private String inventoryStatus;
    private Double unitPrice;

    public InventoryCount() {
    }

    public InventoryCount(String userId, String orgId, String storeLocationName, String itemCode, String itemName,
            String batchNo, Date expiryDate, String uom, Double availableStock, Double physicalCountQty,
            Date physicalCountDate, String preparedBy, String status, Date lastmodifiedDate, Double varianceQty, String inventoryStatus, Double unitPrice) {
        this.userId = userId;
        this.orgId = orgId;
        this.storeLocationName = storeLocationName;
        this.itemCode = itemCode;
        this.itemName = itemName;
        this.batchNo = batchNo;
        this.expiryDate = expiryDate;
        this.uom = uom;
        this.availableStock = availableStock;
        this.physicalCountQty = physicalCountQty;
        this.physicalCountDate = physicalCountDate;
        this.preparedBy = preparedBy;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.varianceQty = varianceQty;
        this.inventoryStatus = inventoryStatus;
        this.unitPrice = unitPrice;
    }

    public InventoryCount(Integer SNo) {
        this.SNo = SNo;
    }

    public InventoryCount(Integer SNo, String userId, String orgId, String storeLocationName, String itemCode, String itemName, String batchNo, Date expiryDate, String uom, Double availableStock, Double physicalCountQty, Date physicalCountDate, String preparedBy, String status, Date lastmodifiedDate) {
        this.SNo = SNo;
        this.userId = userId;
        this.orgId = orgId;
        this.storeLocationName = storeLocationName;
        this.itemCode = itemCode;
        this.itemName = itemName;
        this.batchNo = batchNo;
        this.expiryDate = expiryDate;
        this.uom = uom;
        this.availableStock = availableStock;
        this.physicalCountQty = physicalCountQty;
        this.physicalCountDate = physicalCountDate;
        this.preparedBy = preparedBy;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "s_no", unique = true, nullable = false)
    public Integer getSNo() {
        return this.SNo;
    }

    public void setSNo(Integer SNo) {
        this.SNo = SNo;
    }

    @Column(name = "user_id", length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "org_id", length = 50)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "store_location_name", length = 150)
    public String getStoreLocationName() {
        return this.storeLocationName;
    }

    public void setStoreLocationName(String storeLocationName) {
        this.storeLocationName = storeLocationName;
    }

    @Column(name = "item_code", length = 80)
    public String getItemCode() {
        return this.itemCode;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    @Column(name = "item_name", length = 120)
    public String getItemName() {
        return this.itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    @Column(name = "batch_no", length = 30)
    public String getBatchNo() {
        return this.batchNo;
    }

    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "expiry_date", length = 7)
    public Date getExpiryDate() {
        return this.expiryDate;
    }

    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    @Column(name = "uom", length = 50)
    public String getUom() {
        return this.uom;
    }

    public void setUom(String uom) {
        this.uom = uom;
    }

    @Column(name = "available_stock", precision = 10, scale = 0)
    public Double getAvailableStock() {
        return this.availableStock;
    }

    public void setAvailableStock(Double availableStock) {
        this.availableStock = availableStock;
    }

    @Column(name = "physical_count_qty", precision = 10, scale = 0)
    public Double getPhysicalCountQty() {
        return this.physicalCountQty;
    }

    public void setPhysicalCountQty(Double physicalCountQty) {
        this.physicalCountQty = physicalCountQty;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "physical_count_date", length = 7)
    public Date getPhysicalCountDate() {
        return this.physicalCountDate;
    }

    public void setPhysicalCountDate(Date physicalCountDate) {
        this.physicalCountDate = physicalCountDate;
    }

    @Column(name = "prepared_by", length = 50)
    public String getPreparedBy() {
        return this.preparedBy;
    }

    public void setPreparedBy(String preparedBy) {
        this.preparedBy = preparedBy;
    }

    @Column(name = "status", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "lastmodified_date")
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Column(name = "variance_qty", length = 50)
    public Double getVarianceQty() {
        return varianceQty;
    }

    public void setVarianceQty(Double varianceQty) {
        this.varianceQty = varianceQty;
    }

    @Column(name = "store_manager_remarks", length = 50)
    public String getStoreManagerRemarks() {
        return storeManagerRemarks;
    }

    public void setStoreManagerRemarks(String storeManagerRemarks) {
        this.storeManagerRemarks = storeManagerRemarks;
    }

    @Column(name = "finance_manager_remarks", length = 50)
    public String getFinanceManagerRemarks() {
        return financeManagerRemarks;
    }

    public void setFinanceManagerRemarks(String financeManagerRemarks) {
        this.financeManagerRemarks = financeManagerRemarks;
    }

    @Column(name = "store_manager_name", length = 50)
    public String getStoreManagerName() {
        return storeManagerName;
    }

    public void setStoreManagerName(String storeManagerName) {
        this.storeManagerName = storeManagerName;
    }

    @Column(name = "finance_manager_name", length = 50)
    public String getFinanceManagerName() {
        return financeManagerName;
    }

    public void setFinanceManagerName(String financeManagerName) {
        this.financeManagerName = financeManagerName;
    }

    @Column(name = "inventory_status", length = 50)
    public String getInventoryStatus() {
        return inventoryStatus;
    }

    public void setInventoryStatus(String inventoryStatus) {
        this.inventoryStatus = inventoryStatus;
    }

    @Column(name = "unit_price", length = 50)
    public Double getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

}
