package tenant.classes;
// Generated Oct 15, 2016 12:01:01 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inventorylist generated by hbm2java
 */
@Entity
@Table(name = "inventorylist", schema = "arete_tms"
)
public class Inventorylist implements java.io.Serializable {

    private Integer SNo;
    private String userId;
    private String orgId;
    private String storeLocationName;
    private String itemSubCategory;
    private String itemCode;
    private String itemName;
    private String itemDesc;
    private String unit;
    private Double stockQty;
    private String batchNo;
    private Date expiryDate;
    private String itemStorageLocation;
    private String status;
    private Date lastmodifiedDate;
    private String projectCode;
    private Double unitPrice;
    private Double saftyStock;
    private Double totalValue;
    private String supplierCode;
    private String supplierName;
    private String poNo;
    private String grnNo;
    private String WAC;
    private String FOC;

    public Inventorylist() {
    }

    public Inventorylist(Integer SNo) {
        this.SNo = SNo;
    }

    public Inventorylist(Double unitPrice, String userId, String orgId, String storeLocationName, String itemSubCategory,
            String itemCode, String itemName, String itemDesc, String unit, Double stockQty,
            String batchNo, Date expiryDate, String itemStorageLocation, String status,
            Date lastmodifiedDate, String projectCode, Double saftyStock, Double totalValue,
            String supplierName, String supplierCode, String poNo, String grnNo) {
        this.unitPrice = unitPrice;
        this.userId = userId;
        this.orgId = orgId;
        this.storeLocationName = storeLocationName;
        this.itemSubCategory = itemSubCategory;
        this.itemCode = itemCode;
        this.itemName = itemName;
        this.itemDesc = itemDesc;
        this.unit = unit;
        this.stockQty = stockQty;
        this.batchNo = batchNo;
        this.expiryDate = expiryDate;
        this.itemStorageLocation = itemStorageLocation;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.projectCode = projectCode;
        this.saftyStock = saftyStock;
        this.totalValue = totalValue;
        this.supplierCode = supplierCode;
        this.supplierName = supplierName;
        this.poNo = poNo;
        this.grnNo = grnNo;
    }

    //----------- 1 GRN M PO----------
    public Inventorylist(Double unitPrice, String userId, String orgId, String storeLocationName, String itemSubCategory,
            String itemCode, String itemName, String itemDesc, String unit, Double stockQty,
            String batchNo, Date expiryDate, String itemStorageLocation, String status,
            Date lastmodifiedDate, String projectCode, Double saftyStock, Double totalValue,
            String supplierCode, String supplierName, String storageId,
            String activeStatus, String poNo, String grnNo) {
        this.unitPrice = unitPrice;
        this.userId = userId;
        this.orgId = orgId;
        this.storeLocationName = storeLocationName;
        this.itemSubCategory = itemSubCategory;
        this.itemCode = itemCode;
        this.itemName = itemName;
        this.itemDesc = itemDesc;
        this.unit = unit;
        this.stockQty = stockQty;
        this.batchNo = batchNo;
        this.expiryDate = expiryDate;
        this.itemStorageLocation = itemStorageLocation;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.projectCode = projectCode;
        this.saftyStock = saftyStock;
        this.totalValue = totalValue;
        this.supplierCode = supplierCode;
        this.supplierName = supplierName;
        this.poNo = poNo;
        this.grnNo = grnNo;

        //this.activeStatus = activeStatus;
    }

    public Inventorylist(Double unitPrice, String userId, String orgId, String storeLocationName, String itemSubCategory,
            String itemCode, String itemName, String itemDesc, String unit, Double stockQty,
            String batchNo, Date expiryDate, String itemStorageLocation, String status, Date lastmodifiedDate,
            String projectCode, Double saftyStock, Double totalValue, String supplierCode, String supplierName) {
        this.unitPrice = unitPrice;
        this.userId = userId;
        this.orgId = orgId;
        this.storeLocationName = storeLocationName;
        this.itemSubCategory = itemSubCategory;
        this.itemCode = itemCode;
        this.itemName = itemName;
        this.itemDesc = itemDesc;
        this.unit = unit;
        this.stockQty = stockQty;
        this.batchNo = batchNo;
        this.expiryDate = expiryDate;
        this.itemStorageLocation = itemStorageLocation;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.projectCode = projectCode;

        this.saftyStock = saftyStock;
        this.totalValue = totalValue;
        this.supplierCode = supplierCode;
        this.supplierName = supplierName;
    }

    public Inventorylist(Integer SNo, String userId, String orgId, String storeLocationName, String itemSubCategory, String itemCode, String itemName, String itemDesc, String unit, Double stockQty, String batchNo, Date expiryDate, String itemStorageLocation, String status, Date lastmodifiedDate, String projectCode) {
        this.SNo = SNo;
        this.userId = userId;
        this.orgId = orgId;
        this.storeLocationName = storeLocationName;
        this.itemSubCategory = itemSubCategory;
        this.itemCode = itemCode;
        this.itemName = itemName;
        this.itemDesc = itemDesc;
        this.unit = unit;
        this.stockQty = stockQty;
        this.batchNo = batchNo;
        this.expiryDate = expiryDate;
        this.itemStorageLocation = itemStorageLocation;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.projectCode = projectCode;
    }

    public Inventorylist(String WAC, String userId, String orgId, String storeLocationName, String itemSubCategory, String itemCode, String itemName, String itemDesc, String unit, Double stockQty, String batchNo, Date expiryDate, String itemStorageLocation, String status, Date lastmodifiedDate, String projectCode) {
        this.WAC = WAC;
        this.userId = userId;
        this.orgId = orgId;
        this.storeLocationName = storeLocationName;
        this.itemSubCategory = itemSubCategory;
        this.itemCode = itemCode;
        this.itemName = itemName;
        this.itemDesc = itemDesc;
        this.unit = unit;
        this.stockQty = stockQty;
        this.batchNo = batchNo;
        this.expiryDate = expiryDate;
        this.itemStorageLocation = itemStorageLocation;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.projectCode = projectCode;

    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "sno", unique = true, nullable = false)
    public Integer getSNo() {
        return SNo;
    }

    public void setSNo(Integer SNo) {
        this.SNo = SNo;
    }

    @Column(name = "user_id", length = 50)
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "org_id", length = 50)
    public String getOrgId() {
        return orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "store_location_name", length = 50)
    public String getStoreLocationName() {
        return storeLocationName;
    }

    public void setStoreLocationName(String storeLocationName) {
        this.storeLocationName = storeLocationName;
    }

    @Column(name = "item_sub_category", length = 50)
    public String getItemSubCategory() {
        return itemSubCategory;
    }

    public void setItemSubCategory(String itemSubCategory) {
        this.itemSubCategory = itemSubCategory;
    }

    @Column(name = "item_code", length = 50)
    public String getItemCode() {
        return itemCode;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    @Column(name = "item_name", length = 50)
    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    @Column(name = "item_desc", length = 50)
    public String getItemDesc() {
        return itemDesc;
    }

    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc;
    }

    @Column(name = "unit", length = 50)
    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    @Column(name = "stock_qty", length = 50)
    public Double getStockQty() {
        return stockQty;
    }

    public void setStockQty(Double stockQty) {
        this.stockQty = stockQty;
    }

    @Column(name = "batch_no", length = 50)
    public String getBatchNo() {
        return batchNo;
    }

    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "expiry_date", length = 10)
    public Date getExpiryDate() {
        return expiryDate;
    }

    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    @Column(name = "item_storage_location", length = 50)
    public String getItemStorageLocation() {
        return itemStorageLocation;
    }

    public void setItemStorageLocation(String itemStorageLocation) {
        this.itemStorageLocation = itemStorageLocation;
    }

    @Column(name = "status", length = 50)
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "lastmodified_date", length = 10)
    public Date getLastmodifiedDate() {
        return lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Column(name = "project_code", length = 50)
    public String getProjectCode() {
        return projectCode;
    }

    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    @Column(name = "unit_price", length = 50)
    public Double getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    @Column(name = "safty_stock", length = 50)
    public Double getSaftyStock() {
        return saftyStock;
    }

    public void setSaftyStock(Double saftyStock) {
        this.saftyStock = saftyStock;
    }

    @Column(name = "total_value", length = 50)
    public Double getTotalValue() {
        return totalValue;
    }

    public void setTotalValue(Double totalValue) {
        this.totalValue = totalValue;
    }

    @Column(name = "supplier_code", length = 50)
    public String getSupplierCode() {
        return supplierCode;
    }

    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode;
    }

    @Column(name = "supplier_name", length = 50)
    public String getSupplierName() {
        return supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    @Column(name = "po_no", length = 50)
    public String getPoNo() {
        return poNo;
    }

    public void setPoNo(String poNo) {
        this.poNo = poNo;
    }

    @Column(name = "grn_no", length = 50)
    public String getGrnNo() {
        return grnNo;
    }

    public void setGrnNo(String grnNo) {
        this.grnNo = grnNo;
    }

    @Column(name = "wac", length = 50)
    public String getWAC() {
        return WAC;
    }

    public void setWAC(String WAC) {
        this.WAC = WAC;
    }

    @Column(name = "foc", length = 50)
    public String getFOC() {
        return FOC;
    }

    public void setFOC(String FOC) {
        this.FOC = FOC;
    }

}
