package tenant.classes;
// Generated 7 Oct, 2016 4:05:52 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemMaster generated by hbm2java
 */
@Entity
@Table(name = "item_master", schema = "arete_tms"
)
public class ItemMaster implements java.io.Serializable {

    private Integer sno;
    private String orgId;
    private String userId;
    private String itemCategory;
    private String itemCode;
    private String itemName;
    private String itemDesc;
    private String itemUom;
    private String issueUom;
    private String status;     
    private String creationDate;
    private Date lastmodifiedDate;

    public ItemMaster() {
    }

    public ItemMaster(String orgId, String userId, String itemCategory, String itemCode, String itemName, String itemDesc, String itemUom, String issueUom, String status, String creationDate, Date lastmodifiedDate) {
        this.orgId = orgId;
        this.userId = userId;
        this.itemCategory = itemCategory;
        this.itemCode = itemCode;
        this.itemName = itemName;
        this.itemDesc = itemDesc;
        this.itemUom = itemUom;
        this.issueUom = issueUom;
        this.status = status;         
        this.creationDate = creationDate;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    public ItemMaster(Integer sno, String orgId, String userId, String itemCategory, String itemCode, String itemName, String itemDesc, String itemUom, String issueUom, String status, Date lastmodifiedDate) {
        this.sno = sno;
        this.orgId = orgId;
        this.userId = userId;
        this.itemCategory = itemCategory;
        this.itemCode = itemCode;
        this.itemName = itemName;
        this.itemDesc = itemDesc;
        this.itemUom = itemUom;
        this.issueUom = issueUom;
        this.status = status;         
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "SNO", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "ORG_ID", length = 50)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "USER_ID", length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "ITEM_CATEGORY", length = 50)
    public String getItemCategory() {
        return this.itemCategory;
    }

    public void setItemCategory(String itemCategory) {
        this.itemCategory = itemCategory;
    }

    @Column(name = "ITEM_CODE", length = 50)
    public String getItemCode() {
        return this.itemCode;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    @Column(name = "ITEM_NAME", length = 50)
    public String getItemName() {
        return this.itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    @Column(name = "ITEM_DESC", length = 120)
    public String getItemDesc() {
        return this.itemDesc;
    }

    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc;
    }

    @Column(name = "ITEM_UOM", length = 50)
    public String getItemUom() {
        return this.itemUom;
    }

    public void setItemUom(String itemUom) {
        this.itemUom = itemUom;
    }

    @Column(name = "ISSUE_UOM", length = 50)
    public String getIssueUom() {
        return this.issueUom;
    }

    public void setIssueUom(String issueUom) {
        this.issueUom = issueUom;
    }

    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
     
    @Column(name = "CREATION_DATE", length = 120)
    public String getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTMODIFIED_DATE", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

}
