package tenant.classes;
// Generated Sep 3, 2016 1:15:37 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LandLordDetails generated by hbm2java
 */
@Entity
@Table(name = "land_lord_details", schema = "arete_tms"
)    
public class LandLordDetails implements java.io.Serializable {

    private Integer sno;
    private String orgId;
    private String userId;
    private String landlordId;
    private String landlordCategory;
    private String landlordName;
    private String landlordContactno;
    private String landlordWorkContactno;
    private String landlordEmailid;
    private String crIdNo;
    private String personName1;
    private String contactNumber1;
    private String mailId1;
    private String personName2;
    private String contactNumber2;
    private String mailId2;
    private String status;
    private Date creationDate;
    private Date lastmodifiedDate;

    public LandLordDetails() {
    }

    public LandLordDetails(String orgId, String userId, String landlordId, String landlordCategory, String landlordName, String landlordContactno, String landlordWorkContactno, String landlordEmailid, String crIdNo, String personName1, String contactNumber1, String mailId1, String personName2, String contactNumber2, String mailId2, String status, Date creationDate, Date lastmodifiedDate) {
        this.orgId = orgId;
        this.userId = userId;
        this.landlordId = landlordId;
        this.landlordCategory = landlordCategory;
        this.landlordName = landlordName;
        this.landlordContactno = landlordContactno;
        this.landlordWorkContactno = landlordWorkContactno;
        this.landlordEmailid = landlordEmailid;
        this.crIdNo = crIdNo;
        this.personName1 = personName1;
        this.contactNumber1 = contactNumber1;
        this.mailId1 = mailId1;
        this.personName2 = personName2;
        this.contactNumber2 = contactNumber2;
        this.mailId2 = mailId2;
        this.status = status;
        this.creationDate = creationDate;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    public LandLordDetails(Integer sno, String orgId, String userId, String landlordId, String landlordCategory, String landlordName, String landlordContactno, String landlordWorkContactno, String landlordEmailid, String crIdNo, String personName1, String contactNumber1, String mailId1, String personName2, String contactNumber2, String mailId2, String status, Date creationDate, Date lastmodifiedDate) {
        this.sno = sno;
        this.orgId = orgId;
        this.userId = userId;
        this.landlordId = landlordId;
        this.landlordCategory = landlordCategory;
        this.landlordName = landlordName;
        this.landlordContactno = landlordContactno;
        this.landlordWorkContactno = landlordWorkContactno;
        this.landlordEmailid = landlordEmailid;
        this.crIdNo = crIdNo;
        this.personName1 = personName1;
        this.contactNumber1 = contactNumber1;
        this.mailId1 = mailId1;
        this.personName2 = personName2;
        this.contactNumber2 = contactNumber2;
        this.mailId2 = mailId2;
        this.status = status;
        this.creationDate = creationDate;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "sno", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "org_id", length = 50)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "user_id", length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "landlord_id", length = 50)
    public String getLandlordId() {
        return this.landlordId;
    }

    public void setLandlordId(String landlordId) {
        this.landlordId = landlordId;
    }

    @Column(name = "landlord_category", length = 60)
    public String getLandlordCategory() {
        return this.landlordCategory;
    }

    public void setLandlordCategory(String landlordCategory) {
        this.landlordCategory = landlordCategory;
    }

    @Column(name = "landlord_name", length = 60)
    public String getLandlordName() {
        return this.landlordName;
    }

    public void setLandlordName(String landlordName) {
        this.landlordName = landlordName;
    }

    @Column(name = "landlord_contactno", length = 15)
    public String getLandlordContactno() {
        return this.landlordContactno;
    }

    public void setLandlordContactno(String landlordContactno) {
        this.landlordContactno = landlordContactno;
    }

    @Column(name = "landlord_work_contactno", length = 15)
    public String getLandlordWorkContactno() {
        return this.landlordWorkContactno;
    }

    public void setLandlordWorkContactno(String landlordWorkContactno) {
        this.landlordWorkContactno = landlordWorkContactno;
    }

    @Column(name = "landlord_emailid", length = 50)
    public String getLandlordEmailid() {
        return this.landlordEmailid;
    }

    public void setLandlordEmailid(String landlordEmailid) {
        this.landlordEmailid = landlordEmailid;
    }

    @Column(name = "crid_no", length = 60)
    public String getCrIdNo() {
        return crIdNo;
    }

    public void setCrIdNo(String crIdNo) {
        this.crIdNo = crIdNo;
    }

    @Column(name = "person_name1", length = 60)
    public String getPersonName1() {
        return personName1;
    }

    public void setPersonName1(String personName1) {
        this.personName1 = personName1;
    }

    @Column(name = "contact_number1", length = 60)
    public String getContactNumber1() {
        return contactNumber1;
    }

    public void setContactNumber1(String contactNumber1) {
        this.contactNumber1 = contactNumber1;
    }

    @Column(name = "mail_id1", length = 60)
    public String getMailId1() {
        return mailId1;
    }

    public void setMailId1(String mailId1) {
        this.mailId1 = mailId1;
    }

    @Column(name = "person_name2", length = 60)
    public String getPersonName2() {
        return personName2;
    }

    public void setPersonName2(String personName2) {
        this.personName2 = personName2;
    }

    @Column(name = "contact_number2", length = 60)
    public String getContactNumber2() {
        return contactNumber2;
    }

    public void setContactNumber2(String contactNumber2) {
        this.contactNumber2 = contactNumber2;
    }

    @Column(name = "mail_id2", length = 60)
    public String getMailId2() {
        return mailId2;
    }

    public void setMailId2(String mailId2) {
        this.mailId2 = mailId2;
    }

    @Column(name = "status", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "creation_date", length = 60)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lastmodified_date", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

}
