package tenant.classes;
// Generated Oct 16, 2016 12:57:57 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MaterialIssue generated by hbm2java
 */
@Entity
@Table(name = "material_issue", schema = "arete_tms"
)
public class MaterialIssue implements java.io.Serializable {

    private Integer sno;
    private String orgId;
    private String userId;
    private String miNo;
    private Date miDate;
    private String assetName;
    private String subAssetname;
    private String tenantName;
    private String issuedBy;
    private String issuedTo;
    private String srNo;
    private String serviceCategory;
    private String itemCode;
    private String serviceItem;
    private String uom;
    private String reqQty;
    private String qty;
    private String priceum;
    private String totalPrice;
    private String recordstatus;
    private String remarks;
    private String appstatus;
    private String appremarks;
    private String attribute1;
    private String attribute2;
    private String attribute3;
    private String attribute4;
    private String attribute5;
    private String status;
    private Date creationDate;
    private Date lastmodifiedDate;

    public MaterialIssue() {
    }

    public MaterialIssue(String miNo) {
        this.miNo = miNo;
    }

    public MaterialIssue(String orgId, String userId, String miNo, Date miDate, String assetName, String subAssetname, String tenantName, String issuedBy, String issuedTo, String srNo, String serviceCategory, String itemCode, String serviceItem, String uom, String reqQty, String qty, String priceum, String totalPrice, String recordstatus, String remarks, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, String status, Date creationDate, Date lastmodifiedDate) {
        this.orgId = orgId;
        this.userId = userId;
        this.miNo = miNo;
        this.miDate = miDate;
        this.assetName = assetName;
        this.subAssetname = subAssetname;
        this.tenantName = tenantName;
        this.issuedBy = issuedBy;
        this.issuedTo = issuedTo;
        this.srNo = srNo;
        this.serviceCategory = serviceCategory;
        this.itemCode = itemCode;
        this.serviceItem = serviceItem;
        this.uom = uom;
        this.reqQty = reqQty;
        this.qty = qty;
        this.priceum = priceum;
        this.totalPrice = totalPrice;
        this.recordstatus = recordstatus;
        this.remarks = remarks;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.status = status;
        this.creationDate = creationDate;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "sno", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "org_id", length = 50)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "user_id", length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "mi_no", nullable = false, length = 30)
    public String getMiNo() {
        return this.miNo;
    }

    public void setMiNo(String miNo) {
        this.miNo = miNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "mi_date", length = 10)
    public Date getMiDate() {
        return this.miDate;
    }

    public void setMiDate(Date miDate) {
        this.miDate = miDate;
    }

    @Column(name = "asset_name", length = 60)
    public String getAssetName() {
        return this.assetName;
    }

    public void setAssetName(String assetName) {
        this.assetName = assetName;
    }

    @Column(name = "sub_assetname", length = 60)
    public String getSubAssetname() {
        return this.subAssetname;
    }

    public void setSubAssetname(String subAssetname) {
        this.subAssetname = subAssetname;
    }

    @Column(name = "tenant_name", length = 60)
    public String getTenantName() {
        return this.tenantName;
    }

    public void setTenantName(String tenantName) {
        this.tenantName = tenantName;
    }

    @Column(name = "issued_by", length = 60)
    public String getIssuedBy() {
        return this.issuedBy;
    }

    public void setIssuedBy(String issuedBy) {
        this.issuedBy = issuedBy;
    }

    @Column(name = "issued_to", length = 60)
    public String getIssuedTo() {
        return this.issuedTo;
    }

    public void setIssuedTo(String issuedTo) {
        this.issuedTo = issuedTo;
    }

    @Column(name = "sr_no", length = 60)
    public String getSrNo() {
        return this.srNo;
    }

    public void setSrNo(String srNo) {
        this.srNo = srNo;
    }

    @Column(name = "service_category", length = 60)
    public String getServiceCategory() {
        return this.serviceCategory;
    }

    public void setServiceCategory(String serviceCategory) {
        this.serviceCategory = serviceCategory;
    }

    @Column(name = "item_code", length = 60)
    public String getItemCode() {
        return this.itemCode;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    @Column(name = "service_item", length = 60)
    public String getServiceItem() {
        return this.serviceItem;
    }

    public void setServiceItem(String serviceItem) {
        this.serviceItem = serviceItem;
    }

    @Column(name = "uom", length = 50)
    public String getUom() {
        return this.uom;
    }

    public void setUom(String uom) {
        this.uom = uom;
    }

    @Column(name = "req_qty", length = 60)
    public String getReqQty() {
        return reqQty;
    }

    public void setReqQty(String reqQty) {
        this.reqQty = reqQty;
    }

    @Column(name = "qty", length = 60)
    public String getQty() {
        return this.qty;
    }

    public void setQty(String qty) {
        this.qty = qty;
    }

    @Column(name = "total_um", length = 60)
    public String getPriceum() {
        return priceum;
    }

    public void setPriceum(String priceum) {
        this.priceum = priceum;
    }

    @Column(name = "total_price", length = 60)
    public String getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(String totalPrice) {
        this.totalPrice = totalPrice;
    }

    @Column(name = "recordstatus", length = 60)
    public String getRecordstatus() {
        return this.recordstatus;
    }

    public void setRecordstatus(String recordstatus) {
        this.recordstatus = recordstatus;
    }

    @Column(name = "remarks", length = 300)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "appremarks", length = 300)
    public String getAppremarks() {
        return appremarks;
    }

    public void setAppremarks(String appremarks) {
        this.appremarks = appremarks;
    }

    @Column(name = "appstatus", length = 50)
    public String getAppstatus() {
        return appstatus;
    }

    public void setAppstatus(String appstatus) {
        this.appstatus = appstatus;
    }

    @Column(name = "attribute1", length = 50)
    public String getAttribute1() {
        return this.attribute1;
    }

    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    @Column(name = "attribute2", length = 50)
    public String getAttribute2() {
        return this.attribute2;
    }

    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    @Column(name = "attribute3", length = 50)
    public String getAttribute3() {
        return this.attribute3;
    }

    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    @Column(name = "attribute4", length = 300)
    public String getAttribute4() {
        return this.attribute4;
    }

    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    @Column(name = "attribute5", length = 300)
    public String getAttribute5() {
        return this.attribute5;
    }

    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    @Column(name = "status", length = 60)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "creation_date", length = 19)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lastmodified_date", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

}
