package tenant.classes;
// Generated 7 Oct, 2016 10:15:08 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MinutesOfMeeting generated by hbm2java
 */
@Entity
@Table(name = "minutes_of_meeting", schema = "arete_tms"
)
public class MinutesOfMeeting implements java.io.Serializable {

    private Integer sno;
    private String orgId;
    private String userId;
    private String momCode;
    private String createdBy;
    private Date date;
    private String meetingTime;
    private String agenda;
    private String attendedMember;
    private String designation;
    private String discussed;
    private String meetingOutput;
    private String closedBy;
    private String attribute1;
    private String attribute2;
    private String attribute3;
    private String attribute4;
    private String attribute5;
    private Date creationDate;
    private String recordStatus;
    private String status;
    private Date lastmodefiedDate;

    public MinutesOfMeeting() {
    }

    public MinutesOfMeeting(String userId) {
        this.userId = userId;
    }

    public MinutesOfMeeting(String orgId, String userId, String momCode, String createdBy, Date date, String meetingTime, String agenda, String discussed, String meetingOutput, String attendedMember, String designation, String closedBy, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, Date creationDate, String recordStatus, String status, Date lastmodefiedDate) {
        this.orgId = orgId;
        this.userId = userId;
        this.momCode = momCode;
        this.createdBy = createdBy;
        this.date = date;
        this.meetingTime = meetingTime;
        this.agenda = agenda;
        this.discussed = discussed;
        this.meetingOutput = meetingOutput;
        this.attendedMember = attendedMember;
        this.designation = designation;

        this.closedBy = closedBy;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.creationDate = creationDate;
        this.recordStatus = recordStatus;
        this.status = status;
        this.lastmodefiedDate = lastmodefiedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "sno", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "org_Id", length = 20)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "user_Id", nullable = false, length = 20)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "MOM_Code", length = 50)
    public String getMomCode() {
        return this.momCode;
    }

    public void setMomCode(String momCode) {
        this.momCode = momCode;
    }

    @Column(name = "Created_BY", length = 50)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Date", length = 19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "Meeting_Time", length = 50)
    public String getMeetingTime() {
        return this.meetingTime;
    }

    public void setMeetingTime(String meetingTime) {
        this.meetingTime = meetingTime;
    }

    @Column(name = "Agenda", length = 500)
    public String getAgenda() {
        return this.agenda;
    }

    public void setAgenda(String agenda) {
        this.agenda = agenda;
    }

    @Column(name = "Attended_Member", length = 50)
    public String getAttendedMember() {
        return this.attendedMember;
    }

    public void setAttendedMember(String attendedMember) {
        this.attendedMember = attendedMember;
    }

    @Column(name = "Designation", length = 50)
    public String getDesignation() {
        return this.designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

    @Column(name = "Discussed", length = 500)
    public String getDiscussed() {
        return this.discussed;
    }

    public void setDiscussed(String discussed) {
        this.discussed = discussed;
    }

    @Column(name = "Meeting_Output", length = 500)
    public String getMeetingOutput() {
        return this.meetingOutput;
    }

    public void setMeetingOutput(String meetingOutput) {
        this.meetingOutput = meetingOutput;
    }

    @Column(name = "closed_By", length = 50)
    public String getClosedBy() {
        return this.closedBy;
    }

    public void setClosedBy(String closedBy) {
        this.closedBy = closedBy;
    }

    @Column(name = "Attribute1", length = 50)
    public String getAttribute1() {
        return this.attribute1;
    }

    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    @Column(name = "Attribute2", length = 50)
    public String getAttribute2() {
        return this.attribute2;
    }

    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    @Column(name = "Attribute3", length = 50)
    public String getAttribute3() {
        return this.attribute3;
    }

    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    @Column(name = "Attribute4")
    public String getAttribute4() {
        return this.attribute4;
    }

    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    @Column(name = "Attribute5")
    public String getAttribute5() {
        return this.attribute5;
    }

    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Creation_date", length = 19)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Column(name = "Record_Status", length = 50)
    public String getRecordStatus() {
        return this.recordStatus;
    }

    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    @Column(name = "Status", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Lastmodefied_Date", length = 19)
    public Date getLastmodefiedDate() {
        return this.lastmodefiedDate;
    }

    public void setLastmodefiedDate(Date lastmodefiedDate) {
        this.lastmodefiedDate = lastmodefiedDate;
    }

}
