package tenant.classes;
// Generated 12 Oct, 2016 12:08:15 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MonthlyWorkSheet generated by hbm2java
 */
@Entity
@Table(name = "monthly_work_sheet", schema = "arete_tms"
)
public class MonthlyWorkSheet implements java.io.Serializable {

    private Integer sno;
    private String orgId;
    private String userId;
    private String mwsCode;
    private String empName;
    private String empCode;
    private String year;
    private String month;
    private String date;
    private String leadName;
    private String source;
    private String remarks;
    private String followUp;
    private String workingWith;
    private String attribute1;
    private String attribute2;
    private String attribute3;
    private String attribute4;
    private String attribute5;
    private Date creationDate;
    private String recordStatus;
    private String status;
    private Date lastmodefiedDate;

    public MonthlyWorkSheet() {
    }

    public MonthlyWorkSheet(String userId) {
        this.userId = userId;
    }

    public MonthlyWorkSheet(String orgId, String userId, String mwsCode, String empName, String empCode, String year, String month, String date, String leadName, String source, String remarks, String followUp, String workingWith, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, Date creationDate, String recordStatus, String status, Date lastmodefiedDate) {
        this.orgId = orgId;
        this.userId = userId;
        this.mwsCode = mwsCode;
        this.empName = empName;
        this.empCode = empCode;
        this.year = year;
        this.month = month;
        this.date = date;
        this.leadName = leadName;
        this.source = source;
        this.remarks = remarks;
        this.followUp = followUp;
        this.workingWith = workingWith;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.creationDate = creationDate;
        this.recordStatus = recordStatus;
        this.status = status;
        this.lastmodefiedDate = lastmodefiedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "sno", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "org_Id", length = 20)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "user_Id", nullable = false, length = 20)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "MWS_Code", length = 50)
    public String getMwsCode() {
        return this.mwsCode;
    }

    public void setMwsCode(String mwsCode) {
        this.mwsCode = mwsCode;
    }

    @Column(name = "Emp_Name", length = 50)
    public String getEmpName() {
        return this.empName;
    }

    public void setEmpName(String empName) {
        this.empName = empName;
    }

    @Column(name = "Emp_Code", length = 50)
    public String getEmpCode() {
        return this.empCode;
    }

    public void setEmpCode(String empCode) {
        this.empCode = empCode;
    }

    @Column(name = "Year", length = 50)
    public String getYear() {
        return this.year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    @Column(name = "Month", length = 50)
    public String getMonth() {
        return this.month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    @Column(name = "Date", length = 50)
    public String getDate() {
        return this.date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    @Column(name = "Lead_Name", length = 50)
    public String getLeadName() {
        return this.leadName;
    }

    public void setLeadName(String leadName) {
        this.leadName = leadName;
    }

    @Column(name = "Source", length = 50)
    public String getSource() {
        return this.source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    @Column(name = "Remarks", length = 50)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "FollowUp", length = 50)
    public String getFollowUp() {
        return this.followUp;
    }

    public void setFollowUp(String followUp) {
        this.followUp = followUp;
    }

    @Column(name = "Working_With", length = 50)
    public String getWorkingWith() {
        return this.workingWith;
    }

    public void setWorkingWith(String workingWith) {
        this.workingWith = workingWith;
    }

    @Column(name = "Attribute1", length = 50)
    public String getAttribute1() {
        return this.attribute1;
    }

    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    @Column(name = "Attribute2", length = 50)
    public String getAttribute2() {
        return this.attribute2;
    }

    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    @Column(name = "Attribute3", length = 50)
    public String getAttribute3() {
        return this.attribute3;
    }

    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    @Column(name = "Attribute4")
    public String getAttribute4() {
        return this.attribute4;
    }

    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    @Column(name = "Attribute5")
    public String getAttribute5() {
        return this.attribute5;
    }

    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Creation_date", length = 19)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Column(name = "Record_Status", length = 50)
    public String getRecordStatus() {
        return this.recordStatus;
    }

    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    @Column(name = "Status", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Lastmodefied_Date", length = 19)
    public Date getLastmodefiedDate() {
        return this.lastmodefiedDate;
    }

    public void setLastmodefiedDate(Date lastmodefiedDate) {
        this.lastmodefiedDate = lastmodefiedDate;
    }

}
