package tenant.classes;
// Generated 30 May, 2016 12:22:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrgGroup generated by hbm2java
 */
@Entity
@Table(name = "org_group", schema = "arete_tms"
)
public class OrgGroup implements java.io.Serializable {

    private Integer sno;
    private String groupCode;
    private String groupName;
    private String groupDesc;
    private String groupAddress;
    private String status;
    private Date lastmodifiedDate;

    public OrgGroup() {
    }

    public OrgGroup(String groupCode, String groupName, String groupDesc, String groupAddress, String status, java.sql.Timestamp lastmodifiedDate) {
        this.groupCode = groupCode;
        this.groupName = groupName;
        this.groupDesc = groupDesc;
        this.groupAddress = groupAddress;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    public OrgGroup(Integer sno, String groupCode, String groupName, String groupDesc, String groupAddress, String status, java.sql.Timestamp lastmodifiedDate) {
        this.sno = sno;
        this.groupCode = groupCode;
        this.groupName = groupName;
        this.groupDesc = groupDesc;
        this.groupAddress = groupAddress;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "SNO", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "GROUP_CODE", length = 50)
    public String getGroupCode() {
        return this.groupCode;
    }

    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    @Column(name = "GROUP_NAME", length = 100)
    public String getGroupName() {
        return this.groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    @Column(name = "GROUP_DESC", length = 100)
    public String getGroupDesc() {
        return this.groupDesc;
    }

    public void setGroupDesc(String groupDesc) {
        this.groupDesc = groupDesc;
    }

    @Column(name = "GROUP_ADDRESS", length = 100)
    public String getGroupAddress() {
        return this.groupAddress;
    }

    public void setGroupAddress(String groupAddress) {
        this.groupAddress = groupAddress;
    }

    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTMODIFIED_DATE", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

}
