package tenant.classes;
// Generated 18 Oct, 2016 7:28:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchAttach generated by hbm2java
 */
@Entity
@Table(name = "purch_attach", schema = "arete_tms"
)
public class PurchAttach implements java.io.Serializable {

    private Integer sno;
    private byte[] content;
    private String contentType;
    private String poNo;
    private Date creationDate;
    private String filename;
    private Date lastmodifiedDate;
    private String orgId;
    private String status;
    private String userId;

    public PurchAttach() {
    }

    public PurchAttach(byte[] content, String contentType, String poNo, Date creationDate, String filename, Date lastmodifiedDate, String orgId, String status, String userId) {
        this.content = content;
        this.contentType = contentType;
        this.poNo = poNo;
        this.creationDate = creationDate;
        this.filename = filename;
        this.lastmodifiedDate = lastmodifiedDate;
        this.orgId = orgId;
        this.status = status;
        this.userId = userId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "SNO", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "CONTENT", columnDefinition = "MEDIUMBLOB")
    public byte[] getContent() {
        return this.content;
    }

    public void setContent(byte[] content) {
        this.content = content;
    }

    @Column(name = "CONTENT_TYPE", length = 100)
    public String getContentType() {
        return this.contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    @Column(name = "PO_NO", length = 30)
    public String getPoNo() {
        return this.poNo;
    }

    public void setPoNo(String poNo) {
        this.poNo = poNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATION_DATE", length = 19)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Column(name = "FILENAME", length = 100)
    public String getFilename() {
        return this.filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTMODIFIED_DATE", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Column(name = "ORG_ID", length = 11)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "USER_ID", length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

}
