/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tenant.classes;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchaseAttachments generated by hbm2java
 */
@Entity
@Table(name = "purchase_attachments", schema = "arete_tms"
)
public class PurchaseAttachments implements java.io.Serializable {

    private Integer SNo;
    private String userId;
    private String orgId;
    private String refNo;
    private String fileName;
    private byte[] content;
    private Date created;
    private String status;
    private java.sql.Timestamp lastmodifiedDate;

    public PurchaseAttachments() {
    }

    public PurchaseAttachments(String userId, String orgId, String refNo, String fileName, byte[] content, Date created, String status, java.sql.Timestamp lastmodifiedDate) {
        this.userId = userId;
        this.orgId = orgId;
        this.refNo = refNo;
        this.fileName = fileName;
        this.content = content;
        this.created = created;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "purchaseDoc_id_seq")
    @SequenceGenerator(name = "purchaseDoc_id_seq", sequenceName = "purchaseDoc_seq", allocationSize = 1)
    @Column(name = "s_no", unique = true, nullable = false, precision = 38, scale = 0)
    public Integer getSNo() {
        return this.SNo;
    }

    public void setSNo(Integer SNo) {
        this.SNo = SNo;
    }

    @Column(name = "user_id", nullable = false, length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "org_id", nullable = false, length = 50)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "ref_no", nullable = false, length = 100)
    public String getRefNo() {
        return this.refNo;
    }

    public void setRefNo(String refNo) {
        this.refNo = refNo;
    }

    @Column(name = "file_name", length = 100)
    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    @Column(name = "content", columnDefinition = "blob")
    public byte[] getContent() {
        return this.content;
    }

    public void setContent(byte[] content) {
        this.content = content;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "created", length = 7)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name = "status", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "lastmodified_date", columnDefinition = "TIMESTAMP")
    public java.sql.Timestamp getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(java.sql.Timestamp lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

}
