package tenant.classes;
// Generated 5 Oct, 2016 5:17:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchRequisition generated by hbm2java
 */
@Entity
@Table(name = "purch_requisition", schema = "arete_tms"
)
public class PurchRequisition implements java.io.Serializable {

    private Integer sno;
    private String orgId;
    private String userId;
    private String requisitionNo;
    private Date requiOnDate;
    private String assetCategory;
    private String subAssetCategory;
    private String itemCode;
    private Date requiredDate;
    private String quantity;
    private String deliveryLocation;
    private String paymentTerms;
    private String remarks;
    private String recordStatus;
    private String approvar1Remark;
    private String approvar2Remark;
    private String approvar3Remark;
    private String attribute1;
    private String attribute2;
    private String attribute3;
    private String attribute4;
    private String attribute5;
    private String status;
    private Date lastmodifiedDate;
    private String approvalLevel;

    public PurchRequisition() {
    }

    public PurchRequisition(String requisitionNo) {

        this.requisitionNo = requisitionNo;
    }

    public PurchRequisition(String orgId, String userId, String requisitionNo, Date requiOnDate, String assetCategory, String subAssetCategory, String itemCode, Date requiredDate, String quantity, String deliveryLocation, String paymentTerms, String remarks, String recordStatus, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, String status, Date lastmodifiedDate, String approvalLevel) {
        this.orgId = orgId;
        this.userId = userId;
        this.requisitionNo = requisitionNo;
        this.requiOnDate = requiOnDate;
        this.assetCategory = assetCategory;
        this.subAssetCategory = subAssetCategory;
        this.itemCode = itemCode;
        this.requiredDate = requiredDate;
        this.quantity = quantity;
        this.deliveryLocation = deliveryLocation;
        this.paymentTerms = paymentTerms;
        this.remarks = remarks;
        this.recordStatus = recordStatus;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.approvalLevel = approvalLevel;
    }

    public PurchRequisition(Integer sno, String orgId, String userId, String requisitionNo, Date requiOnDate, String assetCategory, String subAssetCategory, Date requiredDate, String quantity, String deliveryLocation, String paymentTerms, String remarks, String recordStatus, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, String status, Date lastmodifiedDate, String approvalLevel) {
        this.sno = sno;
        this.orgId = orgId;
        this.userId = userId;
        this.requisitionNo = requisitionNo;
        this.requiOnDate = requiOnDate;
        this.assetCategory = assetCategory;
        this.subAssetCategory = subAssetCategory;
        this.requiredDate = requiredDate;
        this.quantity = quantity;
        this.deliveryLocation = deliveryLocation;
        this.paymentTerms = paymentTerms;
        this.remarks = remarks;
        this.recordStatus = recordStatus;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.approvalLevel = approvalLevel;
    }

    public PurchRequisition(Integer sno, String orgId, String userId, String requisitionNo, Date requiOnDate, String assetCategory, String subAssetCategory, String itemCode, Date requiredDate, String quantity, String deliveryLocation, String paymentTerms, String remarks, String recordStatus, String status, Date lastmodifiedDate, String approvalLevel) {
        this.sno = sno;
        this.orgId = orgId;
        this.userId = userId;
        this.requisitionNo = requisitionNo;
        this.requiOnDate = requiOnDate;
        this.assetCategory = assetCategory;
        this.subAssetCategory = subAssetCategory;
        this.itemCode = itemCode;
        this.requiredDate = requiredDate;
        this.quantity = quantity;
        this.deliveryLocation = deliveryLocation;
        this.paymentTerms = paymentTerms;
        this.remarks = remarks;
        this.recordStatus = recordStatus;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.approvalLevel = approvalLevel;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "SNO", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "ORG_ID", length = 50)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "USER_ID", length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "REQUISITION_NO", nullable = false, length = 50)
    public String getRequisitionNo() {
        return this.requisitionNo;
    }

    public void setRequisitionNo(String requisitionNo) {
        this.requisitionNo = requisitionNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "REQUI_ON_DATE", length = 10)
    public Date getRequiOnDate() {
        return this.requiOnDate;
    }

    public void setRequiOnDate(Date requiOnDate) {
        this.requiOnDate = requiOnDate;
    }

    @Column(name = "ASSET_CATEGORY", length = 50)
    public String getAssetCategory() {
        return this.assetCategory;
    }

    public void setAssetCategory(String assetCategory) {
        this.assetCategory = assetCategory;
    }

    @Column(name = "SUB_ASSET_CATEGORY", length = 50)
    public String getSubAssetCategory() {
        return this.subAssetCategory;
    }

    public void setSubAssetCategory(String subAssetCategory) {
        this.subAssetCategory = subAssetCategory;
    }

    @Column(name = "ITEM_CODE", length = 50)
    public String getItemCode() {
        return this.itemCode;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "REQUIRED_DATE", length = 10)
    public Date getRequiredDate() {
        return this.requiredDate;
    }

    public void setRequiredDate(Date requiredDate) {
        this.requiredDate = requiredDate;
    }

    @Column(name = "QUANTITY", length = 70)
    public String getQuantity() {
        return this.quantity;
    }

    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    @Column(name = "DELIVERY_LOCATION", length = 300)
    public String getDeliveryLocation() {
        return this.deliveryLocation;
    }

    public void setDeliveryLocation(String deliveryLocation) {
        this.deliveryLocation = deliveryLocation;
    }

    @Column(name = "PAYMENT_TERMS", length = 300)
    public String getPaymentTerms() {
        return this.paymentTerms;
    }

    public void setPaymentTerms(String paymentTerms) {
        this.paymentTerms = paymentTerms;
    }

    @Column(name = "REMARKS")
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "RECORD_STATUS", length = 50)
    public String getRecordStatus() {
        return this.recordStatus;
    }

    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    @Column(name = "APPROVER1_REMARK")
    public String getApprovar1Remark() {
        return approvar1Remark;
    }

    public void setApprovar1Remark(String approvar1Remark) {
        this.approvar1Remark = approvar1Remark;
    }

    @Column(name = "APPROVER2_REMARK")
    public String getApprovar2Remark() {
        return approvar2Remark;
    }

    public void setApprovar2Remark(String approvar2Remark) {
        this.approvar2Remark = approvar2Remark;
    }

    @Column(name = "APPROVER3_REMARK")
    public String getApprovar3Remark() {
        return approvar3Remark;
    }

    public void setApprovar3Remark(String approvar3Remark) {
        this.approvar3Remark = approvar3Remark;
    }

    @Column(name = "REJECTOR_REMARK", length = 300)
    public String getAttribute1() {
        return this.attribute1;
    }

    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    @Column(name = "ATTRIBUTE2", length = 100)
    public String getAttribute2() {
        return this.attribute2;
    }

    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    @Column(name = "ATTRIBUTE3", length = 100)
    public String getAttribute3() {
        return this.attribute3;
    }

    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    @Column(name = "ATTRIBUTE4")
    public String getAttribute4() {
        return this.attribute4;
    }

    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    @Column(name = "ATTRIBUTE5")
    public String getAttribute5() {
        return this.attribute5;
    }

    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTMODIFIED_DATE", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Column(name = "approval_level", length = 50)
    public String getApprovalLevel() {
        return approvalLevel;
    }

    public void setApprovalLevel(String approvalLevel) {
        this.approvalLevel = approvalLevel;
    }
    
    

}
