package tenant.classes;
// Generated Oct 12, 2016 5:11:25 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchaseOrder generated by hbm2java
 */
@Entity
@Table(name = "purchase_order", schema = "arete_tms"
)
public class PurchaseOrder implements java.io.Serializable {

    private Integer SNo;
    private String userId;
    private String orgId;
    private String purchaseOrderNo;
    private String purchaseType;
    
    
    private String supplierName;
    private String supplierAddress;
    private String supplierEmail;
    private String supplierContactNumber;
    private String supplierCode;
    
   private String contactPersonName;
   private String contactAddress;
   private String contactNumber;
   private String contactEmail;
   private String contactCode;
   
   private String deliveryName;
   private String deliveryAddress;
   private String deliveryContact;
   private String deliveryEmail;
   private String deliveryCode;
   
   private String paymentTerms;
    private String deliveryTerms;
    private String warrentyTerms;
    
    
    private Date expectedDeliveryDate;
    
    private String recordStatus;
    
     private String status;
    private Date lastmodifiedDate;
    
    
    
    
    
    private String divisionName;
    private String department;
    
    private String projectCode;
    private String projectName;
    
    private Date purchaseOrderDate;
    private String prNo;
    private Date prDate;
    private String preparedBy;
    private String quotationNo;
    private Date quotationDate;
    private String importLocal;
    private String currency;
    private String billToLocation;
    private String shipToLocation;
    private String itemCategory;
    private String itemSubCategory;
    private String itemCode;
    private String itemName;
    private String description;
    private String uom;
    private Double qty;
    private Double unitPrice;
    private Double discount;
    private Double totalValue;
    private Double grandTotal;
    private Date requiredDate;
    private String warrantyPeriod;
    
    private String poNote;
    
    private String approvalStatus = "Initial";
    
    
    private Integer prSno;
    private Integer qtSno;
    private String remarks;
    private String purMngName;
    private String purMngRemarks;
    private Date purMngDate;
    private String gmName;
    private String gmRemarks;
    private Date gmDate;
    private String fmName;
    private String fmRemarks;
    private Date fmDate;
   
    private String poRevNo;
    private String emailStatus = "Send Email";
    private Double lumsumDiscount;
    private String invoiceStatus;
    private String costcenterCode;
    private String costcenterDesc;
    private String uom1;
    private Double uom1Price;
    private String uom2;
    private Double uom2Price;
    private String uom3;
    private Double uom3Price;
    private String assetCategory;
    private String subAssetCategory;

    public PurchaseOrder() {
    }

    public PurchaseOrder(String userId, String orgId, String purchaseOrderNo, String purchaseType, String supplierName, String supplierAddress,
            String supplierEmail, String supplierContactNumber, String supplierCode, String contactPersonName, String contactAddress, 
            String contactNumber, String contactEmail, String contactCode, String deliveryName, String deliveryAddress, String deliveryContact,
            String deliveryEmail, String deliveryCode, String paymentTerms, String deliveryTerms,String warrentyTerms, Date expectedDeliveryDate,
            String recordStatus, String status, Date lastmodifiedDate) {
        this.userId = userId;
        this.orgId = orgId;
        this.purchaseOrderNo = purchaseOrderNo;
        this.purchaseType = purchaseType;
        this.supplierName = supplierName;
        this.supplierAddress = supplierAddress;
        this.supplierEmail = supplierEmail;
        this.supplierContactNumber = supplierContactNumber;
        this.supplierCode = supplierCode;
        this.contactPersonName = contactPersonName;
        this.contactAddress = contactAddress;
        this.contactNumber = contactNumber;
        this.contactEmail = contactEmail;
        this.contactCode = contactCode;
        this.deliveryName = deliveryName;
        this.deliveryAddress = deliveryAddress;
        this.deliveryContact = deliveryContact;
        this.deliveryEmail = deliveryEmail;
        this.deliveryCode = deliveryCode;
        this.paymentTerms = paymentTerms;
        this.deliveryTerms = deliveryTerms;
        this.warrentyTerms = warrentyTerms;
        this.expectedDeliveryDate = expectedDeliveryDate;
        this.recordStatus = recordStatus;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    public PurchaseOrder(Integer SNo, String userId, String orgId, String purchaseOrderNo, String purchaseType, String supplierName, String supplierAddress, String supplierEmail, String supplierContactNumber, String supplierCode, String contactPersonName, String contactAddress, String contactNumber, String contactEmail, String contactCode, String deliveryName, String deliveryAddress, String deliveryContact, String deliveryEmail, String deliveryCode, String paymentTerms, String deliveryTerms,String warrentyTerms, Date expectedDeliveryDate, String recordStatus, String status, Date lastmodifiedDate) {
        this.SNo = SNo;
        this.userId = userId;
        this.orgId = orgId;
        this.purchaseOrderNo = purchaseOrderNo;
        this.purchaseType = purchaseType;
        this.supplierName = supplierName;
        this.supplierAddress = supplierAddress;
        this.supplierEmail = supplierEmail;
        this.supplierContactNumber = supplierContactNumber;
        this.supplierCode = supplierCode;
        this.contactPersonName = contactPersonName;
        this.contactAddress = contactAddress;
        this.contactNumber = contactNumber;
        this.contactEmail = contactEmail;
        this.contactCode = contactCode;
        this.deliveryName = deliveryName;
        this.deliveryAddress = deliveryAddress;
        this.deliveryContact = deliveryContact;
        this.deliveryEmail = deliveryEmail;
        this.deliveryCode = deliveryCode;
        this.paymentTerms = paymentTerms;
        this.deliveryTerms = deliveryTerms;
        this.warrentyTerms = warrentyTerms;
        this.expectedDeliveryDate = expectedDeliveryDate;
        this.recordStatus = recordStatus;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }
    
    
    

//    public PurchaseOrder(String userId, String orgId, String divisionName, String department, String purchaseType, String projectCode, String projectName, String purchaseOrderNo, Date purchaseOrderDate, String prNo, Date prDate, String preparedBy, String quotationNo, Date quotationDate, String importLocal, String currency, String billToLocation, String shipToLocation, String itemCategory, String itemSubCategory, String itemCode, String itemName, String description, String uom, Double qty, Double unitPrice, Double discount, Double totalValue, Double grandTotal, Date requiredDate, String warrantyPeriod, String paymentTerms, String deliveryTerms, String poNote, String recordStatus, String supplierCode, String supplierName, String supplierAddress, String supplierEmail, Integer prSno, Integer qtSno, String remarks, String status, Date lastmodifiedDate, Double lumsumDiscount, String costcenterCode, String costcenterDesc,
//            String uom1,
//            Double uom1Price,
//            String uom2,
//            Double uom2Price,
//            String uom3,
//            Double uom3Price) {
//        this.userId = userId;
//        this.orgId = orgId;
//        this.divisionName = divisionName;
//        this.department = department;
//        this.purchaseType = purchaseType;
//        this.projectCode = projectCode;
//        this.projectName = projectName;
//        this.purchaseOrderNo = purchaseOrderNo;
//        this.purchaseOrderDate = purchaseOrderDate;
//        this.prNo = prNo;
//        this.prDate = prDate;
//        this.preparedBy = preparedBy;
//        this.quotationNo = quotationNo;
//        this.quotationDate = quotationDate;
//        this.importLocal = importLocal;
//        this.currency = currency;
//        this.billToLocation = billToLocation;
//        this.shipToLocation = shipToLocation;
//        this.itemCategory = itemCategory;
//        this.itemSubCategory = itemSubCategory;
//        this.itemCode = itemCode;
//        this.itemName = itemName;
//        this.description = description;
//        this.uom = uom;
//        this.qty = qty;
//        this.unitPrice = unitPrice;
//        this.discount = discount;
//        this.totalValue = totalValue;
//        this.grandTotal = grandTotal;
//        this.requiredDate = requiredDate;
//        this.warrantyPeriod = warrantyPeriod;
//        this.paymentTerms = paymentTerms;
//        this.deliveryTerms = deliveryTerms;
//        this.poNote = poNote;
//        this.recordStatus = recordStatus;
//        this.supplierCode = supplierCode;
//        this.supplierName = supplierName;
//        this.supplierAddress = supplierAddress;
//        this.supplierEmail = supplierEmail;
//        this.prSno = prSno;
//        this.qtSno = qtSno;
//        this.remarks = remarks;
//        this.status = status;
//        this.lastmodifiedDate = lastmodifiedDate;
//        this.lumsumDiscount = lumsumDiscount;
//        this.costcenterCode = costcenterCode;
//        this.costcenterDesc = costcenterDesc;
//        this.uom1 = uom1;
//        this.uom1Price = uom1Price;
//        this.uom2 = uom2;
//        this.uom2Price = uom2Price;
//        this.uom3 = uom3;
//        this.uom3Price = uom3Price;
//    }

//    public PurchaseOrder(Integer SNo, String userId, String orgId, String divisionName, String department, String purchaseType, String projectCode, String projectName, String purchaseOrderNo, Date purchaseOrderDate, String prNo, Date prDate, String preparedBy, String quotationNo, Date quotationDate, String importLocal, String currency, String billToLocation, String shipToLocation, String itemCategory, String itemSubCategory, String itemCode, String itemName, String description, String uom, Double qty, Double unitPrice, Double discount, Double totalValue, Double grandTotal, Date requiredDate, String warrantyPeriod, String paymentTerms, String deliveryTerms, String poNote, String recordStatus, String supplierCode, String supplierName, String supplierAddress, String supplierEmail, Integer prSno, Integer qtSno, String remarks, String status, Date lastmodifiedDate) {
//        this.SNo = SNo;
//        this.userId = userId;
//        this.orgId = orgId;
//        this.divisionName = divisionName;
//        this.department = department;
//        this.purchaseType = purchaseType;
//        this.projectCode = projectCode;
//        this.projectName = projectName;
//        this.purchaseOrderNo = purchaseOrderNo;
//        this.purchaseOrderDate = purchaseOrderDate;
//        this.prNo = prNo;
//        this.prDate = prDate;
//        this.preparedBy = preparedBy;
//        this.quotationNo = quotationNo;
//        this.quotationDate = quotationDate;
//        this.importLocal = importLocal;
//        this.currency = currency;
//        this.billToLocation = billToLocation;
//        this.shipToLocation = shipToLocation;
//        this.itemCategory = itemCategory;
//        this.itemSubCategory = itemSubCategory;
//        this.itemCode = itemCode;
//        this.itemName = itemName;
//        this.description = description;
//        this.uom = uom;
//        this.qty = qty;
//        this.unitPrice = unitPrice;
//        this.discount = discount;
//        this.totalValue = totalValue;
//        this.grandTotal = grandTotal;
//        this.requiredDate = requiredDate;
//        this.warrantyPeriod = warrantyPeriod;
//        this.paymentTerms = paymentTerms;
//        this.deliveryTerms = deliveryTerms;
//        this.poNote = poNote;
//        this.recordStatus = recordStatus;
//        this.supplierCode = supplierCode;
//        this.supplierName = supplierName;
//        this.supplierAddress = supplierAddress;
//        this.supplierEmail = supplierEmail;
//        this.prSno = prSno;
//        this.qtSno = qtSno;
//        this.remarks = remarks;
//        this.status = status;
//        this.lastmodifiedDate = lastmodifiedDate;
//        
//    }

//    public PurchaseOrder(String userId, String orgId, String divisionName, String assetCategory,String subAssetCategory, String department, String purchaseType, String projectCode, String projectName, String purchaseOrderNo, Date purchaseOrderDate, String preparedBy, String importLocal, String currency, String billToLocation, String shipToLocation, String itemCategory, String itemSubCategory, String itemCode, String itemName, String description, String uom, Double qty, Double unitPrice, Double discount, Double totalValue, Double grandTotal, Date requiredDate, String warrantyPeriod, String paymentTerms, String deliveryTerms, String poNote, String recordStatus, String supplierCode, String supplierName, String supplierAddress, String supplierEmail, String remarks, String status, Date lastmodifiedDate, Double lumsumDiscount, String costcenterCode, String costcenterDesc,
//            String uom1,
//            Double uom1Price,
//            String uom2,
//            Double uom2Price,
//            String uom3,
//            Double uom3Price
//    ) {
//        this.userId = userId;
//        this.orgId = orgId;
//        this.divisionName = divisionName;
//        this.department = department;
//        this.purchaseType = purchaseType;
//        this.projectCode = projectCode;
//        this.projectName = projectName;
//        this.purchaseOrderNo = purchaseOrderNo;
//        this.purchaseOrderDate = purchaseOrderDate;
//        this.preparedBy = preparedBy;
//        this.importLocal = importLocal;
//        this.currency = currency;
//        this.billToLocation = billToLocation;
//        this.shipToLocation = shipToLocation;
//        this.itemCategory = itemCategory;
//        this.itemSubCategory = itemSubCategory;
//        this.itemCode = itemCode;
//        this.itemName = itemName;
//        this.description = description;
//        this.uom = uom;
//        this.qty = qty;
//        this.unitPrice = unitPrice;
//        this.discount = discount;
//        this.totalValue = totalValue;
//        this.grandTotal = grandTotal;
//        this.requiredDate = requiredDate;
//        this.warrantyPeriod = warrantyPeriod;
//        this.paymentTerms = paymentTerms;
//        this.deliveryTerms = deliveryTerms;
//        this.poNote = poNote;
//        this.recordStatus = recordStatus;
//        this.supplierCode = supplierCode;
//        this.supplierName = supplierName;
//        this.supplierAddress = supplierAddress;
//        this.supplierEmail = supplierEmail;
//        this.remarks = remarks;
//        this.status = status;
//        this.lastmodifiedDate = lastmodifiedDate;
//        this.lumsumDiscount = lumsumDiscount;
//        this.costcenterCode = costcenterCode;
//        this.costcenterDesc = costcenterDesc;
//        this.uom1 = uom1;
//        this.uom1Price = uom1Price;
//        this.uom2 = uom2;
//        this.uom2Price = uom2Price;
//        this.uom3 = uom3;
//        this.uom3Price = uom3Price;
//        this.assetCategory = assetCategory;
//        this.subAssetCategory = subAssetCategory;
//    }

//    public PurchaseOrder(String userId, String orgId, String divisionName, String department, String purchaseType, String projectCode, String projectName, String purchaseOrderNo, Date purchaseOrderDate, String prNo, Date prDate, String preparedBy, String importLocal, String currency, String billToLocation, String shipToLocation, String itemCategory, String itemSubCategory, String itemCode, String itemName, String description, String uom, Double qty, Double unitPrice, Double discount, Double totalValue, Double grandTotal, Date requiredDate, String paymentTerms, String deliveryTerms, String recordStatus, String supplierCode, String supplierName, String supplierAddress, String supplierEmail, Integer prSno, String status, Date lastmodifiedDate, String costcenterCode, String costcenterDesc,
//            String uom1,
//            Double uom1Price,
//            String uom2,
//            Double uom2Price,
//            String uom3,
//            Double uom3Price) {
//        this.userId = userId;
//        this.orgId = orgId;
//        this.divisionName = divisionName;
//        this.department = department;
//        this.purchaseType = purchaseType;
//        this.projectCode = projectCode;
//        this.projectName = projectName;
//        this.purchaseOrderNo = purchaseOrderNo;
//        this.purchaseOrderDate = purchaseOrderDate;
//        this.prNo = prNo;
//        this.prDate = prDate;
//        this.preparedBy = preparedBy;
//        this.importLocal = importLocal;
//        this.currency = currency;
//        this.billToLocation = billToLocation;
//        this.shipToLocation = shipToLocation;
//        this.itemCategory = itemCategory;
//        this.itemSubCategory = itemSubCategory;
//        this.itemCode = itemCode;
//        this.itemName = itemName;
//        this.description = description;
//        this.uom = uom;
//        this.qty = qty;
//        this.unitPrice = unitPrice;
//        this.discount = discount;
//        this.totalValue = totalValue;
//        this.grandTotal = grandTotal;
//        this.requiredDate = requiredDate;
//        this.paymentTerms = paymentTerms;
//        this.deliveryTerms = deliveryTerms;
//        this.recordStatus = recordStatus;
//        this.supplierCode = supplierCode;
//        this.supplierName = supplierName;
//        this.supplierAddress = supplierAddress;
//        this.supplierEmail = supplierEmail;
//        this.prSno = prSno;
//        this.status = status;
//        this.lastmodifiedDate = lastmodifiedDate;
//        this.costcenterCode = costcenterCode;
//        this.costcenterDesc = costcenterDesc;
//        this.uom1 = uom1;
//        this.uom1Price = uom1Price;
//        this.uom2 = uom2;
//        this.uom2Price = uom2Price;
//        this.uom3 = uom3;
//        this.uom3Price = uom3Price;
//    }

//    public PurchaseOrder(Integer SNo, String userId, String orgId, String divisionName, String department, String purchaseType, String projectCode, String projectName, String purchaseOrderNo, Date purchaseOrderDate, String prNo, Date prDate, String preparedBy, String quotationNo, Date quotationDate, String importLocal, String currency, String billToLocation, String shipToLocation, String itemCategory, String itemSubCategory, String itemCode, String itemName, String description, String uom, Double qty, Double unitPrice, Double discount, Double totalValue, Double grandTotal, Date requiredDate, String warrantyPeriod, String paymentTerms, String deliveryTerms, String poNote, String recordStatus, String supplierCode, String supplierName, String supplierAddress, String supplierEmail, Integer prSno, Integer qtSno, String remarks, String status, Date lastmodifiedDate, String poRevNo, Double lumsumDiscount, String costcenterCode, String costcenterDesc,
//            String uom1,
//            Double uom1Price,
//            String uom2,
//            Double uom2Price,
//            String uom3,
//            Double uom3Price) {
//        this.SNo = SNo;
//        this.userId = userId;
//        this.orgId = orgId;
//        this.divisionName = divisionName;
//        this.department = department;
//        this.purchaseType = purchaseType;
//        this.projectCode = projectCode;
//        this.projectName = projectName;
//        this.purchaseOrderNo = purchaseOrderNo;
//        this.purchaseOrderDate = purchaseOrderDate;
//        this.prNo = prNo;
//        this.prDate = prDate;
//        this.preparedBy = preparedBy;
//        this.quotationNo = quotationNo;
//        this.quotationDate = quotationDate;
//        this.importLocal = importLocal;
//        this.currency = currency;
//        this.billToLocation = billToLocation;
//        this.shipToLocation = shipToLocation;
//        this.itemCategory = itemCategory;
//        this.itemSubCategory = itemSubCategory;
//        this.itemCode = itemCode;
//        this.itemName = itemName;
//        this.description = description;
//        this.uom = uom;
//        this.qty = qty;
//        this.unitPrice = unitPrice;
//        this.discount = discount;
//        this.totalValue = totalValue;
//        this.grandTotal = grandTotal;
//        this.requiredDate = requiredDate;
//        this.warrantyPeriod = warrantyPeriod;
//        this.paymentTerms = paymentTerms;
//        this.deliveryTerms = deliveryTerms;
//        this.poNote = poNote;
//        this.recordStatus = recordStatus;
//        this.supplierCode = supplierCode;
//        this.supplierName = supplierName;
//        this.supplierAddress = supplierAddress;
//        this.supplierEmail = supplierEmail;
//        this.prSno = prSno;
//        this.qtSno = qtSno;
//        this.remarks = remarks;
//        this.status = status;
//        this.lastmodifiedDate = lastmodifiedDate;
//        this.poRevNo = poRevNo;
//        this.lumsumDiscount = lumsumDiscount;
//        this.costcenterCode = costcenterCode;
//        this.costcenterDesc = costcenterDesc;
//        this.uom1 = uom1;
//        this.uom1Price = uom1Price;
//        this.uom2 = uom2;
//        this.uom2Price = uom2Price;
//        this.uom3 = uom3;
//        this.uom3Price = uom3Price;
//    }

//    public PurchaseOrder(String userId, String orgId, String divisionName, String department, String purchaseType, String projectCode, String projectName, String purchaseOrderNo, Date purchaseOrderDate, String prNo, Date prDate, String preparedBy, String quotationNo, Date quotationDate, String importLocal, String currency, String billToLocation, String shipToLocation, String itemCategory, String itemSubCategory, String itemCode, String itemName, String description, String uom, Double qty, Double unitPrice, Double discount, Double totalValue, Double grandTotal, Date requiredDate, String warrantyPeriod, String paymentTerms, String deliveryTerms, String poNote, String recordStatus, String supplierCode, String supplierName, String supplierAddress, String supplierEmail, Integer prSno, Integer qtSno, String remarks, String status, Date lastmodifiedDate, String poRevNo, Double lumsumDiscount, String costcenterCode, String costcenterDesc,
//            String uom1,
//            Double uom1Price,
//            String uom2,
//            Double uom2Price,
//            String uom3,
//            Double uom3Price
//    ) {
//        this.SNo = SNo;
//        this.userId = userId;
//        this.orgId = orgId;
//        this.divisionName = divisionName;
//        this.department = department;
//        this.purchaseType = purchaseType;
//        this.projectCode = projectCode;
//        this.projectName = projectName;
//        this.purchaseOrderNo = purchaseOrderNo;
//        this.purchaseOrderDate = purchaseOrderDate;
//        this.prNo = prNo;
//        this.prDate = prDate;
//        this.preparedBy = preparedBy;
//        this.quotationNo = quotationNo;
//        this.quotationDate = quotationDate;
//        this.importLocal = importLocal;
//        this.currency = currency;
//        this.billToLocation = billToLocation;
//        this.shipToLocation = shipToLocation;
//        this.itemCategory = itemCategory;
//        this.itemSubCategory = itemSubCategory;
//        this.itemCode = itemCode;
//        this.itemName = itemName;
//        this.description = description;
//        this.uom = uom;
//        this.qty = qty;
//        this.unitPrice = unitPrice;
//        this.discount = discount;
//        this.totalValue = totalValue;
//        this.grandTotal = grandTotal;
//        this.requiredDate = requiredDate;
//        this.warrantyPeriod = warrantyPeriod;
//        this.paymentTerms = paymentTerms;
//        this.deliveryTerms = deliveryTerms;
//        this.poNote = poNote;
//        this.recordStatus = recordStatus;
//        this.supplierCode = supplierCode;
//        this.supplierName = supplierName;
//        this.supplierAddress = supplierAddress;
//        this.supplierEmail = supplierEmail;
//        this.prSno = prSno;
//        this.qtSno = qtSno;
//        this.remarks = remarks;
//        this.status = status;
//        this.lastmodifiedDate = lastmodifiedDate;
//        this.poRevNo = poRevNo;
//        this.lumsumDiscount = lumsumDiscount;
//        this.costcenterCode = costcenterCode;
//        this.costcenterDesc = costcenterDesc;
//        this.uom1 = uom1;
//        this.uom1Price = uom1Price;
//        this.uom2 = uom2;
//        this.uom2Price = uom2Price;
//        this.uom3 = uom3;
//        this.uom3Price = uom3Price;
//    }

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "sno", unique = true, nullable = false)
    public Integer getSNo() {
        return SNo;
    }

    public void setSNo(Integer SNo) {
        this.SNo = SNo;
    }

    @Column(name = "user_id", length = 50)
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "org_id", length = 50)
    public String getOrgId() {
        return orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "division_name", length = 60)
    public String getDivisionName() {
        return divisionName;
    }

    public void setDivisionName(String divisionName) {
        this.divisionName = divisionName;
    }
@Column(name = "asset_category", length = 50)
    public String getAssetCategory() {
        return this.assetCategory;
    }

    public void setAssetCategory(String assetCategory) {
        this.assetCategory = assetCategory;
    }

    @Column(name = "sub_asset_category", length = 50)
    public String getSubAssetCategory() {
        return this.subAssetCategory;
    }

    public void setSubAssetCategory(String subAssetCategory) {
        this.subAssetCategory = subAssetCategory;
    }
    @Column(name = "department", length = 50)
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @Column(name = "purchase_type", length = 50)
    public String getPurchaseType() {
        return purchaseType;
    }

    public void setPurchaseType(String purchaseType) {
        this.purchaseType = purchaseType;
    }

    @Column(name = "project_code", length = 50)
    public String getProjectCode() {
        return projectCode;
    }

    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    @Column(name = "project_name", length = 50)
    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    @Column(name = "purchase_order_no", length = 50)
    public String getPurchaseOrderNo() {
        return purchaseOrderNo;
    }

    public void setPurchaseOrderNo(String purchaseOrderNo) {
        this.purchaseOrderNo = purchaseOrderNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "purchase_order_date", length = 10)
    public Date getPurchaseOrderDate() {
        return purchaseOrderDate;
    }

    public void setPurchaseOrderDate(Date purchaseOrderDate) {
        this.purchaseOrderDate = purchaseOrderDate;
    }

    @Column(name = "pr_no", length = 50)
    public String getPrNo() {
        return prNo;
    }

    public void setPrNo(String prNo) {
        this.prNo = prNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "pr_date", length = 10)
    public Date getPrDate() {
        return prDate;
    }

    public void setPrDate(Date prDate) {
        this.prDate = prDate;
    }

    @Column(name = "prepared_by", length = 50)
    public String getPreparedBy() {
        return preparedBy;
    }

    public void setPreparedBy(String preparedBy) {
        this.preparedBy = preparedBy;
    }

    @Column(name = "quotation_no", length = 50)
    public String getQuotationNo() {
        return quotationNo;
    }

    public void setQuotationNo(String quotationNo) {
        this.quotationNo = quotationNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "quotation_date", length = 10)
    public Date getQuotationDate() {
        return quotationDate;
    }

    public void setQuotationDate(Date quotationDate) {
        this.quotationDate = quotationDate;
    }

    @Column(name = "import_local", length = 50)
    public String getImportLocal() {
        return importLocal;
    }

    public void setImportLocal(String importLocal) {
        this.importLocal = importLocal;
    }

    @Column(name = "currency", length = 50)
    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    @Column(name = "bill_to_Location", length = 50)
    public String getBillToLocation() {
        return billToLocation;
    }

    public void setBillToLocation(String billToLocation) {
        this.billToLocation = billToLocation;
    }

    @Column(name = "ship_to_location", length = 50)
    public String getShipToLocation() {
        return shipToLocation;
    }

    public void setShipToLocation(String shipToLocation) {
        this.shipToLocation = shipToLocation;
    }

    @Column(name = "item_category", length = 50)
    public String getItemCategory() {
        return itemCategory;
    }

    public void setItemCategory(String itemCategory) {
        this.itemCategory = itemCategory;
    }

    @Column(name = "item_sub_category", length = 50)
    public String getItemSubCategory() {
        return itemSubCategory;
    }

    public void setItemSubCategory(String itemSubCategory) {
        this.itemSubCategory = itemSubCategory;
    }

    @Column(name = "item_code", length = 50)
    public String getItemCode() {
        return itemCode;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    @Column(name = "item_name", length = 50)
    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    @Column(name = "description", length = 50)
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "uom", length = 50)
    public String getUom() {
        return uom;
    }

    public void setUom(String uom) {
        this.uom = uom;
    }

    @Column(name = "qty", length = 50)
    public Double getQty() {
        return qty;
    }

    public void setQty(Double qty) {
        this.qty = qty;
    }

    @Column(name = "unit_price", length = 50)
    public Double getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    @Column(name = "discount", length = 50)
    public Double getDiscount() {
        return discount;
    }

    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    @Column(name = "total_value", length = 50)
    public Double getTotalValue() {
        return totalValue;
    }

    public void setTotalValue(Double totalValue) {
        this.totalValue = totalValue;
    }

    @Column(name = "grand_total", length = 50)
    public Double getGrandTotal() {
        return grandTotal;
    }

    public void setGrandTotal(Double grandTotal) {
        this.grandTotal = grandTotal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "required_date", length = 10)
    public Date getRequiredDate() {
        return requiredDate;
    }

    public void setRequiredDate(Date requiredDate) {
        this.requiredDate = requiredDate;
    }

    @Column(name = "warranty_period", length = 50)
    public String getWarrantyPeriod() {
        return warrantyPeriod;
    }

    public void setWarrantyPeriod(String warrantyPeriod) {
        this.warrantyPeriod = warrantyPeriod;
    }

    @Column(name = "payment_terms", length = 50)
    public String getPaymentTerms() {
        return paymentTerms;
    }

    public void setPaymentTerms(String paymentTerms) {
        this.paymentTerms = paymentTerms;
    }

    @Column(name = "delivery_terms", length = 50)
    public String getDeliveryTerms() {
        return deliveryTerms;
    }

    
    public void setDeliveryTerms(String deliveryTerms) {
        this.deliveryTerms = deliveryTerms;
    }

    @Column(name = "warrenty_terms")
    public String getWarrentyTerms() {
        return warrentyTerms;
    }

    public void setWarrentyTerms(String warrentyTerms) {
        this.warrentyTerms = warrentyTerms;
    }
    
    

    @Column(name = "po_note", length = 50)
    public String getPoNote() {
        return poNote;
    }

    public void setPoNote(String poNote) {
        this.poNote = poNote;
    }

    @Column(name = "record_status", length = 50)
    public String getRecordStatus() {
        return recordStatus;
    }

    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    @Column(name = "approval_status", length = 50)
    public String getApprovalStatus() {
        return approvalStatus;
    }

    public void setApprovalStatus(String approvalStatus) {
        this.approvalStatus = approvalStatus;
    }

    @Column(name = "supplier_code", length = 50)
    public String getSupplierCode() {
        return supplierCode;
    }

    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode;
    }

    @Column(name = "supplier_name", length = 50)
    public String getSupplierName() {
        return supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    @Column(name = "supplier_address", length = 50)
    public String getSupplierAddress() {
        return supplierAddress;
    }

    public void setSupplierAddress(String supplierAddress) {
        this.supplierAddress = supplierAddress;
    }

    @Column(name = "supplier_email", length = 50)
    public String getSupplierEmail() {
        return supplierEmail;
    }

    public void setSupplierEmail(String supplierEmail) {
        this.supplierEmail = supplierEmail;
    }

    @Column(name = "pr_sno", length = 50)
    public Integer getPrSno() {
        return prSno;
    }

    public void setPrSno(Integer prSno) {
        this.prSno = prSno;
    }

    @Column(name = "qt_sno", length = 50)
    public Integer getQtSno() {
        return qtSno;
    }

    public void setQtSno(Integer qtSno) {
        this.qtSno = qtSno;
    }

    @Column(name = "remarks", length = 50)
    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "pur_mng_name", length = 50)
    public String getPurMngName() {
        return purMngName;
    }

    public void setPurMngName(String purMngName) {
        this.purMngName = purMngName;
    }

    @Column(name = "pur_mng_remarks", length = 50)
    public String getPurMngRemarks() {
        return purMngRemarks;
    }

    public void setPurMngRemarks(String purMngRemarks) {
        this.purMngRemarks = purMngRemarks;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "pur_mng_date", length = 10)
    public Date getPurMngDate() {
        return purMngDate;
    }

    public void setPurMngDate(Date purMngDate) {
        this.purMngDate = purMngDate;
    }

    @Column(name = "gm_name", length = 50)
    public String getGmName() {
        return gmName;
    }

    public void setGmName(String gmName) {
        this.gmName = gmName;
    }

    @Column(name = "gm_remarks", length = 50)
    public String getGmRemarks() {
        return gmRemarks;
    }

    public void setGmRemarks(String gmRemarks) {
        this.gmRemarks = gmRemarks;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "gm_date", length = 10)
    public Date getGmDate() {
        return gmDate;
    }

    public void setGmDate(Date gmDate) {
        this.gmDate = gmDate;
    }

    @Column(name = "fm_name", length = 50)
    public String getFmName() {
        return fmName;
    }

    public void setFmName(String fmName) {
        this.fmName = fmName;
    }

    @Column(name = "fm_remarks", length = 50)
    public String getFmRemarks() {
        return fmRemarks;
    }

    public void setFmRemarks(String fmRemarks) {
        this.fmRemarks = fmRemarks;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fm_date", length = 10)
    public Date getFmDate() {
        return fmDate;
    }

    public void setFmDate(Date fmDate) {
        this.fmDate = fmDate;
    }

    @Column(name = "status", length = 50)
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "lastmodified_date", length = 10)
    public Date getLastmodifiedDate() {
        return lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Column(name = "po_rev_no", length = 50)
    public String getPoRevNo() {
        return poRevNo;
    }

    public void setPoRevNo(String poRevNo) {
        this.poRevNo = poRevNo;
    }

    @Column(name = "email_status", length = 50)
    public String getEmailStatus() {
        return emailStatus;
    }

    public void setEmailStatus(String emailStatus) {
        this.emailStatus = emailStatus;
    }

    @Column(name = "lumsum_discount", length = 50)
    public Double getLumsumDiscount() {
        return lumsumDiscount;
    }

    public void setLumsumDiscount(Double lumsumDiscount) {
        this.lumsumDiscount = lumsumDiscount;
    }

    @Column(name = "invoice_status", length = 50)
    public String getInvoiceStatus() {
        return invoiceStatus;
    }

    public void setInvoiceStatus(String invoiceStatus) {
        this.invoiceStatus = invoiceStatus;
    }

    @Column(name = "costcenter_code", length = 50)
    public String getCostcenterCode() {
        return costcenterCode;
    }

    public void setCostcenterCode(String costcenterCode) {
        this.costcenterCode = costcenterCode;
    }

    @Column(name = "costcenter_desc", length = 50)
    public String getCostcenterDesc() {
        return costcenterDesc;
    }

    public void setCostcenterDesc(String costcenterDesc) {
        this.costcenterDesc = costcenterDesc;
    }

    @Column(name = "uom1", length = 50)
    public String getUom1() {
        return uom1;
    }

    public void setUom1(String uom1) {
        this.uom1 = uom1;
    }

    @Column(name = "uom1_price", length = 50)
    public Double getUom1Price() {
        return uom1Price;
    }

    public void setUom1Price(Double uom1Price) {
        this.uom1Price = uom1Price;
    }

    @Column(name = "uom2", length = 50)
    public String getUom2() {
        return uom2;
    }

    public void setUom2(String uom2) {
        this.uom2 = uom2;
    }

    @Column(name = "uom2_price", length = 50)
    public Double getUom2Price() {
        return uom2Price;
    }

    public void setUom2Price(Double uom2Price) {
        this.uom2Price = uom2Price;
    }

    @Column(name = "uom3", length = 50)
    public String getUom3() {
        return uom3;
    }

    public void setUom3(String uom3) {
        this.uom3 = uom3;
    }

    @Column(name = "uom3_price", length = 50)
    public Double getUom3Price() {
        return uom3Price;
    }

    public void setUom3Price(Double uom3Price) {
        this.uom3Price = uom3Price;
    }

    @Column(name = "supplier_contact_number")
    public String getSupplierContactNumber() {
        return supplierContactNumber;
    }

    public void setSupplierContactNumber(String supplierContactNumber) {
        this.supplierContactNumber = supplierContactNumber;
    }

    @Column(name = "contact_person_name")
    public String getContactPersonName() {
        return contactPersonName;
    }

    public void setContactPersonName(String contactPersonName) {
        this.contactPersonName = contactPersonName;
    }

    @Column(name = "contact_address")
    public String getContactAddress() {
        return contactAddress;
    }

    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress;
    }

    @Column(name = "contact_number")
    public String getContactNumber() {
        return contactNumber;
    }

    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }

    @Column(name = "contact_email")
    public String getContactEmail() {
        return contactEmail;
    }

    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    @Column(name = "contact_code")
    public String getContactCode() {
        return contactCode;
    }

    public void setContactCode(String contactCode) {
        this.contactCode = contactCode;
    }

    @Column(name = "delivery_name")
    public String getDeliveryName() {
        return deliveryName;
    }

    public void setDeliveryName(String deliveryName) {
        this.deliveryName = deliveryName;
    }

    @Column(name = "delivery_address")
    public String getDeliveryAddress() {
        return deliveryAddress;
    }

    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }

    @Column(name = "delivery_contact")
    public String getDeliveryContact() {
        return deliveryContact;
    }

    public void setDeliveryContact(String deliveryContact) {
        this.deliveryContact = deliveryContact;
    }

    @Column(name = "delivery_email")
    public String getDeliveryEmail() {
        return deliveryEmail;
    }

    public void setDeliveryEmail(String deliveryEmail) {
        this.deliveryEmail = deliveryEmail;
    }

    @Column(name = "delivery_code")
    public String getDeliveryCode() {
        return deliveryCode;
    }

    public void setDeliveryCode(String deliveryCode) {
        this.deliveryCode = deliveryCode;
    } 

    @Temporal(TemporalType.DATE)
    @Column(name = "expected_delivery_date", length = 10)
    public Date getExpectedDeliveryDate() {
        return expectedDeliveryDate;
    }

    public void setExpectedDeliveryDate(Date expectedDeliveryDate) {
        this.expectedDeliveryDate = expectedDeliveryDate;
    }

    
}
