package tenant.classes;
// Generated Oct 6, 2016 3:18:10 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Quality generated by hbm2java
 */
@Entity
@Table(name = "quality", schema = "arete_tms"
)
public class Quality implements java.io.Serializable {

    private Integer sno;
    private String orgId;
    private String userId;
    private String qa;
    private String poNo;
    private String qaBy;
    private String customerInvoiceNo;
    private Date customerInvoiceDate;
    private String supplierName;
    private String supplierAddress;
    private String supplierCntNo;
    private String supplierMailId;
    private String inventoryLocation;
    private String subAssetCode;
    private String category;
    private String type;
    private String orderedQty;
    private String receivedQty;
    private String foc;
    private String uom;
    private String qtyAccepted;
    private String qtyRejected;
    private String batchNo;
    private Date expiryDate;
    private String warrantyPeriod;
    private String remarks;
    private Date qaDate;
    private String itemCode;
    private String itemName;
    private String qualityStatus;
    private String createdBy;
    private Date creationDate;
    private String status;
    private Date lastmodifiedDate;
    private String unitPrice;
    private String totalPrice;
    private String returnStatus;

    public Quality() {
    }

    public Quality(String qa) {
        this.qa = qa;
    }

    public Quality(String orgId, String userId, String qa, String poNo, String qaBy, String customerInvoiceNo, Date customerInvoiceDate, String supplierName, String supplierAddress, String supplierCntNo, String supplierMailId, String inventoryLocation, String receivedQty, String foc, String uom, String qtyAccepted, String qtyRejected, String batchNo, Date expiryDate, String warrantyPeriod, String remarks, Date qaDate, String itemCode, String itemName, String qualityStatus, String status, Date lastmodifiedDate, String unitPrice, String totalPrice, String returnStatus, String orderedQty) {
        this.orgId = orgId;
        this.userId = userId;
        this.qa = qa;
        this.poNo = poNo;
        this.qaBy = qaBy;
        this.customerInvoiceNo = customerInvoiceNo;
        this.customerInvoiceDate = customerInvoiceDate;
        this.supplierName = supplierName;
        this.supplierAddress = supplierAddress;
        this.supplierCntNo = supplierCntNo;
        this.supplierMailId = supplierMailId;
        this.inventoryLocation = inventoryLocation;
//       this.subAssetCode = subAssetCode;
//       this.category = category;
//       this.type = type;
//       this.orderedQty = orderedQty;
        this.receivedQty = receivedQty;
        this.foc = foc;
        this.uom = uom;
        this.qtyAccepted = qtyAccepted;
        this.qtyRejected = qtyRejected;
        this.batchNo = batchNo;
        this.expiryDate = expiryDate;
        this.warrantyPeriod = warrantyPeriod;
        this.remarks = remarks;
//       this.createdBy = createdBy;
//       this.creationDate = creationDate;
        this.qaDate = qaDate;
        this.itemCode = itemCode;
        this.itemName = itemName;
        this.qualityStatus = qualityStatus;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.unitPrice = unitPrice;
        this.totalPrice = totalPrice;
        this.returnStatus = returnStatus;
        this.orderedQty = orderedQty;
    }

    public Quality(Integer sno, String orgId, String userId, String qa, String poNo, String qaBy, String customerInvoiceNo, Date customerInvoiceDate, String supplierName, String supplierAddress, String supplierCntNo, String supplierMailId, String inventoryLocation, String receivedQty, String foc, String uom, String qtyAccepted, String qtyRejected, String batchNo, Date expiryDate, String warrantyPeriod, String remarks, Date qaDate, String itemCode, String itemName, String qualityStatus, String status, Date lastmodifiedDate, String unitPrice, String totalPrice, String returnStatus, String orderedQty) {

        this.sno = sno;
        this.orgId = orgId;
        this.userId = userId;
        this.qa = qa;
        this.poNo = poNo;
        this.qaBy = qaBy;
        this.customerInvoiceNo = customerInvoiceNo;
        this.customerInvoiceDate = customerInvoiceDate;
        this.supplierName = supplierName;
        this.supplierAddress = supplierAddress;
        this.supplierCntNo = supplierCntNo;
        this.supplierMailId = supplierMailId;
        this.inventoryLocation = inventoryLocation;
//       this.subAssetCode = subAssetCode;
//       this.category = category;
//       this.type = type;
//       this.orderedQty = orderedQty;
        this.receivedQty = receivedQty;
        this.foc = foc;
        this.uom = uom;
        this.qtyAccepted = qtyAccepted;
        this.qtyRejected = qtyRejected;
        this.batchNo = batchNo;
        this.expiryDate = expiryDate;
        this.warrantyPeriod = warrantyPeriod;
        this.remarks = remarks;
        this.qaDate = qaDate;
        this.itemCode = itemCode;
        this.itemName = itemName;
        this.qualityStatus = qualityStatus;
//       this.createdBy = createdBy;
//       this.creationDate = creationDate;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.unitPrice = unitPrice;
        this.totalPrice = totalPrice;
        this.returnStatus = returnStatus;
        this.orderedQty = orderedQty;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "sno", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "org_id", length = 50)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "user_id", length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "qa", nullable = false, length = 60)
    public String getQa() {
        return this.qa;
    }

    public void setQa(String qa) {
        this.qa = qa;
    }

    @Column(name = "po_no", length = 60)
    public String getPoNo() {
        return this.poNo;
    }

    public void setPoNo(String poNo) {
        this.poNo = poNo;
    }

    @Column(name = "qa_by", length = 60)
    public String getQaBy() {
        return this.qaBy;
    }

    public void setQaBy(String qaBy) {
        this.qaBy = qaBy;
    }

    @Column(name = "customer_invoice_no", length = 60)
    public String getCustomerInvoiceNo() {
        return this.customerInvoiceNo;
    }

    public void setCustomerInvoiceNo(String customerInvoiceNo) {
        this.customerInvoiceNo = customerInvoiceNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CUSTOMER_INVOICE_DATE", length = 60)
    public Date getCustomerInvoiceDate() {
        return this.customerInvoiceDate;
    }

    public void setCustomerInvoiceDate(Date customerInvoiceDate) {
        this.customerInvoiceDate = customerInvoiceDate;
    }

    @Column(name = "SUPPLIER_NAME", length = 60)
    public String getSupplierName() {
        return this.supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    @Column(name = "SUPPLIER_ADDRESS", length = 500)
    public String getSupplierAddress() {
        return this.supplierAddress;
    }

    public void setSupplierAddress(String supplierAddress) {
        this.supplierAddress = supplierAddress;
    }

    @Column(name = "SUPPLIER_CNT_NO", length = 20)
    public String getSupplierCntNo() {
        return this.supplierCntNo;
    }

    public void setSupplierCntNo(String supplierCntNo) {
        this.supplierCntNo = supplierCntNo;
    }

    @Column(name = "SUPPLIER_MAIL_ID", length = 60)
    public String getSupplierMailId() {
        return this.supplierMailId;
    }

    public void setSupplierMailId(String supplierMailId) {
        this.supplierMailId = supplierMailId;
    }

    @Column(name = "INVENTORY_LOCATION", length = 200)
    public String getInventoryLocation() {
        return this.inventoryLocation;
    }

    public void setInventoryLocation(String inventoryLocation) {
        this.inventoryLocation = inventoryLocation;
    }

    @Column(name = "sub_asset_code", length = 60)
    public String getSubAssetCode() {
        return this.subAssetCode;
    }

    public void setSubAssetCode(String subAssetCode) {
        this.subAssetCode = subAssetCode;
    }

    @Column(name = "category", length = 60)
    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    @Column(name = "type", length = 60)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "ordered_qty", length = 60)
    public String getOrderedQty() {
        return this.orderedQty;
    }

    public void setOrderedQty(String orderedQty) {
        this.orderedQty = orderedQty;
    }

    @Column(name = "received_qty", length = 60)
    public String getReceivedQty() {
        return this.receivedQty;
    }

    public void setReceivedQty(String receivedQty) {
        this.receivedQty = receivedQty;
    }

    @Column(name = "foc", length = 60)
    public String getFoc() {
        return this.foc;
    }

    public void setFoc(String foc) {
        this.foc = foc;
    }

    @Column(name = "uom", length = 60)
    public String getUom() {
        return this.uom;
    }

    public void setUom(String uom) {
        this.uom = uom;
    }

    @Column(name = "qty_accepted", length = 60)
    public String getQtyAccepted() {
        return this.qtyAccepted;
    }

    public void setQtyAccepted(String qtyAccepted) {
        this.qtyAccepted = qtyAccepted;
    }

    @Column(name = "qty_rejected", length = 60)
    public String getQtyRejected() {
        return this.qtyRejected;
    }

    public void setQtyRejected(String qtyRejected) {
        this.qtyRejected = qtyRejected;
    }

    @Column(name = "batch_no", length = 60)
    public String getBatchNo() {
        return this.batchNo;
    }

    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "expiry_date", length = 60)
    public Date getExpiryDate() {
        return this.expiryDate;
    }

    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    @Column(name = "warranty_period", length = 60)
    public String getWarrantyPeriod() {
        return this.warrantyPeriod;
    }

    public void setWarrantyPeriod(String warrantyPeriod) {
        this.warrantyPeriod = warrantyPeriod;
    }

    @Column(name = "remarks", length = 500)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "created_by", length = 60)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "creation_date", length = 60)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lastmodified_date", length = 60)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Column(name = "STATUS", length = 60)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "qa_date", length = 60)
    public Date getQaDate() {
        return qaDate;
    }

    public void setQaDate(Date qaDate) {
        this.qaDate = qaDate;
    }

    @Column(name = "item_code", length = 60)
    public String getItemCode() {
        return itemCode;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    @Column(name = "item_name", length = 60)
    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    @Column(name = "quality_status", length = 60)
    public String getQualityStatus() {
        return qualityStatus;
    }

    public void setQualityStatus(String qualityStatus) {
        this.qualityStatus = qualityStatus;
    }

    @Column(name = "unit_price", length = 60)
    public String getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(String unitPrice) {
        this.unitPrice = unitPrice;
    }

    @Column(name = "total_price", length = 60)
    public String getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(String totalPrice) {
        this.totalPrice = totalPrice;
    }

    @Column(name = "return_status", length = 60)
    public String getReturnStatus() {
        return returnStatus;
    }

    public void setReturnStatus(String returnStatus) {
        this.returnStatus = returnStatus;
    }

}
