package tenant.classes;
// Generated 15 Sep, 2016 4:06:08 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rentquote generated by hbm2java
 */
@Entity
@Table(name = "rentquote", catalog = "arete_tms"
)
public class Rentquote implements java.io.Serializable {

    private Integer sno;
    private String userId;
    private String orgId;
    private String tenantQuoteCode;
    private String tenantType;
    private String tenantCategory;
    private String tenantFirstName;
    private String tenantLastName;
    private String tenantCitizenship;
    private String tenantId;
    private String tenantpostalCode;
    private String tenantPostBoxNo;

    private byte[] tenantAttachment;
    private String tenantFilename;

    private String jointeeName1;
    private String jointeeAddress1;
    private String jointeeName2;
    private String jointeeAddress2;
    private String sponsorname;
    private String ifWorking;
    private String companyName;
    private String companyAddress;
    private String crno;
    private String contactNo;
    private String tenantWorkContactNo;
    private String mailId;
    private String permanentAddress;
    private String correspondingAddress;
    private String sponsorAddress;
    private String sponsorPostalCode;
    private String sponsorPostBoxNo;
    private String tenantHistory;
    private String remarks;
    private String assetName;
    private String assetCode;
    private String subClassifiedAssetName;
    private String buildingNo;
    private String waterUtilityBillNo;
    private String area;
    private String blockNo;
    private String plotNo;
    private String electricBillNo;
    private String way;
    private String streetNo;
    private String postalCode;
    private String postBoxNo;
    private String contractCode;
    private String contractName;
    private Date startsFrom;
    private Date endTo;

    private byte[] contractAttachment;
    private String contractFileName;

    private String minimumRentFixed;
    private String quotedRentAmount;
    private String billingCycle;
    private Date dueDate;
    private String approverStatus;
    private String creationFrom;
    private String recordStatus;
    private String approver1;
    private String approverRemarks1;
    private String approver2;
    private String approverRemarks2;
    private String attribute1;
    private String attribute2;
    private String attribute3;
    private String attribute4;
    private String attribute5;
    private String status;
    private Date lastmodefiedDate;
    private String subAssetCode;

    public Rentquote() {
    }

    public Rentquote(String userId) {
        this.userId = userId;
    }

    public Rentquote(String userId, String orgId, String tenantQuoteCode, String tenantType, String tenantCategory, String tenantFirstName, String tenantLastName, String tenantCitizenship, String tenantId, String tenantpostalCode, String tenantPostBoxNo, byte[] tenantAttachment, String tenantFilename, String jointeeName1, String jointeeAddress1, String jointeeName2, String jointeeAddress2, String sponsorname, String ifWorking, String companyName, String companyAddress, String crno, String contactNo, String tenantWorkContactNo, String mailId, String permanentAddress, String correspondingAddress, String sponsorAddress, String sponsorPostalCode, String sponsorPostBoxNo, String tenantHistory, String remarks, String assetName, String assetCode, String subClassifiedAssetName, String buildingNo, String waterUtilityBillNo, String area, String blockNo, String plotNo, String electricBillNo, String way, String streetNo, String postalCode, String postBoxNo, String contractCode, String contractName, Date startsFrom, Date endTo, byte[] contractAttachment, String contractFileName, String minimumRentFixed, String quotedRentAmount, String billingCycle, Date dueDate, String approverStatus, String creationFrom, String recordStatus, String approver1, String approverRemarks1, String approver2, String approverRemarks2, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, String status, Date lastmodefiedDate) {
        this.userId = userId;
        this.orgId = orgId;
        this.tenantQuoteCode = tenantQuoteCode;
        this.tenantType = tenantType;
        this.tenantCategory = tenantCategory;
        this.tenantFirstName = tenantFirstName;
        this.tenantLastName = tenantLastName;
        this.tenantCitizenship = tenantCitizenship;
        this.tenantId = tenantId;
        this.tenantpostalCode = tenantpostalCode;
        this.tenantPostBoxNo = tenantPostBoxNo;
        this.tenantAttachment = tenantAttachment;
        this.tenantFilename = tenantFilename;
        this.jointeeName1 = jointeeName1;
        this.jointeeAddress1 = jointeeAddress1;
        this.jointeeName2 = jointeeName2;
        this.jointeeAddress2 = jointeeAddress2;
        this.sponsorname = sponsorname;
        this.ifWorking = ifWorking;
        this.companyName = companyName;
        this.companyAddress = companyAddress;
        this.crno = crno;
        this.contactNo = contactNo;
        this.tenantWorkContactNo = tenantWorkContactNo;
        this.mailId = mailId;
        this.permanentAddress = permanentAddress;
        this.correspondingAddress = correspondingAddress;
        this.sponsorAddress = sponsorAddress;
        this.sponsorPostalCode = sponsorPostalCode;
        this.sponsorPostBoxNo = sponsorPostBoxNo;
        this.tenantHistory = tenantHistory;
        this.remarks = remarks;
        this.assetName = assetName;
        this.assetCode = assetCode;
        this.subClassifiedAssetName = subClassifiedAssetName;
        this.buildingNo = buildingNo;
        this.waterUtilityBillNo = waterUtilityBillNo;
        this.area = area;
        this.blockNo = blockNo;
        this.plotNo = plotNo;
        this.electricBillNo = electricBillNo;
        this.way = way;
        this.streetNo = streetNo;
        this.postalCode = postalCode;
        this.postBoxNo = postBoxNo;
        this.contractCode = contractCode;
        this.contractName = contractName;
        this.startsFrom = startsFrom;
        this.endTo = endTo;
        this.contractAttachment = contractAttachment;
        this.contractFileName = contractFileName;
        this.minimumRentFixed = minimumRentFixed;
        this.quotedRentAmount = quotedRentAmount;
        this.billingCycle = billingCycle;
        this.dueDate = dueDate;
        this.approverStatus = approverStatus;
        this.creationFrom = creationFrom;
        this.recordStatus = recordStatus;
        this.approver1 = approver1;
        this.approverRemarks1 = approverRemarks1;
        this.approver2 = approver2;
        this.approverRemarks2 = approverRemarks2;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.status = status;
        this.lastmodefiedDate = lastmodefiedDate;
    }

    public Rentquote(Integer sno, String userId, String orgId, String tenantQuoteCode, String tenantType, String tenantCategory, String tenantFirstName, String tenantLastName, String tenantCitizenship, String tenantId, String tenantpostalCode, String tenantPostBoxNo, byte[] tenantAttachment, String tenantFilename, String jointeeName1, String jointeeAddress1, String jointeeName2, String jointeeAddress2, String sponsorname, String ifWorking, String companyName, String companyAddress, String crno, String contactNo, String tenantWorkContactNo, String mailId, String permanentAddress, String correspondingAddress, String sponsorAddress, String sponsorPostalCode, String sponsorPostBoxNo, String tenantHistory, String remarks, String assetName, String assetCode, String subClassifiedAssetName, String buildingNo, String waterUtilityBillNo, String area, String blockNo, String plotNo, String electricBillNo, String way, String streetNo, String postalCode, String postBoxNo, String contractCode, String contractName, Date startsFrom, Date endTo, byte[] contractAttachment, String contractFileName, String minimumRentFixed, String quotedRentAmount, String billingCycle, Date dueDate, String approverStatus, String creationFrom, String recordStatus, String approver1, String approverRemarks1, String approver2, String approverRemarks2, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, String status, Date lastmodefiedDate) {
        this.sno = sno;
        this.userId = userId;
        this.orgId = orgId;
        this.tenantQuoteCode = tenantQuoteCode;
        this.tenantType = tenantType;
        this.tenantCategory = tenantCategory;
        this.tenantFirstName = tenantFirstName;
        this.tenantLastName = tenantLastName;
        this.tenantCitizenship = tenantCitizenship;
        this.tenantId = tenantId;
        this.tenantpostalCode = tenantpostalCode;
        this.tenantPostBoxNo = tenantPostBoxNo;
        this.tenantAttachment = tenantAttachment;
        this.tenantFilename = tenantFilename;
        this.jointeeName1 = jointeeName1;
        this.jointeeAddress1 = jointeeAddress1;
        this.jointeeName2 = jointeeName2;
        this.jointeeAddress2 = jointeeAddress2;
        this.sponsorname = sponsorname;
        this.ifWorking = ifWorking;
        this.companyName = companyName;
        this.companyAddress = companyAddress;
        this.crno = crno;
        this.contactNo = contactNo;
        this.tenantWorkContactNo = tenantWorkContactNo;
        this.mailId = mailId;
        this.permanentAddress = permanentAddress;
        this.correspondingAddress = correspondingAddress;
        this.sponsorAddress = sponsorAddress;
        this.sponsorPostalCode = sponsorPostalCode;
        this.sponsorPostBoxNo = sponsorPostBoxNo;
        this.tenantHistory = tenantHistory;
        this.remarks = remarks;
        this.assetName = assetName;
        this.assetCode = assetCode;
        this.subClassifiedAssetName = subClassifiedAssetName;
        this.buildingNo = buildingNo;
        this.waterUtilityBillNo = waterUtilityBillNo;
        this.area = area;
        this.blockNo = blockNo;
        this.plotNo = plotNo;
        this.electricBillNo = electricBillNo;
        this.way = way;
        this.streetNo = streetNo;
        this.postalCode = postalCode;
        this.postBoxNo = postBoxNo;
        this.contractCode = contractCode;
        this.contractName = contractName;
        this.startsFrom = startsFrom;
        this.endTo = endTo;
        this.contractAttachment = contractAttachment;
        this.contractFileName = contractFileName;
        this.minimumRentFixed = minimumRentFixed;
        this.quotedRentAmount = quotedRentAmount;
        this.billingCycle = billingCycle;
        this.dueDate = dueDate;
        this.approverStatus = approverStatus;
        this.creationFrom = creationFrom;
        this.recordStatus = recordStatus;
        this.approver1 = approver1;
        this.approverRemarks1 = approverRemarks1;
        this.approver2 = approver2;
        this.approverRemarks2 = approverRemarks2;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.status = status;
        this.lastmodefiedDate = lastmodefiedDate;
    }

    /*   
     Added by Garun while adding a new column sub asset code in RentQuote table 
     Reason to create new one : may be this will effect on other runing files
     */
    public Rentquote(String userId, String orgId, String tenantQuoteCode, String tenantType, String tenantCategory, String tenantFirstName, String tenantLastName, String tenantCitizenship, String tenantId, String tenantpostalCode, String tenantPostBoxNo, byte[] tenantAttachment, String tenantFilename, String jointeeName1, String jointeeAddress1, String jointeeName2, String jointeeAddress2, String sponsorname, String ifWorking, String companyName, String companyAddress, String crno, String contactNo, String tenantWorkContactNo, String mailId, String permanentAddress, String correspondingAddress, String sponsorAddress, String sponsorPostalCode, String sponsorPostBoxNo, String tenantHistory, String remarks, String assetName, String assetCode, String subClassifiedAssetName, String buildingNo, String waterUtilityBillNo, String area, String blockNo, String plotNo, String electricBillNo, String way, String streetNo, String postalCode, String postBoxNo, String contractCode, String contractName, Date startsFrom, Date endTo, byte[] contractAttachment, String contractFileName, String minimumRentFixed, String quotedRentAmount, String billingCycle, Date dueDate, String approverStatus, String creationFrom, String recordStatus, String approver1, String approverRemarks1, String approver2, String approverRemarks2, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, String status, Date lastmodefiedDate, String subAssetCode) {
        this.userId = userId;
        this.orgId = orgId;
        this.tenantQuoteCode = tenantQuoteCode;
        this.tenantType = tenantType;
        this.tenantCategory = tenantCategory;
        this.tenantFirstName = tenantFirstName;
        this.tenantLastName = tenantLastName;
        this.tenantCitizenship = tenantCitizenship;
        this.tenantId = tenantId;
        this.tenantpostalCode = tenantpostalCode;
        this.tenantPostBoxNo = tenantPostBoxNo;
        this.tenantAttachment = tenantAttachment;
        this.tenantFilename = tenantFilename;
        this.jointeeName1 = jointeeName1;
        this.jointeeAddress1 = jointeeAddress1;
        this.jointeeName2 = jointeeName2;
        this.jointeeAddress2 = jointeeAddress2;
        this.sponsorname = sponsorname;
        this.ifWorking = ifWorking;
        this.companyName = companyName;
        this.companyAddress = companyAddress;
        this.crno = crno;
        this.contactNo = contactNo;
        this.tenantWorkContactNo = tenantWorkContactNo;
        this.mailId = mailId;
        this.permanentAddress = permanentAddress;
        this.correspondingAddress = correspondingAddress;
        this.sponsorAddress = sponsorAddress;
        this.sponsorPostalCode = sponsorPostalCode;
        this.sponsorPostBoxNo = sponsorPostBoxNo;
        this.tenantHistory = tenantHistory;
        this.remarks = remarks;
        this.assetName = assetName;
        this.assetCode = assetCode;
        this.subClassifiedAssetName = subClassifiedAssetName;
        this.buildingNo = buildingNo;
        this.waterUtilityBillNo = waterUtilityBillNo;
        this.area = area;
        this.blockNo = blockNo;
        this.plotNo = plotNo;
        this.electricBillNo = electricBillNo;
        this.way = way;
        this.streetNo = streetNo;
        this.postalCode = postalCode;
        this.postBoxNo = postBoxNo;
        this.contractCode = contractCode;
        this.contractName = contractName;
        this.startsFrom = startsFrom;
        this.endTo = endTo;
        this.contractAttachment = contractAttachment;
        this.contractFileName = contractFileName;
        this.minimumRentFixed = minimumRentFixed;
        this.quotedRentAmount = quotedRentAmount;
        this.billingCycle = billingCycle;
        this.dueDate = dueDate;
        this.approverStatus = approverStatus;
        this.creationFrom = creationFrom;
        this.recordStatus = recordStatus;
        this.approver1 = approver1;
        this.approverRemarks1 = approverRemarks1;
        this.approver2 = approver2;
        this.approverRemarks2 = approverRemarks2;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.status = status;
        this.lastmodefiedDate = lastmodefiedDate;
        this.subAssetCode = subAssetCode;
    }

    public Rentquote(Integer sno, String userId, String orgId, String tenantQuoteCode, String tenantType, String tenantCategory, String tenantFirstName, String tenantLastName, String tenantCitizenship, String tenantId, String tenantpostalCode, String tenantPostBoxNo, byte[] tenantAttachment, String tenantFilename, String jointeeName1, String jointeeAddress1, String jointeeName2, String jointeeAddress2, String sponsorname, String ifWorking, String companyName, String companyAddress, String crno, String contactNo, String tenantWorkContactNo, String mailId, String permanentAddress, String correspondingAddress, String sponsorAddress, String sponsorPostalCode, String sponsorPostBoxNo, String tenantHistory, String remarks, String assetName, String assetCode, String subClassifiedAssetName, String buildingNo, String waterUtilityBillNo, String area, String blockNo, String plotNo, String electricBillNo, String way, String streetNo, String postalCode, String postBoxNo, String contractCode, String contractName, Date startsFrom, Date endTo, byte[] contractAttachment, String contractFileName, String minimumRentFixed, String quotedRentAmount, String billingCycle, Date dueDate, String approverStatus, String creationFrom, String recordStatus, String approver1, String approverRemarks1, String approver2, String approverRemarks2, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, String status, Date lastmodefiedDate, String subAssetCode) {
        this.sno = sno;
        this.userId = userId;
        this.orgId = orgId;
        this.tenantQuoteCode = tenantQuoteCode;
        this.tenantType = tenantType;
        this.tenantCategory = tenantCategory;
        this.tenantFirstName = tenantFirstName;
        this.tenantLastName = tenantLastName;
        this.tenantCitizenship = tenantCitizenship;
        this.tenantId = tenantId;
        this.tenantpostalCode = tenantpostalCode;
        this.tenantPostBoxNo = tenantPostBoxNo;
        this.tenantAttachment = tenantAttachment;
        this.tenantFilename = tenantFilename;
        this.jointeeName1 = jointeeName1;
        this.jointeeAddress1 = jointeeAddress1;
        this.jointeeName2 = jointeeName2;
        this.jointeeAddress2 = jointeeAddress2;
        this.sponsorname = sponsorname;
        this.ifWorking = ifWorking;
        this.companyName = companyName;
        this.companyAddress = companyAddress;
        this.crno = crno;
        this.contactNo = contactNo;
        this.tenantWorkContactNo = tenantWorkContactNo;
        this.mailId = mailId;
        this.permanentAddress = permanentAddress;
        this.correspondingAddress = correspondingAddress;
        this.sponsorAddress = sponsorAddress;
        this.sponsorPostalCode = sponsorPostalCode;
        this.sponsorPostBoxNo = sponsorPostBoxNo;
        this.tenantHistory = tenantHistory;
        this.remarks = remarks;
        this.assetName = assetName;
        this.assetCode = assetCode;
        this.subClassifiedAssetName = subClassifiedAssetName;
        this.buildingNo = buildingNo;
        this.waterUtilityBillNo = waterUtilityBillNo;
        this.area = area;
        this.blockNo = blockNo;
        this.plotNo = plotNo;
        this.electricBillNo = electricBillNo;
        this.way = way;
        this.streetNo = streetNo;
        this.postalCode = postalCode;
        this.postBoxNo = postBoxNo;
        this.contractCode = contractCode;
        this.contractName = contractName;
        this.startsFrom = startsFrom;
        this.endTo = endTo;
        this.contractAttachment = contractAttachment;
        this.contractFileName = contractFileName;
        this.minimumRentFixed = minimumRentFixed;
        this.quotedRentAmount = quotedRentAmount;
        this.billingCycle = billingCycle;
        this.dueDate = dueDate;
        this.approverStatus = approverStatus;
        this.creationFrom = creationFrom;
        this.recordStatus = recordStatus;
        this.approver1 = approver1;
        this.approverRemarks1 = approverRemarks1;
        this.approver2 = approver2;
        this.approverRemarks2 = approverRemarks2;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.status = status;
        this.lastmodefiedDate = lastmodefiedDate;
        this.subAssetCode = subAssetCode;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "sno", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "user_Id", nullable = false, length = 20)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "org_Id", length = 20)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "Tenant_QuoteCode", length = 100)
    public String getTenantQuoteCode() {
        return this.tenantQuoteCode;
    }

    public void setTenantQuoteCode(String tenantQuoteCode) {
        this.tenantQuoteCode = tenantQuoteCode;
    }

    @Column(name = "Tenant_Type", length = 100)
    public String getTenantType() {
        return this.tenantType;
    }

    public void setTenantType(String tenantType) {
        this.tenantType = tenantType;
    }

    @Column(name = "Tenant_Category", length = 100)
    public String getTenantCategory() {
        return this.tenantCategory;
    }

    public void setTenantCategory(String tenantCategory) {
        this.tenantCategory = tenantCategory;
    }

    @Column(name = "Tenant_FirstName", length = 100)
    public String getTenantFirstName() {
        return this.tenantFirstName;
    }

    public void setTenantFirstName(String tenantFirstName) {
        this.tenantFirstName = tenantFirstName;
    }

    @Column(name = "Tenant_LastName", length = 100)
    public String getTenantLastName() {
        return this.tenantLastName;
    }

    public void setTenantLastName(String tenantLastName) {
        this.tenantLastName = tenantLastName;
    }

    @Column(name = "Tenant_Citizenship", length = 50)
    public String getTenantCitizenship() {
        return this.tenantCitizenship;
    }

    public void setTenantCitizenship(String tenantCitizenship) {
        this.tenantCitizenship = tenantCitizenship;
    }

    @Column(name = "Tenant_Id", length = 50)
    public String getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    @Column(name = "Tenant_postalCode", length = 10)
    public String getTenantpostalCode() {
        return this.tenantpostalCode;
    }

    public void setTenantpostalCode(String tenantpostalCode) {
        this.tenantpostalCode = tenantpostalCode;
    }

    @Column(name = "Tenant_PostBoxNo", length = 10)
    public String getTenantPostBoxNo() {
        return this.tenantPostBoxNo;
    }

    public void setTenantPostBoxNo(String tenantPostBoxNo) {
        this.tenantPostBoxNo = tenantPostBoxNo;
    }

    @Column(name = "Tenant_Attachment", columnDefinition = "MEDIUMBLOB")
    public byte[] getTenantAttachment() {
        return this.tenantAttachment;
    }

    public void setTenantAttachment(byte[] tenantAttachment) {
        this.tenantAttachment = tenantAttachment;
    }

    @Column(name = "tenant_Filename")
    public String getTenantFilename() {
        return tenantFilename;
    }

    public void setTenantFilename(String tenantFilename) {
        this.tenantFilename = tenantFilename;
    }

    @Column(name = "Jointee_Name1", length = 60)
    public String getJointeeName1() {
        return this.jointeeName1;
    }

    public void setJointeeName1(String jointeeName1) {
        this.jointeeName1 = jointeeName1;
    }

    @Column(name = "Jointee_Address1", length = 500)
    public String getJointeeAddress1() {
        return this.jointeeAddress1;
    }

    public void setJointeeAddress1(String jointeeAddress1) {
        this.jointeeAddress1 = jointeeAddress1;
    }

    @Column(name = "Jointee_Name2", length = 60)
    public String getJointeeName2() {
        return this.jointeeName2;
    }

    public void setJointeeName2(String jointeeName2) {
        this.jointeeName2 = jointeeName2;
    }

    @Column(name = "Jointee_Address2", length = 500)
    public String getJointeeAddress2() {
        return this.jointeeAddress2;
    }

    public void setJointeeAddress2(String jointeeAddress2) {
        this.jointeeAddress2 = jointeeAddress2;
    }

    @Column(name = "Sponsor_Name", length = 50)
    public String getSponsorname() {
        return this.sponsorname;
    }

    public void setSponsorname(String sponsorname) {
        this.sponsorname = sponsorname;
    }

    @Column(name = "If_Working", length = 50)
    public String getIfWorking() {
        return this.ifWorking;
    }

    public void setIfWorking(String ifWorking) {
        this.ifWorking = ifWorking;
    }

    @Column(name = "Company_Name", length = 50)
    public String getCompanyName() {
        return this.companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    @Column(name = "Company_Address", length = 500)
    public String getCompanyAddress() {
        return this.companyAddress;
    }

    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress;
    }

    @Column(name = "CR_No", length = 50)
    public String getCrno() {
        return this.crno;
    }

    public void setCrno(String crno) {
        this.crno = crno;
    }

    @Column(name = "Contact_No", length = 50)
    public String getContactNo() {
        return this.contactNo;
    }

    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    @Column(name = "Tenant_Work_ContactNo", length = 50)
    public String getTenantWorkContactNo() {
        return this.tenantWorkContactNo;
    }

    public void setTenantWorkContactNo(String tenantWorkContactNo) {
        this.tenantWorkContactNo = tenantWorkContactNo;
    }

    @Column(name = "Mail_ID", length = 50)
    public String getMailId() {
        return this.mailId;
    }

    public void setMailId(String mailId) {
        this.mailId = mailId;
    }

    @Column(name = "Permanent_Address", length = 500)
    public String getPermanentAddress() {
        return this.permanentAddress;
    }

    public void setPermanentAddress(String permanentAddress) {
        this.permanentAddress = permanentAddress;
    }

    @Column(name = "Corresponding_Address", length = 500)
    public String getCorrespondingAddress() {
        return this.correspondingAddress;
    }

    public void setCorrespondingAddress(String correspondingAddress) {
        this.correspondingAddress = correspondingAddress;
    }

    @Column(name = "Sponsor_Address", length = 500)
    public String getSponsorAddress() {
        return this.sponsorAddress;
    }

    public void setSponsorAddress(String sponsorAddress) {
        this.sponsorAddress = sponsorAddress;
    }

    @Column(name = "Sponsor_PostalCode", length = 10)
    public String getSponsorPostalCode() {
        return this.sponsorPostalCode;
    }

    public void setSponsorPostalCode(String sponsorPostalCode) {
        this.sponsorPostalCode = sponsorPostalCode;
    }

    @Column(name = "Sponsor_PostBoxNo", length = 10)
    public String getSponsorPostBoxNo() {
        return this.sponsorPostBoxNo;
    }

    public void setSponsorPostBoxNo(String sponsorPostBoxNo) {
        this.sponsorPostBoxNo = sponsorPostBoxNo;
    }

    @Column(name = "Tenant_History", length = 500)
    public String getTenantHistory() {
        return this.tenantHistory;
    }

    public void setTenantHistory(String tenantHistory) {
        this.tenantHistory = tenantHistory;
    }

    @Column(name = "Remarks", length = 500)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "Asset_Name", length = 50)
    public String getAssetName() {
        return this.assetName;
    }

    public void setAssetName(String assetName) {
        this.assetName = assetName;
    }

    @Column(name = "Asset_Code", length = 50)
    public String getAssetCode() {
        return assetCode;
    }

    public void setAssetCode(String assetCode) {
        this.assetCode = assetCode;
    }

    @Column(name = "SubClassified_AssetName", length = 50)
    public String getSubClassifiedAssetName() {
        return this.subClassifiedAssetName;
    }

    public void setSubClassifiedAssetName(String subClassifiedAssetName) {
        this.subClassifiedAssetName = subClassifiedAssetName;
    }

    @Column(name = "Building_No", length = 50)
    public String getBuildingNo() {
        return this.buildingNo;
    }

    public void setBuildingNo(String buildingNo) {
        this.buildingNo = buildingNo;
    }

    @Column(name = "WaterUtility_BillNo", length = 50)
    public String getWaterUtilityBillNo() {
        return this.waterUtilityBillNo;
    }

    public void setWaterUtilityBillNo(String waterUtilityBillNo) {
        this.waterUtilityBillNo = waterUtilityBillNo;
    }

    @Column(name = "Area", length = 50)
    public String getArea() {
        return this.area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    @Column(name = "Block_No", length = 50)
    public String getBlockNo() {
        return this.blockNo;
    }

    public void setBlockNo(String blockNo) {
        this.blockNo = blockNo;
    }

    @Column(name = "Plot_No", length = 50)
    public String getPlotNo() {
        return this.plotNo;
    }

    public void setPlotNo(String plotNo) {
        this.plotNo = plotNo;
    }

    @Column(name = "Electric_BillNo", length = 50)
    public String getElectricBillNo() {
        return this.electricBillNo;
    }

    public void setElectricBillNo(String electricBillNo) {
        this.electricBillNo = electricBillNo;
    }

    @Column(name = "Way", length = 50)
    public String getWay() {
        return this.way;
    }

    public void setWay(String way) {
        this.way = way;
    }

    @Column(name = "Street_No", length = 50)
    public String getStreetNo() {
        return this.streetNo;
    }

    public void setStreetNo(String streetNo) {
        this.streetNo = streetNo;
    }

    @Column(name = "Postal_Code", length = 10)
    public String getPostalCode() {
        return this.postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    @Column(name = "Post_BoxNo", length = 10)
    public String getPostBoxNo() {
        return this.postBoxNo;
    }

    public void setPostBoxNo(String postBoxNo) {
        this.postBoxNo = postBoxNo;
    }

    @Column(name = "Contract_Code", length = 50)
    public String getContractCode() {
        return this.contractCode;
    }

    public void setContractCode(String contractCode) {
        this.contractCode = contractCode;
    }

    @Column(name = "Contract_Name", length = 50)
    public String getContractName() {
        return this.contractName;
    }

    public void setContractName(String contractName) {
        this.contractName = contractName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Starts_From", length = 19)
    public Date getStartsFrom() {
        return this.startsFrom;
    }

    public void setStartsFrom(Date startsFrom) {
        this.startsFrom = startsFrom;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "End_To", length = 19)
    public Date getEndTo() {
        return this.endTo;
    }

    public void setEndTo(Date endTo) {
        this.endTo = endTo;
    }

    @Column(name = "Contract_Attachment", columnDefinition = "MEDIUMBLOB")
    public byte[] getContractAttachment() {
        return this.contractAttachment;
    }

    public void setContractAttachment(byte[] contractAttachment) {
        this.contractAttachment = contractAttachment;
    }

    @Column(name = "contract_FileName")
    public String getContractFileName() {
        return contractFileName;
    }

    public void setContractFileName(String contractFileName) {
        this.contractFileName = contractFileName;
    }

    @Column(name = "Minimum_RentFixed", length = 50)
    public String getMinimumRentFixed() {
        return this.minimumRentFixed;
    }

    public void setMinimumRentFixed(String minimumRentFixed) {
        this.minimumRentFixed = minimumRentFixed;
    }

    @Column(name = "quotedrent_amount", length = 50)
    public String getQuotedRentAmount() {
        return quotedRentAmount;
    }

    public void setQuotedRentAmount(String quotedRentAmount) {
        this.quotedRentAmount = quotedRentAmount;
    }

//    @Column(name = "Actual_RentFixed", length = 50)
//    public String getActualRentFixed() {
//        return this.actualRentFixed;
//    }
//
//    public void setActualRentFixed(String actualRentFixed) {
//        this.actualRentFixed = actualRentFixed;
//    }

    @Column(name = "Billing_Cycle", length = 50)
    public String getBillingCycle() {
        return this.billingCycle;
    }

    public void setBillingCycle(String billingCycle) {
        this.billingCycle = billingCycle;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Due_Date", length = 19)
    public Date getDueDate() {
        return this.dueDate;
    }

    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    @Column(name = "Approver_Status", length = 50)
    public String getApproverStatus() {
        return approverStatus;
    }

    public void setApproverStatus(String approverStatus) {
        this.approverStatus = approverStatus;
    }

    @Column(name = "creation_From", length = 50)
    public String getCreationFrom() {
        return creationFrom;
    }

    public void setCreationFrom(String creationFrom) {
        this.creationFrom = creationFrom;
    }

    @Column(name = "Record_Status", length = 50)
    public String getRecordStatus() {
        return this.recordStatus;
    }

    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    @Column(name = "Approver1", length = 50)
    public String getApprover1() {
        return approver1;
    }

    public void setApprover1(String approver1) {
        this.approver1 = approver1;
    }

    @Column(name = "Approver_Remarks1", length = 500)
    public String getApproverRemarks1() {
        return approverRemarks1;
    }

    public void setApproverRemarks1(String approverRemarks1) {
        this.approverRemarks1 = approverRemarks1;
    }

    @Column(name = "Approver2", length = 50)
    public String getApprover2() {
        return approver2;
    }

    public void setApprover2(String approver2) {
        this.approver2 = approver2;
    }

    @Column(name = "Approver_Remarks2", length = 500)
    public String getApproverRemarks2() {
        return approverRemarks2;
    }

    public void setApproverRemarks2(String approverRemarks2) {
        this.approverRemarks2 = approverRemarks2;
    }

    @Column(name = "Attribute1", length = 50)
    public String getAttribute1() {
        return this.attribute1;
    }

    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    @Column(name = "Attribute2", length = 50)
    public String getAttribute2() {
        return this.attribute2;
    }

    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    @Column(name = "Attribute3", length = 50)
    public String getAttribute3() {
        return this.attribute3;
    }

    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    @Column(name = "Attribute4", length = 500)
    public String getAttribute4() {
        return this.attribute4;
    }

    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    @Column(name = "Attribute5", length = 500)
    public String getAttribute5() {
        return this.attribute5;
    }

    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    @Column(name = "Status", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Lastmodefied_Date", length = 19)
    public Date getLastmodefiedDate() {
        return this.lastmodefiedDate;
    }

    public void setLastmodefiedDate(Date lastmodefiedDate) {
        this.lastmodefiedDate = lastmodefiedDate;
    }

    @Column(name = "sub_asset_code", length = 60)
    public String getSubAssetCode() {
        return subAssetCode;
    }

    public void setSubAssetCode(String subAssetCode) {
        this.subAssetCode = subAssetCode;
    }

}
