package tenant.classes;
// Generated 14 Oct, 2016 11:56:12 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RevaluationOfAsset generated by hbm2java
 */
@Entity
@Table(name = "revaluation_of_asset", schema = "arete_tms"
)
public class RevaluationOfAsset implements java.io.Serializable {

    private Integer SNo;
    private String assetCode;
    private String assetName;
    private String subAssetCode;
    private String subAssetName;
    private String currentValueOfAsset;
    private String addSubValueOfAsset;
    private String newDepreciation;
    private String newLifeSpan;
    private String revaluedLeftOut;
    private String previousValueLeftOut;
    private String revaluationOfAsset;
    private Date startDate;
    private String status;
    private Date createdDate;
    private Date lastModifiedDate;
    private String reason;
    private String recordStatus;
    private String approvar1Remark;
    private String approvar2Remark;
    private String rejectedRemark;
    private String revaluationNo;

    public RevaluationOfAsset() {
    }

    public RevaluationOfAsset(String assetCode, String assetName, String subAssetCode, String subAssetName, String revaluationOfAsset, String addSubValueOfAsset, Date startDate, String currentValueOfAsset, String newDepreciation, String newLifeSpan, String previousValueLeftOut, String revaluedLeftOut, String status, Date createdDate, Date lastModifiedDate, String reason, String recordStatus, String revaluationNo) {
        this.assetCode = assetCode;
        this.subAssetCode = subAssetCode;
        this.assetName = assetName;
        this.subAssetName = subAssetName;
        this.currentValueOfAsset = currentValueOfAsset;
        this.addSubValueOfAsset = addSubValueOfAsset;
        this.newDepreciation = newDepreciation;
        this.newLifeSpan = newLifeSpan;
        this.revaluedLeftOut = revaluedLeftOut;
        this.previousValueLeftOut = previousValueLeftOut;
        this.revaluationOfAsset = revaluationOfAsset;
        this.startDate = startDate;
        this.status = status;
        this.createdDate = createdDate;
        this.lastModifiedDate = lastModifiedDate;
        this.reason = reason;
        this.recordStatus = recordStatus;
        this.revaluationNo = revaluationNo;

    }

    public RevaluationOfAsset(Integer sno, String assetCode, String assetName, String subAssetCode, String subAssetName, String revaluationOfAsset, String addSubValueOfAsset, Date startDate, String currentValueOfAsset, String newDepreciation, String newLifeSpan, String previousValueLeftOut, String revaluedLeftOut, String status, Date createdDate, Date lastModifiedDate, String reason, String recordStatus, String revaluationNo) {
        this.SNo = sno;
        this.assetCode = assetCode;
        this.subAssetCode = subAssetCode;
        this.assetName = assetName;
        this.subAssetName = subAssetName;
        this.currentValueOfAsset = currentValueOfAsset;
        this.addSubValueOfAsset = addSubValueOfAsset;
        this.newDepreciation = newDepreciation;
        this.newLifeSpan = newLifeSpan;
        this.revaluedLeftOut = revaluedLeftOut;
        this.previousValueLeftOut = previousValueLeftOut;
        this.revaluationOfAsset = revaluationOfAsset;
        this.startDate = startDate;
        this.status = status;
        this.createdDate = createdDate;
        this.lastModifiedDate = lastModifiedDate;
        this.reason = reason;
        this.recordStatus = recordStatus;
        this.revaluationNo = revaluationNo;

    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "s_no", unique = true, nullable = false)
    public Integer getSNo() {
        return this.SNo;
    }

    public void setSNo(Integer SNo) {
        this.SNo = SNo;
    }

    @Column(name = "Asset_Code", length = 60)
    public String getAssetCode() {
        return this.assetCode;
    }

    public void setAssetCode(String assetCode) {
        this.assetCode = assetCode;
    }

    @Column(name = "Asset_Name", length = 60)
    public String getAssetName() {
        return this.assetName;
    }

    public void setAssetName(String assetName) {
        this.assetName = assetName;
    }

    @Column(name = "Sub_Asset_Name", length = 60)
    public String getSubAssetName() {
        return this.subAssetName;
    }

    public void setSubAssetName(String subAssetName) {
        this.subAssetName = subAssetName;
    }

    @Column(name = "Sub_Asset_Code", length = 60)
    public String getSubAssetCode() {
        return this.subAssetCode;
    }

    public void setSubAssetCode(String subAssetCode) {
        this.subAssetCode = subAssetCode;
    }

    @Column(name = "Current_Value_Of_Asset", length = 60)
    public String getCurrentValueOfAsset() {
        return this.currentValueOfAsset;
    }

    @Column(name = "Revaluation_Of_Asset", length = 60)
    public String getRevaluationOfAsset() {
        return revaluationOfAsset;
    }

    public void setRevaluationOfAsset(String revaluationOfAsset) {
        this.revaluationOfAsset = revaluationOfAsset;
    }

    public void setCurrentValueOfAsset(String currentValueOfAsset) {
        this.currentValueOfAsset = currentValueOfAsset;
    }

    @Column(name = "Add_Sub_Value_Of_Asset", length = 60)
    public String getAddSubValueOfAsset() {
        return this.addSubValueOfAsset;
    }

    public void setAddSubValueOfAsset(String addSubValueOfAsset) {
        this.addSubValueOfAsset = addSubValueOfAsset;
    }

    @Column(name = "New_Depreciation", length = 60)
    public String getNewDepreciation() {
        return this.newDepreciation;
    }

    public void setNewDepreciation(String newDepreciation) {
        this.newDepreciation = newDepreciation;
    }

    @Column(name = "New_Life_Span", length = 60)
    public String getNewLifeSpan() {
        return this.newLifeSpan;
    }

    public void setNewLifeSpan(String newLifeSpan) {
        this.newLifeSpan = newLifeSpan;
    }

    @Column(name = "Revalued_Left_Out", length = 60)
    public String getRevaluedLeftOut() {
        return this.revaluedLeftOut;
    }

    public void setRevaluedLeftOut(String revaluedLeftOut) {
        this.revaluedLeftOut = revaluedLeftOut;
    }

    @Column(name = "Previous_Value_Left_Out", length = 60)
    public String getPreviousValueLeftOut() {
        return this.previousValueLeftOut;
    }

    public void setPreviousValueLeftOut(String previousValueLeftOut) {
        this.previousValueLeftOut = previousValueLeftOut;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "Start_Date", length = 60)
    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Column(name = "status", length = 60)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "createdDate", length = 10)
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "lastModifiedDate", length = 10)
    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    @Column(name = "reason", length = 60)
    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    @Column(name = "record_status", length = 60)
    public String getRecordStatus() {
        return recordStatus;
    }

    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    @Column(name = "approvar1_remark", length = 60)
    public String getApprovar1Remark() {
        return approvar1Remark;
    }

    public void setApprovar1Remark(String approvar1Remark) {
        this.approvar1Remark = approvar1Remark;
    }

    @Column(name = "approvar2_remark", length = 60)
    public String getApprovar2Remark() {
        return approvar2Remark;
    }

    public void setApprovar2Remark(String approvar2Remark) {
        this.approvar2Remark = approvar2Remark;
    }

    @Column(name = "rejected_remark", length = 60)
    public String getRejectedRemark() {
        return rejectedRemark;
    }

    public void setRejectedRemark(String rejectedRemark) {
        this.rejectedRemark = rejectedRemark;
    }

    @Column(name = "revaluation_no", length = 60)
    public String getRevaluationNo() {
        return revaluationNo;
    }

    public void setRevaluationNo(String revaluationNo) {
        this.revaluationNo = revaluationNo;
    }

}
