package tenant.classes;
// Generated 30 May, 2016 12:22:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RolePermission generated by hbm2java
 */
@Entity
@Table(name = "role_permission", schema = "arete_tms"
)
public class RolePermission implements java.io.Serializable {

    private Integer sno;
    private String orgId;
    private String departmentName;
    private String roleName;
    private String submoduleName;
    private String tabName;
    private String newEntry;
    private String edit;
    private String inactive;
    private String approve;
    private String review;
    private String status;
    private Date lastmodifiedDate;
    private String listUrl;

    public RolePermission() {
    }

    public RolePermission(String orgId, String departmentName, String roleName, String submoduleName,
            String tabName, String newEntry, String edit, String inactive, String approve,
            String review, String status, java.sql.Timestamp lastmodifiedDate, String listUrl) {
        this.orgId = orgId;
        this.departmentName = departmentName;
        this.roleName = roleName;
        this.submoduleName = submoduleName;
        this.tabName = tabName;
        this.newEntry = newEntry;
        this.edit = edit;
        this.inactive = inactive;
        this.approve = approve;
        this.review = review;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.listUrl = listUrl;
    }

    public RolePermission(Integer sno, String orgId, String departmentName, String roleName, String submoduleName,
            String tabName, String newEntry, String edit, String inactive, String approve, String review,
            String status, java.sql.Timestamp lastmodifiedDate) {
        this.sno = sno;
        this.orgId = orgId;
        this.departmentName = departmentName;
        this.roleName = roleName;
        this.submoduleName = submoduleName;
        this.tabName = tabName;
        this.newEntry = newEntry;
        this.edit = edit;
        this.inactive = inactive;
        this.approve = approve;
        this.review = review;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "SNO", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "ORG_ID", length = 50)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "DEPARTMENT_NAME", length = 50)
    public String getDepartmentName() {
        return this.departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    @Column(name = "ROLE_NAME", length = 50)
    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @Column(name = "SUBMODULE_NAME", length = 100)
    public String getSubmoduleName() {
        return this.submoduleName;
    }

    public void setSubmoduleName(String submoduleName) {
        this.submoduleName = submoduleName;
    }

    @Column(name = "TAB_NAME", length = 100)
    public String getTabName() {
        return this.tabName;
    }

    public void setTabName(String tabName) {
        this.tabName = tabName;
    }

    @Column(name = "NEW_ENTRY", length = 100)
    public String getNewEntry() {
        return this.newEntry;
    }

    public void setNewEntry(String newEntry) {
        this.newEntry = newEntry;
    }

    @Column(name = "EDIT", length = 20)
    public String getEdit() {
        return this.edit;
    }

    public void setEdit(String edit) {
        this.edit = edit;
    }

    @Column(name = "INACTIVE", length = 20)
    public String getInactive() {
        return this.inactive;
    }

    public void setInactive(String inactive) {
        this.inactive = inactive;
    }

    @Column(name = "APPROVE", length = 20)
    public String getApprove() {
        return this.approve;
    }

    public void setApprove(String approve) {
        this.approve = approve;
    }

    @Column(name = "REVIEW", length = 20)
    public String getReview() {
        return this.review;
    }

    public void setReview(String review) {
        this.review = review;
    }

    @Column(name = "STATUS", length = 20)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTMODIFIED_DATE", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Column(name = "LIST_URL", length = 100)
    public String getListUrl() {
        return this.listUrl;
    }

    public void setListUrl(String listUrl) {
        this.listUrl = listUrl;
    }

}
