package tenant.classes;
// Generated 14 Oct, 2016 11:56:12 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SplitAsset generated by hbm2java
 */
@Entity
@Table(name = "split_asset", schema = "arete_tms"
)
public class SplitAsset implements java.io.Serializable {

    private Integer SNo;
    private String assetCode;
    private String assetName;
    private String subAssetCode;
    private String subAssetName;
    private String assetCurrentValue;
    private String assetSplittingProportionateValue1;
    private String assetSplittingProportionateValue2;
    private String purchaseValue;
    private String newAssetCode1;
    private String newAssetCode2;
    private String depreciationForAsset1;
    private String depreciationForAsset2;
    private String totalValueLeftoutAsset1;
    private String totalValueLeftoutAsset2;
    private String currentValueOfAsset1;
    private String currentValueOfAsset2;
    private String status;
    private Date createdDate;
    private Date lastModifiedDate;

    public SplitAsset() {
    }

    public SplitAsset(String assetCode, String assetName, String subAssetCode, String subAssetName, String assetSplittingProportionateValue1, String assetSplittingProportionateValue2, String assetCurrentValue, String currentValueOfAsset1, String currentValueOfAsset2, String depreciationForAsset1, String depreciationForAsset2, String totalValueLeftoutAsset1, String totalValueLeftoutAsset2, String newAssetCode1, String newAssetCode2, String purchaseValue, String status, Date createdDate, Date lastModifiedDate) {
        this.assetCode = assetCode;
        this.subAssetCode = subAssetCode;
        this.assetName = assetName;
        this.subAssetName = subAssetName;
        this.assetCurrentValue = assetCurrentValue;
        this.assetSplittingProportionateValue1 = assetSplittingProportionateValue1;
        this.assetSplittingProportionateValue2 = assetSplittingProportionateValue2;
        this.purchaseValue = purchaseValue;
        this.newAssetCode1 = newAssetCode1;
        this.newAssetCode2 = newAssetCode2;
        this.currentValueOfAsset1 = currentValueOfAsset1;
        this.currentValueOfAsset2 = currentValueOfAsset2;
        this.depreciationForAsset1 = depreciationForAsset1;
        this.depreciationForAsset2 = depreciationForAsset2;
        this.totalValueLeftoutAsset1 = totalValueLeftoutAsset1;
        this.totalValueLeftoutAsset2 = totalValueLeftoutAsset2;
        this.status = status;
        this.createdDate = createdDate;
        this.lastModifiedDate = lastModifiedDate;

    }

    public SplitAsset(Integer sno, String assetCode, String assetName, String subAssetCode, String subAssetName, String assetSplittingProportionateValue1, String assetSplittingProportionateValue2, String assetCurrentValue, String currentValueOfAsset1, String currentValueOfAsset2, String depreciationForAsset1, String depreciationForAsset2, String totalValueLeftoutAsset1, String totalValueLeftoutAsset2, String newAssetCode1, String newAssetCode2, String purchaseValue, String status, Date createdDate, Date lastModifiedDate) {
        this.SNo = sno;
        this.assetCode = assetCode;
        this.subAssetCode = subAssetCode;
        this.assetName = assetName;
        this.subAssetName = subAssetName;
        this.assetCurrentValue = assetCurrentValue;
        this.assetSplittingProportionateValue1 = assetSplittingProportionateValue1;
        this.assetSplittingProportionateValue2 = assetSplittingProportionateValue2;
        this.purchaseValue = purchaseValue;
        this.newAssetCode1 = newAssetCode1;
        this.newAssetCode2 = newAssetCode2;
        this.currentValueOfAsset1 = currentValueOfAsset1;
        this.currentValueOfAsset2 = currentValueOfAsset2;
        this.depreciationForAsset1 = depreciationForAsset1;
        this.depreciationForAsset2 = depreciationForAsset2;
        this.totalValueLeftoutAsset1 = totalValueLeftoutAsset1;
        this.totalValueLeftoutAsset2 = totalValueLeftoutAsset2;
        this.status = status;
        this.createdDate = createdDate;
        this.lastModifiedDate = lastModifiedDate;

    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "s_no", unique = true, nullable = false)
    public Integer getSNo() {
        return this.SNo;
    }

    public void setSNo(Integer SNo) {
        this.SNo = SNo;
    }

    @Column(name = "Asset_Code", length = 60)
    public String getAssetCode() {
        return this.assetCode;
    }

    public void setAssetCode(String assetCode) {
        this.assetCode = assetCode;
    }

    @Column(name = "Asset_Name", length = 60)
    public String getAssetName() {
        return this.assetName;
    }

    public void setAssetName(String assetName) {
        this.assetName = assetName;
    }

    @Column(name = "Sub_Asset_Name", length = 60)
    public String getSubAssetName() {
        return this.subAssetName;
    }

    public void setSubAssetName(String subAssetName) {
        this.subAssetName = subAssetName;
    }

    @Column(name = "Sub_Asset_Code", length = 60)
    public String getSubAssetCode() {
        return this.subAssetCode;
    }

    public void setSubAssetCode(String subAssetCode) {
        this.subAssetCode = subAssetCode;
    }

    @Column(name = "Asset_Current_Value", length = 60)
    public String getAssetCurrentValue() {
        return this.assetCurrentValue;
    }

    public void setAssetCurrentValue(String assetCurrentValue) {
        this.assetCurrentValue = assetCurrentValue;
    }

    @Column(name = "Asset_Splitting_Proportionate_value_1", length = 60)
    public String getAssetSplittingProportionateValue1() {
        return this.assetSplittingProportionateValue1;
    }

    public void setAssetSplittingProportionateValue1(String assetSplittingProportionateValue1) {
        this.assetSplittingProportionateValue1 = assetSplittingProportionateValue1;
    }

    @Column(name = "Asset_Splitting_Proportionate_value_2", length = 60)
    public String getAssetSplittingProportionateValue2() {
        return this.assetSplittingProportionateValue2;
    }

    public void setAssetSplittingProportionateValue2(String assetSplittingProportionateValue2) {
        this.assetSplittingProportionateValue2 = assetSplittingProportionateValue2;
    }

    @Column(name = "Purchase_value", length = 60)
    public String getPurchaseValue() {
        return this.purchaseValue;
    }

    public void setPurchaseValue(String purchaseValue) {
        this.purchaseValue = purchaseValue;
    }

    @Column(name = "New_Asset_Code_1", length = 60)
    public String getNewAssetCode1() {
        return this.newAssetCode1;
    }

    public void setNewAssetCode1(String newAssetCode1) {
        this.newAssetCode1 = newAssetCode1;
    }

    @Column(name = "New_Asset_Code_2", length = 60)
    public String getNewAssetCode2() {
        return this.newAssetCode2;
    }

    public void setNewAssetCode2(String newAssetCode2) {
        this.newAssetCode2 = newAssetCode2;
    }

    @Column(name = "Current_Value_Of_Asset_1", length = 60)
    public String getCurrentValueOfAsset1() {
        return currentValueOfAsset1;
    }

    public void setCurrentValueOfAsset1(String currentValueOfAsset1) {
        this.currentValueOfAsset1 = currentValueOfAsset1;
    }

    @Column(name = "Current_Value_Of_Asset_2", length = 60)
    public String getCurrentValueOfAsset2() {
        return currentValueOfAsset2;
    }

    public void setCurrentValueOfAsset2(String currentValueOfAsset2) {
        this.currentValueOfAsset2 = currentValueOfAsset2;
    }

    @Column(name = "Depreciation_For_Asset_1", length = 60)
    public String getDepreciationForAsset1() {
        return this.depreciationForAsset1;
    }

    public void setDepreciationForAsset1(String depreciationForAsset1) {
        this.depreciationForAsset1 = depreciationForAsset1;
    }

    @Column(name = "Depreciation_For_Asset_2", length = 60)
    public String getDepreciationForAsset2() {
        return this.depreciationForAsset2;
    }

    public void setDepreciationForAsset2(String depreciationForAsset2) {
        this.depreciationForAsset2 = depreciationForAsset2;
    }

    @Column(name = "Total_Value_Leftout_Asset_1", length = 60)
    public String getTotalValueLeftoutAsset1() {
        return this.totalValueLeftoutAsset1;
    }

    public void setTotalValueLeftoutAsset1(String totalValueLeftoutAsset1) {
        this.totalValueLeftoutAsset1 = totalValueLeftoutAsset1;
    }

    @Column(name = "Total_Value_Leftout_Asset_2", length = 60)
    public String getTotalValueLeftoutAsset2() {
        return this.totalValueLeftoutAsset2;
    }

    public void setTotalValueLeftoutAsset2(String totalValueLeftoutAsset2) {
        this.totalValueLeftoutAsset2 = totalValueLeftoutAsset2;
    }

    @Column(name = "status", length = 60)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "createdDate", length = 10)
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "lastModifiedDate", length = 10)
    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

}
