package tenant.classes;
// Generated 7 Oct, 2016 8:41:21 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SupplierMaster generated by hbm2java
 */
@Entity
@Table(name = "supplier_master", schema = "arete_tms"
)
public class SupplierMaster implements java.io.Serializable {

    private Integer sno;
    private String orgId;
    private String userId;
    private String supplierCode;
    private String supplierName;
    private String supplierAddress;
    private String city;
    private String state;
    private String pincode;
    private String supplierContNum;
    private String mailId;
    private String supplierDesc;
    private String bankName;
    private String accountNumber;
    private String ifsccode;
    private String branchname;
    private String address;
    private String emailid;
    private String contNum;
    private Date creationDate;
    private String status;//deliveryTerms
    private String paymentTerms;
    private String deliveryTerms;
    private String recordStatus;
    private Date lastmodifiedDate;

    public SupplierMaster() {
    }

    public SupplierMaster(String supplierCode) {
        this.supplierCode = supplierCode;
    }

    public SupplierMaster(String orgId, String userId, String supplierCode, String supplierName, String supplierAddress, String city, String state, String pincode, String supplierContNum, String mailId, String supplierDesc, String bankName, String accountNumber, String ifsccode, String branchname, String address, String emailid, String contNum, Date creationDate, String status, Date lastmodifiedDate,String paymentTerms,String deliveryTerms) {
        this.orgId = orgId;
        this.userId = userId;
        this.supplierCode = supplierCode;
        this.supplierName = supplierName;
        this.supplierAddress = supplierAddress;
        this.city = city;
        this.state = state;
        this.pincode = pincode;
        this.supplierContNum = supplierContNum;
        this.mailId = mailId;
        this.supplierDesc = supplierDesc;
        this.bankName = bankName;
        this.accountNumber = accountNumber;
        this.ifsccode = ifsccode;
        this.branchname = branchname;
        this.address = address;
        this.emailid = emailid;
        this.contNum = contNum;
        this.creationDate = creationDate;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.deliveryTerms = deliveryTerms;
        this.paymentTerms = paymentTerms;
        
    }

    public SupplierMaster(Integer sno, String orgId, String userId, String supplierCode, String supplierName, String supplierAddress, String city, String state, String pincode, String supplierContNum, String mailId, String supplierDesc, String bankName, String accountNumber, String ifsccode, String branchname, String address, String emailid, String contNum, Date creationDate, String status, Date lastmodifiedDate,String paymentTerms,String deliveryTerms) {
        this.sno = sno;
        this.orgId = orgId;
        this.userId = userId;
        this.supplierCode = supplierCode;
        this.supplierName = supplierName;
        this.supplierAddress = supplierAddress;
        this.city = city;
        this.state = state;
        this.pincode = pincode;
        this.supplierContNum = supplierContNum;
        this.mailId = mailId;
        this.supplierDesc = supplierDesc;
        this.bankName = bankName;
        this.accountNumber = accountNumber;
        this.ifsccode = ifsccode;
        this.branchname = branchname;
        this.address = address;
        this.emailid = emailid;
        this.contNum = contNum;
        this.creationDate = creationDate;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.deliveryTerms = deliveryTerms;
        this.paymentTerms = paymentTerms;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "SNO", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "ORG_ID", length = 50)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "USER_ID", length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "SUPPLIER_CODE", nullable = false, length = 50)
    public String getSupplierCode() {
        return this.supplierCode;
    }

    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode;
    }

    @Column(name = "SUPPLIER_NAME", length = 50)
    public String getSupplierName() {
        return this.supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    @Column(name = "SUPPLIER_ADDRESS", length = 250)
    public String getSupplierAddress() {
        return this.supplierAddress;
    }

    public void setSupplierAddress(String supplierAddress) {
        this.supplierAddress = supplierAddress;
    }

    @Column(name = "BANK_NAME", length = 100)
    public String getBankName() {
        return this.bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    @Column(name = "ACCOUNT_NUMBER", length = 50)
    public String getAccountNumber() {
        return this.accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }
@Column(name = "PAYMENT_TERMS", length = 250)
    public String getPaymentTerms() {
        return paymentTerms;
    }
    public void setPaymentTerms(String paymentTerms) {
        this.paymentTerms = paymentTerms;
    }
    @Column(name = "SUPPLIER_DESC")
    public String getSupplierDesc() {
        return this.supplierDesc;
    }

    public void setSupplierDesc(String supplierDesc) {
        this.supplierDesc = supplierDesc;
    }

    @Column(name = "SUPPLIER_CONT_NUM", length = 50)
    public String getSupplierContNum() {
        return this.supplierContNum;
    }

    public void setSupplierContNum(String supplierContNum) {
        this.supplierContNum = supplierContNum;
    }

    @Column(name = "MAIL_ID", length = 50)
    public String getMailId() {
        return this.mailId;
    }

    public void setMailId(String mailId) {
        this.mailId = mailId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATION_DATE", length = 19)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
    @Column(name = "record_status", length = 50)
    public String getRecordStatus() {
        return this.recordStatus;
    }

    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTMODIFIED_DATE", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Column(name = "city", length = 50)
    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "state", length = 50)
    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "pin_code", length = 50)
    public String getPincode() {
        return pincode;
    }

    public void setPincode(String pincode) {
        this.pincode = pincode;
    }

    @Column(name = "ifsc_code", length = 50)
    public String getIfsccode() {
        return ifsccode;
    }

    public void setIfsccode(String ifsccode) {
        this.ifsccode = ifsccode;
    }

    @Column(name = "branch_name", length = 50)
    public String getBranchname() {
        return branchname;
    }

    public void setBranchname(String branchname) {
        this.branchname = branchname;
    }

    @Column(name = "address", length = 250)
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "email_id", length = 50)
    public String getEmailid() {
        return emailid;
    }

    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }

    @Column(name = "cont_Number", length = 50)
    public String getContNum() {
        return contNum;
    }

    public void setContNum(String contNum) {
        this.contNum = contNum;
    }
    @Column(name = "DELIVERY_TERMS", length = 100)
    public String getDeliveryTerms() {
        return deliveryTerms;
    }
    public void setDeliveryTerms(String deliveryTerms) {
        this.deliveryTerms = deliveryTerms;
    }

}
