/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tenant.classes;

// Generated Mar 16, 2016 10:57:11 AM by Hibernate Tools 4.3.1

import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SupplierEnquiry generated by hbm2java
 */
@Entity
@Table(name = "supplier_enquiry", schema = "arete_tms"
)
public class SupplierEnquiry implements java.io.Serializable {

    private Integer SNo;
    private String userId;
    private String orgId;
    private String enquiriesNo;
    private Date enquiriesDate;
    private String divisionName;
    private String projectCode;
    private String projectName;
    private String department;
    private String prNo;
    private Integer prSno;
    private Date prDate;
    private String purchaseType;
    private String itemCategory;
    private String itemSubCategory;
    private String itemCode;
    private String itemName;
    private String description;
    private String itemSpecification;
    private String unit;
    private Double quantity;
    private String enquiryRemarks;
    private Date requiredDate;
    private String deliveryLocation;
    private String supplierName;
    private String supplierCode;
    private String supplierMailId;
    private String recordStatus;
    private String status;
    private java.sql.Timestamp lastmodifiedDate;

    public SupplierEnquiry() {
    }

    public SupplierEnquiry(String userId, String orgId, String enquiriesNo, Date enquiriesDate, String divisionName, String projectCode, String projectName, String department, String prNo, Integer prSno, Date prDate, String purchaseType, String itemCategory, String itemSubCategory, String itemCode, String itemName, String description, String itemSpecification, String unit, Double quantity, String enquiryRemarks, Date requiredDate, String deliveryLocation, String supplierMailId, String recordStatus, String status, Timestamp lastmodifiedDate) {
        this.userId = userId;
        this.orgId = orgId;
        this.enquiriesNo = enquiriesNo;
        this.enquiriesDate = enquiriesDate;
        this.divisionName = divisionName;
        this.projectCode = projectCode;
        this.projectName = projectName;
        this.department = department;
        this.prNo = prNo;
        this.prSno = prSno;
        this.prDate = prDate;
        this.purchaseType = purchaseType;
        this.itemCategory = itemCategory;
        this.itemSubCategory = itemSubCategory;
        this.itemCode = itemCode;
        this.itemName = itemName;
        this.description = description;
        this.itemSpecification = itemSpecification;
        this.unit = unit;
        this.quantity = quantity;
        this.enquiryRemarks = enquiryRemarks;
        this.requiredDate = requiredDate;
        this.deliveryLocation = deliveryLocation;
        this.supplierMailId = supplierMailId;
        this.recordStatus = recordStatus;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "supplierEnq_id_seq")
    @SequenceGenerator(name = "supplierEnq_id_seq", sequenceName = "supplierEnq_seq", allocationSize = 1)
    @Column(name = "s_no", unique = true, nullable = false, precision = 22, scale = 0)
    public Integer getSNo() {
        return this.SNo;
    }

    public void setSNo(Integer SNo) {
        this.SNo = SNo;
    }

    @Column(name = "user_id", length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "org_id", length = 50)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "enquiries_no", length = 100)
    public String getEnquiriesNo() {
        return this.enquiriesNo;
    }

    public void setEnquiriesNo(String enquiriesNo) {
        this.enquiriesNo = enquiriesNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "enquiries_date", length = 7)
    public Date getEnquiriesDate() {
        return this.enquiriesDate;
    }

    public void setEnquiriesDate(Date enquiriesDate) {
        this.enquiriesDate = enquiriesDate;
    }

    @Column(name = "division_name", length = 60)
    public String getDivisionName() {
        return this.divisionName;
    }

    public void setDivisionName(String divisionName) {
        this.divisionName = divisionName;
    }

    @Column(name = "project_code", length = 100)
    public String getProjectCode() {
        return this.projectCode;
    }

    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    @Column(name = "project_name", length = 100)
    public String getProjectName() {
        return this.projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    @Column(name = "department", length = 100)
    public String getDepartment() {
        return this.department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @Column(name = "pr_no", length = 100)
    public String getPrNo() {
        return this.prNo;
    }

    public void setPrNo(String prNo) {
        this.prNo = prNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "pr_date", length = 7)
    public Date getPrDate() {
        return this.prDate;
    }

    public void setPrDate(Date prDate) {
        this.prDate = prDate;
    }

    @Column(name = "purchase_type", length = 50)
    public String getPurchaseType() {
        return this.purchaseType;
    }

    public void setPurchaseType(String purchaseType) {
        this.purchaseType = purchaseType;
    }

    @Column(name = "item_category", length = 50)
    public String getItemCategory() {
        return this.itemCategory;
    }

    public void setItemCategory(String itemCategory) {
        this.itemCategory = itemCategory;
    }

    @Column(name = "item_sub_category", length = 50)
    public String getItemSubCategory() {
        return this.itemSubCategory;
    }

    public void setItemSubCategory(String itemSubCategory) {
        this.itemSubCategory = itemSubCategory;
    }

    @Column(name = "item_code", nullable = false, length = 100)
    public String getItemCode() {
        return this.itemCode;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    @Column(name = "item_name", length = 250)
    public String getItemName() {
        return this.itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    @Column(name = "description", length = 250)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "unit", length = 50)
    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    @Column(name = "quantity", precision = 126, scale = 0)
    public Double getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }

    @Column(name = "enquiry_remarks", length = 200)
    public String getEnquiryRemarks() {
        return this.enquiryRemarks;
    }

    public void setEnquiryRemarks(String enquiryRemarks) {
        this.enquiryRemarks = enquiryRemarks;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "required_date", length = 7)
    public Date getRequiredDate() {
        return this.requiredDate;
    }

    public void setRequiredDate(Date requiredDate) {
        this.requiredDate = requiredDate;
    }

    @Column(name = "delivery_location", length = 200)
    public String getDeliveryLocation() {
        return this.deliveryLocation;
    }

    public void setDeliveryLocation(String deliveryLocation) {
        this.deliveryLocation = deliveryLocation;
    }

    @Column(name = "supplier_mail_id", length = 80)
    public String getSupplierMailId() {
        return this.supplierMailId;
    }

    public void setSupplierMailId(String supplierMailId) {
        this.supplierMailId = supplierMailId;
    }

    @Column(name = "status", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "lastmodified_date")
    public java.sql.Timestamp getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(java.sql.Timestamp lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Column(name = "record_status", length = 100)
    public String getRecordStatus() {
        return this.recordStatus;
    }

    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    @Column(name = "supplier_name", length = 100)
    public String getSupplierName() {
        return this.supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    @Column(name = "supplier_code", length = 100)
    public String getSupplierCode() {
        return this.supplierCode;
    }

    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode;
    }

    @Column(name = "pr_sno", precision = 22, scale = 0)
    public Integer getPrSno() {
        return this.prSno;
    }

    public void setPrSno(Integer prSno) {
        this.prSno = prSno;
    }

    @Column(name = "item_specification", length = 220)
    public String getItemSpecification() {
        return this.itemSpecification;
    }

    public void setItemSpecification(String itemSpecification) {
        this.itemSpecification = itemSpecification;
    }

}
