/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tenant.classes;

// Generated Mar 17, 2016 5:38:37 PM by Hibernate Tools 4.3.1

import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SupplierQuotation generated by hbm2java
 */
@Entity
@Table(name = "supplier_quotation", schema = "arete_tms"
)
public class SupplierQuotation implements java.io.Serializable {

    private Integer SNo;
    private String userId;
    private String orgId;
    private String enquiriesNo;
    private Date enquiriesDate;
    private String divisionName;
    private String department;
    private String projectCode;
    private String projectName;
    private String prNo;
    private Date prDate;
    private String purchaseType;
    private String supplierCode;
    private String supplierName;
    private String supplierEmail;
    private String supplierAddress;
    private String quotationNo;
    private Date quotationDate;
    private String paymentTerms;
    private String deliveryTerms;
    private String specialSpecificationDetails;
    private String itemCategory;
    private String itemSubCategory;
    private String itemCode;
    private String itemName;
    private String description;
    private String unit;
    private Double quantity;
    private String deliveryLocation;
    private Date deliveryDate;
    private Double discount;
    private Double unitPrice;
    private Double totalPrice;
    private Integer prSno;
    private Integer enqSno;
    private String reviewerName;
    private String reviewerRecordStatus;
    private String reviewerRemarks;
    private Date reviewerDate;
    private String approverName;
    private String approverRemarks;
    private String approverRecordStatus;
    private Date approverDate;
    private String status;
    private java.sql.Timestamp lastmodifiedDate;
    private String recordStatus;
    private byte[] attachment;
    private String fileName;

    public SupplierQuotation() {
    }

    public SupplierQuotation(String userId, String orgId, String enquiriesNo, Date enquiriesDate, String divisionName, String department, String projectCode, String projectName, String prNo, Date prDate, String purchaseType, String supplierCode, String supplierName, String supplierEmail, String supplierAddress, String quotationNo, Date quotationDate, String paymentTerms, String deliveryTerms, String specialSpecificationDetails, String itemCategory, String itemSubCategory, String itemCode, String itemName, String description, String unit, Double quantity, String deliveryLocation, Date deliveryDate, Double discount, Double unitPrice, Double totalPrice, Integer prSno, Integer enqSno, String status, Timestamp lastmodifiedDate, String recordStatus) {
        this.userId = userId;
        this.orgId = orgId;
        this.enquiriesNo = enquiriesNo;
        this.enquiriesDate = enquiriesDate;
        this.divisionName = divisionName;
        this.department = department;
        this.projectCode = projectCode;
        this.projectName = projectName;
        this.prNo = prNo;
        this.prDate = prDate;
        this.purchaseType = purchaseType;
        this.supplierCode = supplierCode;
        this.supplierName = supplierName;
        this.supplierEmail = supplierEmail;
        this.supplierAddress = supplierAddress;
        this.quotationNo = quotationNo;
        this.quotationDate = quotationDate;
        this.paymentTerms = paymentTerms;
        this.deliveryTerms = deliveryTerms;
        this.specialSpecificationDetails = specialSpecificationDetails;
        this.itemCategory = itemCategory;
        this.itemSubCategory = itemSubCategory;
        this.itemCode = itemCode;
        this.itemName = itemName;
        this.description = description;
        this.unit = unit;
        this.quantity = quantity;
        this.deliveryLocation = deliveryLocation;
        this.deliveryDate = deliveryDate;
        this.discount = discount;
        this.unitPrice = unitPrice;
        this.totalPrice = totalPrice;
        this.prSno = prSno;
        this.enqSno = enqSno;
        this.status = status;
        this.lastmodifiedDate = lastmodifiedDate;
        this.recordStatus = recordStatus;
        
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "supplierQuot_id_seq")
    @SequenceGenerator(name = "supplierQuot_id_seq", sequenceName = "supplierQuot_seq", allocationSize = 1)
    @Column(name = "s_no", unique = true, nullable = false, precision = 38, scale = 0)
    public Integer getSNo() {
        return this.SNo;
    }

    public void setSNo(Integer SNo) {
        this.SNo = SNo;
    }

    @Column(name = "user_id", nullable = false, length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "org_id", nullable = false, length = 50)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "enquiries_no", nullable = false, length = 50)
    public String getEnquiriesNo() {
        return this.enquiriesNo;
    }

    public void setEnquiriesNo(String enquiriesNo) {
        this.enquiriesNo = enquiriesNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "enquiries_date", nullable = false, length = 7)
    public Date getEnquiriesDate() {
        return this.enquiriesDate;
    }

    public void setEnquiriesDate(Date enquiriesDate) {
        this.enquiriesDate = enquiriesDate;
    }

    @Column(name = "division_name", length = 50)
    public String getDivisionName() {
        return this.divisionName;
    }

    public void setDivisionName(String divisionName) {
        this.divisionName = divisionName;
    }

    @Column(name = "department", length = 50)
    public String getDepartment() {
        return this.department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @Column(name = "project_code", length = 100)
    public String getProjectCode() {
        return this.projectCode;
    }

    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    @Column(name = "project_name", length = 100)
    public String getProjectName() {
        return this.projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    @Column(name = "pr_no", nullable = false, length = 50)
    public String getPrNo() {
        return this.prNo;
    }

    public void setPrNo(String prNo) {
        this.prNo = prNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "pr_date", length = 7)
    public Date getPrDate() {
        return this.prDate;
    }

    public void setPrDate(Date prDate) {
        this.prDate = prDate;
    }

    @Column(name = "purchase_type", length = 100)
    public String getPurchaseType() {
        return this.purchaseType;
    }

    public void setPurchaseType(String purchaseType) {
        this.purchaseType = purchaseType;
    }

    @Column(name = "supplier_name", length = 120)
    public String getSupplierName() {
        return this.supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    @Column(name = "supplier_address", length = 220)
    public String getSupplierAddress() {
        return this.supplierAddress;
    }

    public void setSupplierAddress(String supplierAddress) {
        this.supplierAddress = supplierAddress;
    }

    @Column(name = "quotation_no", length = 100)
    public String getQuotationNo() {
        return this.quotationNo;
    }

    public void setQuotationNo(String quotationNo) {
        this.quotationNo = quotationNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "quotation_date", length = 7)
    public Date getQuotationDate() {
        return this.quotationDate;
    }

    public void setQuotationDate(Date quotationDate) {
        this.quotationDate = quotationDate;
    }

    @Column(name = "payment_terms", length = 80)
    public String getPaymentTerms() {
        return this.paymentTerms;
    }

    public void setPaymentTerms(String paymentTerms) {
        this.paymentTerms = paymentTerms;
    }

    @Column(name = "delivery_terms", length = 80)
    public String getDeliveryTerms() {
        return this.deliveryTerms;
    }

    public void setDeliveryTerms(String deliveryTerms) {
        this.deliveryTerms = deliveryTerms;
    }

    @Column(name = "special_specification_details", length = 120)
    public String getSpecialSpecificationDetails() {
        return this.specialSpecificationDetails;
    }

    public void setSpecialSpecificationDetails(String specialSpecificationDetails) {
        this.specialSpecificationDetails = specialSpecificationDetails;
    }

    @Column(name = "item_category", length = 100)
    public String getItemCategory() {
        return this.itemCategory;
    }

    public void setItemCategory(String itemCategory) {
        this.itemCategory = itemCategory;
    }

    @Column(name = "item_sub_category", length = 100)
    public String getItemSubCategory() {
        return this.itemSubCategory;
    }

    public void setItemSubCategory(String itemSubCategory) {
        this.itemSubCategory = itemSubCategory;
    }

    @Column(name = "item_name", length = 250)
    public String getItemName() {
        return this.itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    @Column(name = "description", length = 250)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "unit", length = 50)
    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    @Column(name = "quantity", precision = 126, scale = 0)
    public Double getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "delivery_date", length = 7)
    public Date getDeliveryDate() {
        return this.deliveryDate;
    }

    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    @Column(name = "discount", precision = 126, scale = 0)
    public Double getDiscount() {
        return this.discount;
    }

    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    @Column(name = "unit_price", precision = 126, scale = 0)
    public Double getUnitPrice() {
        return this.unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    @Column(name = "total_price", precision = 126, scale = 0)
    public Double getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    @Column(name = "status", nullable = false, length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "lastmodified_date", nullable = false)
    public java.sql.Timestamp getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(java.sql.Timestamp lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Column(name = "record_status", length = 100)
    public String getRecordStatus() {
        return this.recordStatus;
    }

    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    @Column(name = "supplier_code", length = 100)
    public String getSupplierCode() {
        return this.supplierCode;
    }

    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode;
    }

    @Column(name = "item_code", length = 100)
    public String getItemCode() {
        return this.itemCode;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    @Column(name = "pr_sno", precision = 22, scale = 0)
    public Integer getPrSno() {
        return this.prSno;
    }

    public void setPrSno(Integer prSno) {
        this.prSno = prSno;
    }

    @Column(name = "enq_sno", precision = 22, scale = 0)
    public Integer getEnqSno() {
        return this.enqSno;
    }

    public void setEnqSno(Integer enqSno) {
        this.enqSno = enqSno;
    }

    @Column(name = "approver_name", length = 50)
    public String getApproverName() {
        return this.approverName;
    }

    public void setApproverName(String approverName) {
        this.approverName = approverName;
    }

    @Column(name = "approver_remarks", length = 2000)
    public String getApproverRemarks() {
        return this.approverRemarks;
    }

    public void setApproverRemarks(String approverRemarks) {
        this.approverRemarks = approverRemarks;
    }

    @Column(name = "approver_record_status", length = 100)
    public String getApproverRecordStatus() {
        return this.approverRecordStatus;
    }

    public void setApproverRecordStatus(String approverRecordStatus) {
        this.approverRecordStatus = approverRecordStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "approver_date", length = 20)
    public Date getApproverDate() {
        return this.approverDate;
    }

    public void setApproverDate(Date approverDate) {
        this.approverDate = approverDate;
    }

    @Column(name = "reviewer_name", length = 100)
    public String getReviewerName() {
        return this.reviewerName;
    }

    public void setReviewerName(String reviewerName) {
        this.reviewerName = reviewerName;
    }

    @Column(name = "reviewer_record_status", length = 100)
    public String getReviewerRecordStatus() {
        return this.reviewerRecordStatus;
    }

    public void setReviewerRecordStatus(String reviewerRecordStatus) {
        this.reviewerRecordStatus = reviewerRecordStatus;
    }

    @Column(name = "reviewer_remarks", length = 220)
    public String getReviewerRemarks() {
        return this.reviewerRemarks;
    }

    public void setReviewerRemarks(String reviewerRemarks) {
        this.reviewerRemarks = reviewerRemarks;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "reviewer_date", length = 20)
    public Date getReviewerDate() {
        return this.reviewerDate;
    }

    public void setReviewerDate(Date reviewerDate) {
        this.reviewerDate = reviewerDate;
    }

    @Column(name = "supplier_email", length = 120)
    public String getSupplierEmail() {
        return supplierEmail;
    }

    public void setSupplierEmail(String supplierEmail) {
        this.supplierEmail = supplierEmail;
    }

    @Column(name = "delivery_location", length = 200)
    public String getDeliveryLocation() {
        return this.deliveryLocation;
    }

    public void setDeliveryLocation(String deliveryLocation) {
        this.deliveryLocation = deliveryLocation;
    }

    @Column(name = "attachment", columnDefinition = "blob")
    public byte[] getAttachment() {
        return this.attachment;
    }

    public void setAttachment(byte[] attachment) {
        this.attachment = attachment;
    }

    @Column(name = "file_name", length = 100)
    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
}
