package tenant.classes;
// Generated 30 May, 2016 12:22:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserRegistration generated by hbm2java
 */
@Entity
@Table(name = "user_registration", schema = "arete_tms"
)  
public class UserRegistration implements java.io.Serializable {

    private Integer SNo;
    private String userId;
    private String userFName;
    private String userLName;
    private String password;
    private Date passwordExpiry;
    private Integer orgId;
    private String status;
    private Date lastmodifiedDate;
    private String departmentName;
    private String roleName;
    private String orgName;
    private String email;
    private String mobilenumber;

    public UserRegistration() {
    }

    public UserRegistration(Integer orgId, String orgName, String departmentName, String roleName, String userId,
            String userFName, String userLName, String password, String status, String email, java.sql.Timestamp lastmodifiedDate, String mobilenumber) {
        this.orgId = orgId;
        this.orgName = orgName;
        this.departmentName = departmentName;
        this.roleName = roleName;
        this.userId = userId;
        this.userFName = userFName;
        this.userLName = userLName;
        this.password = password;
        this.status = status;
        this.email = email;
        this.lastmodifiedDate = lastmodifiedDate;
        this.mobilenumber = mobilenumber;
    }

    public UserRegistration(Integer SNo, Integer orgId, String orgName, String departmentName, String roleName, String userId,
            String userFName, String userLName, String password, String status, String email, java.sql.Timestamp lastmodifiedDate, String mobilenumber) {
        this.SNo = SNo;
        this.orgId = orgId;
        this.orgName = orgName;
        this.departmentName = departmentName;
        this.roleName = roleName;
        this.userId = userId;
        this.userFName = userFName;
        this.userLName = userLName;
        this.password = password;
        this.status = status;
        this.email = email;
        this.lastmodifiedDate = lastmodifiedDate;
        this.mobilenumber = mobilenumber;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "S_NO", unique = true, nullable = false)
    public Integer getSNo() {
        return this.SNo;
    }

    public void setSNo(Integer SNo) {
        this.SNo = SNo;
    }

    @Column(name = "USER_ID", length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "USER_FIRST_NAME", length = 100)
    public String getUserFName() {
        return this.userFName;
    }

    public void setUserFName(String userFName) {
        this.userFName = userFName;
    }

    @Column(name = "USER_LAST_NAME", length = 100)
    public String getUserLName() {
        return userLName;
    }

    public void setUserLName(String userLName) {
        this.userLName = userLName;
    }

    @Column(name = "PASSWORD", length = 100)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "PASSWORD_EXPIRY", length = 10)
    public Date getPasswordExpiry() {
        return this.passwordExpiry;
    }

    public void setPasswordExpiry(Date passwordExpiry) {
        this.passwordExpiry = passwordExpiry;
    }

    @Column(name = "ORG_ID")
    public Integer getOrgId() {
        return this.orgId;
    }

    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTMODIFIED_DATE", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

    @Column(name = "DEPARTMENT_NAME", length = 100)
    public String getDepartmentName() {
        return this.departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    @Column(name = "ROLE_NAME", length = 100)
    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @Column(name = "ORG_NAME", length = 100)
    public String getOrgName() {
        return this.orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    @Column(name = "EMAIL", length = 100)
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "MOBILE_NUMBER", length = 50)
    public String getMobilenumber() {
        return mobilenumber;
    }

    public void setMobilenumber(String mobilenumber) {
        this.mobilenumber = mobilenumber;
    }

}
