package tenant.classes;
// Generated Sep 7, 2016 12:08:23 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TenantDetails generated by hbm2java
 */
@Entity
@Table(name = "utility_details", schema = "arete_tms"
)
public class UtilityDetails implements java.io.Serializable {

    private Integer SNo;

    private String tenantType;
    private String tenantCategory;
    private String tenantFname;
    private String tenantLname;

    private String tenantCode;
    private Date period;
    private Date toDate;
    private String tenantContactno;

    private Date creationDate;
    private Date lastmodifiedDate;
    private String electricBill;
    private String waterBill;
    private String status;
    private String parkingBill;
    private String maintainceBill;
    private String totalAmount;
    private String electricityBillno;
    private String waterBillno;
    private String prviousEBReding;
    private String prviousWBReding;
    private String currentEBReding;
    private String currentWBReding;
    private String totalEBUnints;
    private String totalWBUnints;
    //private String totalEBUnints;

    public UtilityDetails() {
    }

    public UtilityDetails(Integer SNo, String tenantType, String tenantFname, String tenantLname, String tenantCategory, String tenantCode, String electricBill, String waterBill, String parkingBill, String maintainceBill, String tenantContactno, String totalAmount) {
        this.tenantCategory = tenantCategory;
        this.tenantFname = tenantFname;
        this.tenantLname = tenantLname;
        this.tenantType = tenantType;
        this.tenantCode = tenantCode;
        this.tenantContactno = tenantContactno;
        this.electricBill = electricBill;
        this.waterBill = waterBill;
        this.parkingBill = parkingBill;
        this.parkingBill = totalAmount;

        this.maintainceBill = maintainceBill;
    }

    public UtilityDetails(String tenantFname, String tenantLname, String tenantCategory, String tenantCode, String electricBill, String waterBill, String parkingBill, String maintainceBill, String tenantContactno) {
        this.tenantCategory = tenantCategory;
        this.tenantFname = tenantFname;
        this.tenantLname = tenantLname;
        //this.tenantType = tenantType;
        this.tenantCode = tenantCode;
        this.tenantContactno = tenantContactno;
        this.electricBill = electricBill;
        this.waterBill = waterBill;
        this.parkingBill = parkingBill;
        this.maintainceBill = maintainceBill;
    }

    public UtilityDetails(String tenantCategory, String tenantFname, String tenantLname, String tenantType, String tenantCode, String tenantContactno, String electricBill, String waterBill, String parkingBill, String maintainceBill, String totalAmount, String electricityBillno, String waterBillno, String prviousEBReding, String prviousWBReding, String currentEBReding, String currentWBReding, String totalEBUnints, String totalWBUnints, Date period, Date toDate, Date creationDate, Date lastmodifiedDate, String status) {

        this.tenantCategory = tenantCategory;
        this.tenantFname = tenantFname;
        this.tenantLname = tenantLname;
        this.tenantType = tenantType;
        this.tenantCode = tenantCode;
        this.tenantContactno = tenantContactno;
        this.electricBill = electricBill;
        this.waterBill = waterBill;
        this.parkingBill = parkingBill;
        this.maintainceBill = maintainceBill;
        this.totalAmount = totalAmount;
        this.electricityBillno = electricityBillno;
        this.prviousEBReding = prviousEBReding;
        this.waterBillno = waterBillno;
        this.prviousWBReding = prviousWBReding;
        this.currentEBReding = currentEBReding;
        this.currentWBReding = currentWBReding;
        this.totalEBUnints = totalEBUnints;
        this.totalWBUnints = totalWBUnints;
        this.creationDate = creationDate;
        this.toDate=toDate;
        this.period=period;
        this.lastmodifiedDate = lastmodifiedDate;
        this.status = status;

    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "s_no", unique = true, nullable = false)
    public Integer getSNo() {
        return this.SNo;
    }

    public void setSNo(Integer SNo) {
        this.SNo = SNo;
    }

    @Column(name = "tenant_type", length = 60)
    public String getTenantType() {
        return this.tenantType;
    }

    public void setTenantType(String tenantType) {
        this.tenantType = tenantType;
    }

    @Column(name = "tenant_category", length = 60)
    public String getTenantCategory() {
        return this.tenantCategory;
    }

    public void setTenantCategory(String tenantCategory) {
        this.tenantCategory = tenantCategory;
    }

    @Column(name = "tenant_fname", length = 60)
    public String getTenantFname() {
        return this.tenantFname;
    }

    public void setTenantFname(String tenantFname) {
        this.tenantFname = tenantFname;
    }

    @Column(name = "tenant_lname", length = 60)
    public String getTenantLname() {
        return this.tenantLname;
    }

    public void setTenantLname(String tenantLname) {
        this.tenantLname = tenantLname;
    }

    @Column(name = "electricityBillno", length = 60)
    public String getElectricityBillno() {
        return this.electricityBillno;
    }

    public void setElectricityBillno(String electricityBillno) {
        this.electricityBillno = electricityBillno;
    }

    @Column(name = "tenant_code", length = 60)
    public String getTenantCode() {
        return this.tenantCode;
    }

    public void setTenantCode(String tenantCode) {
        this.tenantCode = tenantCode;
    }

    @Column(name = "tenant_contactno", length = 15)
    public String getTenantContactno() {
        return this.tenantContactno;
    }

    public void setTenantContactno(String tenantContactno) {
        this.tenantContactno = tenantContactno;
    }

    @Column(name = "water_bill", length = 60)
    public String getWaterBill() {
        return this.waterBill;
    }

    public void setWaterBill(String waterBill) {
        this.waterBill = waterBill;
    }

    @Column(name = "electric_bill", length = 60)
    public String getElectricBill() {
        return this.electricBill;
    }

    public void setElectricBill(String electricBill) {
        this.electricBill = electricBill;
    }

    @Column(name = "parking_bill", length = 60)
    public String getParkingBill() {
        return this.parkingBill;
    }

    public void setParkingBill(String parkingBill) {
        this.parkingBill = parkingBill;
    }

    @Column(name = "maintaince_bill", length = 60)
    public String getMaintainceBill() {
        return this.maintainceBill;
    }

    public void setMaintainceBill(String maintainceBill) {
        this.maintainceBill = maintainceBill;
    }

    @Column(name = "Water_MeeterNo", length = 60)
    public String getWaterBillno() {
        return this.waterBillno;
    }

    public void setWaterBillno(String waterBillno) {
        this.waterBillno = waterBillno;
    }

    @Column(name = "Prvious_EBReding", length = 60)
    public String getPrviousEBReding() {
        return this.prviousEBReding;
    }

    public void setPrviousEBReding(String prviousEBReding) {
        this.prviousEBReding = prviousEBReding;
    }

    @Column(name = "Prvious_WBReding", length = 60)
    public String getPrviousWBReding() {
        return this.prviousWBReding;
    }

    public void setPrviousWBReding(String prviousWBReding) {
        this.prviousWBReding = prviousWBReding;
    }

    @Column(name = "Current_EBReding", length = 60)
    public String getCurrentEBReding() {
        return this.currentEBReding;
    }

    public void setCurrentEBReding(String currentEBReding) {
        this.currentEBReding = currentEBReding;
    }

    @Column(name = "Current_WBReding", length = 60)
    public String getCurrentWBReding() {
        return this.currentWBReding;
    }

    public void setCurrentWBReding(String currentWBReding) {
        this.currentWBReding = currentWBReding;
    }

    @Column(name = "Total_EBUnints", length = 60)
    public String getTotalEBUnints() {
        return this.totalEBUnints;
    }

    public void setTotalEBUnints(String totalEBUnints) {
        this.totalEBUnints = totalEBUnints;
    }

    @Column(name = "Total_WBUnints", length = 60)
    public String getTotalWBUnints() {
        return this.totalWBUnints;
    }

    public void setTotalWBUnints(String totalWBUnints) {
        this.totalWBUnints = totalWBUnints;
    }

    @Column(name = "totalAmount", length = 60)
    public String getTotalAmount() {
        return this.totalAmount;
    }

    public void setTotalAmount(String totalAmount) {
        this.totalAmount = totalAmount;
    }

    @Column(name = "status", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "creation_date", length = 60)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "period", length = 20)
    public Date getPeriod() {
        return this.period;
    }

    public void setPeriod(Date period) {
        this.period = period;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "toDate", length = 20)
    public Date getToDate() {
        return this.toDate;
    }

    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lastmodified_date", length = 19)
    public Date getLastmodifiedDate() {
        return this.lastmodifiedDate;
    }

    public void setLastmodifiedDate(Date lastmodifiedDate) {
        this.lastmodifiedDate = lastmodifiedDate;
    }

}
