package tenant.classes;
// Generated 6 Sep, 2016 12:51:30 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vacating generated by hbm2java
 */
@Entity
@Table(name = "vacating", schema = "arete_tms"
)
public class Vacating implements java.io.Serializable {

    private Integer sno;
    private String orgId;
    private String userId;
    private String vacatingCode;
    private String tenantName;
    private String tenanCode;
    private String propertyName;
    private String propertyNo;
    private Date vacatingFillDate;
    private Date contracrEndDate;
    private String noticPeriod;
    private String anyDue;
    private String advanceeToBePaid;
    private String reasonForVacating;
    private String attribute1;
    private String attribute2;
    private String attribute3;
    private String attribute4;
    private String attribute5;
    private String advDues;
    private String rentDues;
    private String serviceDues;
    private String utility1;
    private String utility2;
    private String finalSettlementAmmount;
    private String status;
    private Date lastmodefiedDate;
    private Date dateofvacate;

   
    
    public Vacating() {
    }

    public Vacating(String userId) {
        this.userId = userId;
    }

    public Vacating(String orgId, String userId, String vacatingCode, String tenanCode, String tenantName, String propertyName, String propertyNo, Date vacatingFillDate, Date contracrEndDate, String noticPeriod, String advanceeToBePaid, String reasonForVacating, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, String advDues, String rentDues, String serviceDues, String utility1, String utility2, String finalSettlementAmmount, String status, Date lastmodefiedDate, Date dateofvacate) {
        this.orgId = orgId;
        this.userId = userId;
        this.vacatingCode = vacatingCode;
        this.tenanCode = tenanCode;
        this.tenantName = tenantName;
        this.propertyName = propertyName;
        this.propertyNo = propertyNo;
        this.vacatingFillDate = vacatingFillDate;
        this.contracrEndDate = contracrEndDate;
        this.noticPeriod = noticPeriod;
        this.anyDue = anyDue;
        this.advanceeToBePaid = advanceeToBePaid;
        this.reasonForVacating = reasonForVacating;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.advDues = advDues;
        this.rentDues = rentDues;
        this.serviceDues = serviceDues;
        this.utility1 = utility1;
        this.utility2 = utility2;
        this.finalSettlementAmmount = finalSettlementAmmount;
        this.status = status;
        this.lastmodefiedDate = lastmodefiedDate;
        this.dateofvacate=dateofvacate;
    }

    public Vacating(Integer sno, String orgId, String userId, String vacatingCode, String tenanCode, String tenantName, String propertyName, String propertyNo, Date vacatingFillDate, Date contracrEndDate, String noticPeriod, String advanceeToBePaid, String reasonForVacating, String attribute1, String attribute2, String attribute3, String attribute4, String attribute5, String advDues, String rentDues, String serviceDues, String utility1, String utility2, String finalSettlementAmmount, String status, Date lastmodefiedDate,Date dateofvacate) {
        this.sno = sno;
        this.orgId = orgId;
        this.userId = userId;
        this.vacatingCode = vacatingCode;
        this.tenanCode = tenanCode;
        this.tenantName = tenantName;
        this.propertyName = propertyName;
        this.propertyNo = propertyNo;
        this.vacatingFillDate = vacatingFillDate;
        this.contracrEndDate = contracrEndDate;
        this.noticPeriod = noticPeriod;
        this.anyDue = anyDue;
        this.advanceeToBePaid = advanceeToBePaid;
        this.reasonForVacating = reasonForVacating;
        this.attribute1 = attribute1;
        this.attribute2 = attribute2;
        this.attribute3 = attribute3;
        this.attribute4 = attribute4;
        this.attribute5 = attribute5;
        this.advDues = advDues;
        this.rentDues = rentDues;
        this.serviceDues = serviceDues;
        this.utility1 = utility1;
        this.utility2 = utility2;
        this.finalSettlementAmmount = finalSettlementAmmount;
        this.status = status;
        this.lastmodefiedDate = lastmodefiedDate;
        this.dateofvacate=dateofvacate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "sno", unique = true, nullable = false)
    public Integer getSno() {
        return this.sno;
    }

    public void setSno(Integer sno) {
        this.sno = sno;
    }

    @Column(name = "org_Id", length = 20)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "user_Id", nullable = false, length = 20)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "Vacating_Code", length = 50)
    public String getVacatingCode() {
        return this.vacatingCode;
    }

    public void setVacatingCode(String vacatingCode) {
        this.vacatingCode = vacatingCode;
    }

    @Column(name = "Tenant_Code", length = 100)
    public String getTenanCode() {
        return tenanCode;
    }

    public void setTenanCode(String tenanCode) {
        this.tenanCode = tenanCode;
    }

    @Column(name = "Tenant_Name", length = 100)
    public String getTenantName() {
        return this.tenantName;
    }

    public void setTenantName(String tenantName) {
        this.tenantName = tenantName;
    }

    @Column(name = "Property_name", length = 100)
    public String getPropertyName() {
        return this.propertyName;
    }

    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }

    @Column(name = "Property_No", length = 100)
    public String getPropertyNo() {
        return this.propertyNo;
    }

    public void setPropertyNo(String propertyNo) {
        this.propertyNo = propertyNo;
    }

    @Column(name = "Vacating_FillDate", length = 50)
    public Date getVacatingFillDate() {
        return this.vacatingFillDate;
    }

    public void setVacatingFillDate(Date vacatingFillDate) {
        this.vacatingFillDate = vacatingFillDate;
    }

    @Column(name = "Contracr_EndDate", length = 50)
    public Date getContracrEndDate() {
        return this.contracrEndDate;
    }
    
    public void setContracrEndDate(Date contracrEndDate) {
        this.contracrEndDate = contracrEndDate;
    }
    @Column(name = "Vacate_Date", length = 50)
     public Date getDateofvacate() {
        return dateofvacate;
    }

    public void setDateofvacate(Date dateofvacate) {
        this.dateofvacate = dateofvacate;
    }
    
    @Column(name = "Notic_Period", length = 50)
    public String getNoticPeriod() {
        return this.noticPeriod;
    }

    public void setNoticPeriod(String noticPeriod) {
        this.noticPeriod = noticPeriod;
    }

    @Column(name = "Any_Due", length = 50)
    public String getAnyDue() {
        return this.anyDue;
    }

    public void setAnyDue(String anyDue) {
        this.anyDue = anyDue;
    }

    @Column(name = "Advancee_ToBe_Paid", length = 50)
    public String getAdvanceeToBePaid() {
        return this.advanceeToBePaid;
    }

    public void setAdvanceeToBePaid(String advanceeToBePaid) {
        this.advanceeToBePaid = advanceeToBePaid;
    }

    @Column(name = "Reason_For_Vacating", length = 500)
    public String getReasonForVacating() {
        return this.reasonForVacating;
    }

    public void setReasonForVacating(String reasonForVacating) {
        this.reasonForVacating = reasonForVacating;
    }

    @Column(name = "Attribute1", length = 50)
    public String getAttribute1() {
        return attribute1;
    }

    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    @Column(name = "Attribute2", length = 50)
    public String getAttribute2() {
        return attribute2;
    }

    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    @Column(name = "Attribute3", length = 50)
    public String getAttribute3() {
        return attribute3;
    }

    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    @Column(name = "Attribute4", length = 500)
    public String getAttribute4() {
        return attribute4;
    }

    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    @Column(name = "Attribute5", length = 500)
    public String getAttribute5() {
        return attribute5;
    }

    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    @Column(name = "Status", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Lastmodefied_Date", length = 19)
    public Date getLastmodefiedDate() {
        return this.lastmodefiedDate;
    }

    public void setLastmodefiedDate(Date lastmodefiedDate) {
        this.lastmodefiedDate = lastmodefiedDate;
    }

    @Column(name = "Adv_Dues", length = 50)
    public String getAdvDues() {
        return advDues;
    }

    public void setAdvDues(String advDues) {
        this.advDues = advDues;
    }

    @Column(name = "Rent_Dues", length = 50)
    public String getRentDues() {
        return rentDues;
    }

    public void setRentDues(String rentDues) {
        this.rentDues = rentDues;
    }

    @Column(name = "Service_Dues", length = 50)
    public String getServiceDues() {
        return serviceDues;
    }

    public void setServiceDues(String serviceDues) {
        this.serviceDues = serviceDues;
    }

    @Column(name = "Utility_1", length = 50)
    public String getUtility1() {
        return utility1;
    }

    public void setUtility1(String utility1) {
        this.utility1 = utility1;
    }

    @Column(name = "Utility_2", length = 50)
    public String getUtility2() {
        return utility2;
    }

    public void setUtility2(String utility2) {
        this.utility2 = utility2;
    }

    @Column(name = "Final_Settlement", length = 50)
    public String getFinalSettlementAmmount() {
        return finalSettlementAmmount;
    }

    public void setFinalSettlementAmmount(String finalSettlementAmmount) {
        this.finalSettlementAmmount = finalSettlementAmmount;
    }

}
